// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.gematik.consumer.signatureservice31

import de.gematik.connector.api.soap.SoapOperation

object Operations {
  val VerifyDocument: SoapOperation =
      SoapOperation("VerifyDocument", "http://ws.gematik.de/consumer/SignatureService/v3.1#VerifyDocument", "soap11")

  val SignDocument: SoapOperation =
      SoapOperation("SignDocument", "http://ws.gematik.de/consumer/SignatureService/v3.1#SignDocument", "soap11")

  val ExternalAuthenticate: SoapOperation =
      SoapOperation("ExternalAuthenticate", "http://ws.gematik.de/consumer/SignatureService/v3.1#ExternalAuthenticate", "soap11")
}
