// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.gematik.conn.cardservice811

import kotlin.collections.List
import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName

@Serializable
@XmlSerialName(
  "Cards",
  namespace = "http://ws.gematik.de/conn/CardService/v8.1",
)
data class Cards(
  @XmlElement(true)
  @XmlSerialName("Card")
  val card: List<Card> = emptyList(),
)
