// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.gematik.conn.cardservice811

import de.gematik.connector.api.gematik.conn.connectorcommon50.Status
import kotlin.Int
import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName

@Serializable
@XmlSerialName(
  "GetPinStatusResponse",
  namespace = "http://ws.gematik.de/conn/CardService/v8.1",
)
data class GetPinStatusResponse(
  @XmlElement(true)
  @XmlSerialName(
    "Status",
    namespace = "http://ws.gematik.de/conn/ConnectorCommon/v5.0",
  )
  val status: Status,
  @XmlElement(true)
  @XmlSerialName("PinStatus")
  val pinStatus: PinStatusEnum? = null,
  @XmlElement(true)
  @XmlSerialName("LeftTries")
  val leftTries: Int? = null,
)
