// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.gematik.conn.cardservice811

import de.gematik.connector.api.soap.SoapOperation

object Operations {
  val VerifyPin: SoapOperation =
      SoapOperation("VerifyPin", "http://ws.gematik.de/conn/CardService/v8.1#VerifyPin", "soap11")

  val ChangePin: SoapOperation =
      SoapOperation("ChangePin", "http://ws.gematik.de/conn/CardService/v8.1#ChangePin", "soap11")

  val UnblockPin: SoapOperation =
      SoapOperation("UnblockPin", "http://ws.gematik.de/conn/CardService/v8.1#UnblockPin", "soap11")

  val GetPinStatus: SoapOperation =
      SoapOperation("GetPinStatus", "http://ws.gematik.de/conn/CardService/v8.1#GetPinStatus", "soap11")
}
