// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.gematik.conn.cardservice811

import kotlin.Int
import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName

@Serializable
data class VersionInfoType(
  @XmlElement(true)
  @XmlSerialName(
    "Major",
    namespace = "http://ws.gematik.de/conn/CardService/v8.1",
  )
  val major: Int,
  @XmlElement(true)
  @XmlSerialName(
    "Minor",
    namespace = "http://ws.gematik.de/conn/CardService/v8.1",
  )
  val minor: Int,
  @XmlElement(true)
  @XmlSerialName(
    "Revision",
    namespace = "http://ws.gematik.de/conn/CardService/v8.1",
  )
  val revision: Int,
)
