// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.etsi022312

import kotlin.collections.List
import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName

@Serializable
@XmlSerialName(
  "AdditionalInformation",
  namespace = "http://uri.etsi.org/02231/v2#",
)
data class AdditionalInformation(
  @XmlElement(true)
  @XmlSerialName("TextualInformation")
  val textualInformation: List<MultiLangStringType> = emptyList(),
  @XmlElement(true)
  @XmlSerialName("OtherInformation")
  val otherInformation: List<AnyType> = emptyList(),
)
