// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.etsi022312

import kotlin.String
import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName

@Serializable
@XmlSerialName(
  "AdditionalServiceInformation",
  namespace = "http://uri.etsi.org/02231/v2#",
)
data class AdditionalServiceInformation(
  @XmlElement(true)
  @XmlSerialName("URI")
  val uri: NonEmptyMultiLangURIType,
  @XmlElement(true)
  @XmlSerialName("InformationValue")
  val informationValue: String? = null,
  @XmlElement(true)
  @XmlSerialName("OtherInformation")
  val otherInformation: AnyType? = null,
)
