// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.etsi022312

import de.gematik.connector.api.w3200009.xmldsig.KeyValue
import kotlin.String
import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName

@Serializable
data class DigitalIdentityType(
  @XmlElement(true)
  @XmlSerialName(
    "X509Certificate",
    namespace = "http://uri.etsi.org/02231/v2#",
  )
  val x509Certificate: String? = null,
  @XmlElement(true)
  @XmlSerialName(
    "X509SubjectName",
    namespace = "http://uri.etsi.org/02231/v2#",
  )
  val x509SubjectName: String? = null,
  @XmlElement(true)
  @XmlSerialName(
    "KeyValue",
    namespace = "http://www.w3.org/2000/09/xmldsig#",
  )
  val keyValue: KeyValue? = null,
  @XmlElement(true)
  @XmlSerialName(
    "X509SKI",
    namespace = "http://uri.etsi.org/02231/v2#",
  )
  val x509Ski: String? = null,
  @XmlElement(true)
  @XmlSerialName(
    "Other",
    namespace = "http://uri.etsi.org/02231/v2#",
  )
  val other: AnyType? = null,
)
