// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.etsi022312

import kotlin.Boolean
import kotlin.String
import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName

@Serializable
data class ExtensionType(
  @XmlElement(false)
  @XmlSerialName("Critical")
  val critical: Boolean,
  @XmlElement(true)
  val unknownContent: String? = null,
)
