// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.etsi022312

import kotlin.String
import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName
import nl.adaptivity.xmlutil.serialization.XmlValue

@Serializable
data class MultiLangNormStringType(
  @XmlElement(false)
  @XmlSerialName(
    "lang",
    namespace = "http://www.w3.org/XML/1998/namespace",
  )
  val lang: String? = null,
  @XmlValue(true)
  val charData: String,
)
