// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.etsi022312

import kotlin.String
import kotlin.collections.List
import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName

@Serializable
data class NonEmptyURIListType(
  @XmlElement(true)
  @XmlSerialName(
    "URI",
    namespace = "http://uri.etsi.org/02231/v2#",
  )
  val uri: List<String> = emptyList(),
)
