// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.etsi022312

import kotlin.collections.List
import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName

@Serializable
@XmlSerialName(
  "PolicyOrLegalNotice",
  namespace = "http://uri.etsi.org/02231/v2#",
)
data class PolicyOrLegalNotice(
  @XmlElement(true)
  @XmlSerialName("TSLPolicy")
  val tslPolicy: List<NonEmptyMultiLangURIType> = emptyList(),
  @XmlElement(true)
  @XmlSerialName("TSLLegalNotice")
  val tslLegalNotice: List<MultiLangStringType> = emptyList(),
)
