// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.etsi022312

import kotlin.String
import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName

@Serializable
data class PostalAddressType(
  @XmlElement(false)
  @XmlSerialName(
    "lang",
    namespace = "http://www.w3.org/XML/1998/namespace",
  )
  val lang: String? = null,
  @XmlElement(true)
  @XmlSerialName(
    "StreetAddress",
    namespace = "http://uri.etsi.org/02231/v2#",
  )
  val streetAddress: String,
  @XmlElement(true)
  @XmlSerialName(
    "Locality",
    namespace = "http://uri.etsi.org/02231/v2#",
  )
  val locality: String,
  @XmlElement(true)
  @XmlSerialName(
    "StateOrProvince",
    namespace = "http://uri.etsi.org/02231/v2#",
  )
  val stateOrProvince: String? = null,
  @XmlElement(true)
  @XmlSerialName(
    "PostalCode",
    namespace = "http://uri.etsi.org/02231/v2#",
  )
  val postalCode: String? = null,
  @XmlElement(true)
  @XmlSerialName(
    "CountryName",
    namespace = "http://uri.etsi.org/02231/v2#",
  )
  val countryName: String,
)
