// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.etsi022312

import kotlin.String
import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName

@Serializable
@XmlSerialName(
  "PostalAddress",
  namespace = "http://uri.etsi.org/02231/v2#",
)
data class PostalAddress(
  @XmlElement(false)
  @XmlSerialName(
    "lang",
    namespace = "http://www.w3.org/XML/1998/namespace",
  )
  val lang: String? = null,
  @XmlElement(true)
  @XmlSerialName("StreetAddress")
  val streetAddress: String,
  @XmlElement(true)
  @XmlSerialName("Locality")
  val locality: String,
  @XmlElement(true)
  @XmlSerialName("StateOrProvince")
  val stateOrProvince: String? = null,
  @XmlElement(true)
  @XmlSerialName("PostalCode")
  val postalCode: String? = null,
  @XmlElement(true)
  @XmlSerialName("CountryName")
  val countryName: String,
)
