// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.etsi022312

import kotlin.Int
import kotlin.String
import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName

@Serializable
@XmlSerialName(
  "SchemeInformation",
  namespace = "http://uri.etsi.org/02231/v2#",
)
data class SchemeInformation(
  @XmlElement(true)
  @XmlSerialName("TSLVersionIdentifier")
  val tslVersionIdentifier: Int,
  @XmlElement(true)
  @XmlSerialName("TSLSequenceNumber")
  val tslSequenceNumber: Int,
  @XmlElement(true)
  @XmlSerialName("TSLType")
  val tslType: String,
  @XmlElement(true)
  @XmlSerialName("SchemeOperatorName")
  val schemeOperatorName: SchemeOperatorName,
  @XmlElement(true)
  @XmlSerialName("SchemeOperatorAddress")
  val schemeOperatorAddress: AddressType,
  @XmlElement(true)
  @XmlSerialName("SchemeName")
  val schemeName: SchemeName,
  @XmlElement(true)
  @XmlSerialName("SchemeInformationURI")
  val schemeInformationUri: SchemeInformationURI,
  @XmlElement(true)
  @XmlSerialName("StatusDeterminationApproach")
  val statusDeterminationApproach: String,
  @XmlElement(true)
  @XmlSerialName("SchemeTypeCommunityRules")
  val schemeTypeCommunityRules: SchemeTypeCommunityRules? = null,
  @XmlElement(true)
  @XmlSerialName("SchemeTerritory")
  val schemeTerritory: String? = null,
  @XmlElement(true)
  @XmlSerialName("PolicyOrLegalNotice")
  val policyOrLegalNotice: PolicyOrLegalNotice? = null,
  @XmlElement(true)
  @XmlSerialName("HistoricalInformationPeriod")
  val historicalInformationPeriod: Int,
  @XmlElement(true)
  @XmlSerialName("PointersToOtherTSL")
  val pointersToOtherTsl: PointersToOtherTSL? = null,
  @XmlElement(true)
  @XmlSerialName("ListIssueDateTime")
  val listIssueDateTime: String,
  @XmlElement(true)
  @XmlSerialName("NextUpdate")
  val nextUpdate: NextUpdate,
  @XmlElement(true)
  @XmlSerialName("DistributionPoints")
  val distributionPoints: DistributionPoints? = null,
  @XmlElement(true)
  @XmlSerialName("SchemeExtensions")
  val schemeExtensions: ExtensionsListType? = null,
)
