// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.etsi022312

import kotlin.collections.List
import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName

@Serializable
@XmlSerialName(
  "SchemeInformationURI",
  namespace = "http://uri.etsi.org/02231/v2#",
)
data class SchemeInformationURI(
  @XmlElement(true)
  @XmlSerialName("URI")
  val uri: List<NonEmptyMultiLangURIType> = emptyList(),
)
