// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.etsi022312

import kotlin.String
import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName

@Serializable
@XmlSerialName(
  "ServiceInformation",
  namespace = "http://uri.etsi.org/02231/v2#",
)
data class ServiceInformation(
  @XmlElement(true)
  @XmlSerialName("ServiceTypeIdentifier")
  val serviceTypeIdentifier: String,
  @XmlElement(true)
  @XmlSerialName("ServiceName")
  val serviceName: InternationalNamesType,
  @XmlElement(true)
  @XmlSerialName("ServiceDigitalIdentity")
  val serviceDigitalIdentity: ServiceDigitalIdentity,
  @XmlElement(true)
  @XmlSerialName("ServiceStatus")
  val serviceStatus: String,
  @XmlElement(true)
  @XmlSerialName("StatusStartingTime")
  val statusStartingTime: String,
  @XmlElement(true)
  @XmlSerialName("SchemeServiceDefinitionURI")
  val schemeServiceDefinitionUri: NonEmptyMultiLangURIListType? = null,
  @XmlElement(true)
  @XmlSerialName("ServiceSupplyPoints")
  val serviceSupplyPoints: ServiceSupplyPoints? = null,
  @XmlElement(true)
  @XmlSerialName("TSPServiceDefinitionURI")
  val tspServiceDefinitionUri: NonEmptyMultiLangURIListType? = null,
  @XmlElement(true)
  @XmlSerialName("ServiceInformationExtensions")
  val serviceInformationExtensions: ExtensionsListType? = null,
)
