// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.etsi022312

import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName

@Serializable
@XmlSerialName(
  "TrustServiceProvider",
  namespace = "http://uri.etsi.org/02231/v2#",
)
data class TrustServiceProvider(
  @XmlElement(true)
  @XmlSerialName("TSPInformation")
  val tspInformation: TSPInformation,
  @XmlElement(true)
  @XmlSerialName("TSPServices")
  val tspServices: TSPServices,
)
