// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.etsi022312

import kotlin.Int
import kotlin.String
import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName

@Serializable
data class TSLSchemeInformationType(
  @XmlElement(true)
  @XmlSerialName(
    "TSLVersionIdentifier",
    namespace = "http://uri.etsi.org/02231/v2#",
  )
  val tslVersionIdentifier: Int,
  @XmlElement(true)
  @XmlSerialName(
    "TSLSequenceNumber",
    namespace = "http://uri.etsi.org/02231/v2#",
  )
  val tslSequenceNumber: Int,
  @XmlElement(true)
  @XmlSerialName(
    "TSLType",
    namespace = "http://uri.etsi.org/02231/v2#",
  )
  val tslType: String,
  @XmlElement(true)
  @XmlSerialName(
    "SchemeOperatorName",
    namespace = "http://uri.etsi.org/02231/v2#",
  )
  val schemeOperatorName: SchemeOperatorName,
  @XmlElement(true)
  @XmlSerialName(
    "SchemeOperatorAddress",
    namespace = "http://uri.etsi.org/02231/v2#",
  )
  val schemeOperatorAddress: AddressType,
  @XmlElement(true)
  @XmlSerialName(
    "SchemeName",
    namespace = "http://uri.etsi.org/02231/v2#",
  )
  val schemeName: SchemeName,
  @XmlElement(true)
  @XmlSerialName(
    "SchemeInformationURI",
    namespace = "http://uri.etsi.org/02231/v2#",
  )
  val schemeInformationUri: SchemeInformationURI,
  @XmlElement(true)
  @XmlSerialName(
    "StatusDeterminationApproach",
    namespace = "http://uri.etsi.org/02231/v2#",
  )
  val statusDeterminationApproach: String,
  @XmlElement(true)
  @XmlSerialName(
    "SchemeTypeCommunityRules",
    namespace = "http://uri.etsi.org/02231/v2#",
  )
  val schemeTypeCommunityRules: SchemeTypeCommunityRules? = null,
  @XmlElement(true)
  @XmlSerialName(
    "SchemeTerritory",
    namespace = "http://uri.etsi.org/02231/v2#",
  )
  val schemeTerritory: String? = null,
  @XmlElement(true)
  @XmlSerialName(
    "PolicyOrLegalNotice",
    namespace = "http://uri.etsi.org/02231/v2#",
  )
  val policyOrLegalNotice: PolicyOrLegalNotice? = null,
  @XmlElement(true)
  @XmlSerialName(
    "HistoricalInformationPeriod",
    namespace = "http://uri.etsi.org/02231/v2#",
  )
  val historicalInformationPeriod: Int,
  @XmlElement(true)
  @XmlSerialName(
    "PointersToOtherTSL",
    namespace = "http://uri.etsi.org/02231/v2#",
  )
  val pointersToOtherTsl: PointersToOtherTSL? = null,
  @XmlElement(true)
  @XmlSerialName(
    "ListIssueDateTime",
    namespace = "http://uri.etsi.org/02231/v2#",
  )
  val listIssueDateTime: String,
  @XmlElement(true)
  @XmlSerialName(
    "NextUpdate",
    namespace = "http://uri.etsi.org/02231/v2#",
  )
  val nextUpdate: NextUpdate,
  @XmlElement(true)
  @XmlSerialName(
    "DistributionPoints",
    namespace = "http://uri.etsi.org/02231/v2#",
  )
  val distributionPoints: DistributionPoints? = null,
  @XmlElement(true)
  @XmlSerialName(
    "SchemeExtensions",
    namespace = "http://uri.etsi.org/02231/v2#",
  )
  val schemeExtensions: ExtensionsListType? = null,
)
