// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.etsi022312

import kotlin.String
import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName

@Serializable
data class TSPServiceInformationType(
  @XmlElement(true)
  @XmlSerialName(
    "ServiceTypeIdentifier",
    namespace = "http://uri.etsi.org/02231/v2#",
  )
  val serviceTypeIdentifier: String,
  @XmlElement(true)
  @XmlSerialName(
    "ServiceName",
    namespace = "http://uri.etsi.org/02231/v2#",
  )
  val serviceName: InternationalNamesType,
  @XmlElement(true)
  @XmlSerialName(
    "ServiceDigitalIdentity",
    namespace = "http://uri.etsi.org/02231/v2#",
  )
  val serviceDigitalIdentity: ServiceDigitalIdentity,
  @XmlElement(true)
  @XmlSerialName(
    "ServiceStatus",
    namespace = "http://uri.etsi.org/02231/v2#",
  )
  val serviceStatus: String,
  @XmlElement(true)
  @XmlSerialName(
    "StatusStartingTime",
    namespace = "http://uri.etsi.org/02231/v2#",
  )
  val statusStartingTime: String,
  @XmlElement(true)
  @XmlSerialName(
    "SchemeServiceDefinitionURI",
    namespace = "http://uri.etsi.org/02231/v2#",
  )
  val schemeServiceDefinitionUri: NonEmptyMultiLangURIListType? = null,
  @XmlElement(true)
  @XmlSerialName(
    "ServiceSupplyPoints",
    namespace = "http://uri.etsi.org/02231/v2#",
  )
  val serviceSupplyPoints: ServiceSupplyPoints? = null,
  @XmlElement(true)
  @XmlSerialName(
    "TSPServiceDefinitionURI",
    namespace = "http://uri.etsi.org/02231/v2#",
  )
  val tspServiceDefinitionUri: NonEmptyMultiLangURIListType? = null,
  @XmlElement(true)
  @XmlSerialName(
    "ServiceInformationExtensions",
    namespace = "http://uri.etsi.org/02231/v2#",
  )
  val serviceInformationExtensions: ExtensionsListType? = null,
)
