// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.etsi022312

import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName

@Serializable
data class TSPType(
  @XmlElement(true)
  @XmlSerialName(
    "TSPInformation",
    namespace = "http://uri.etsi.org/02231/v2#",
  )
  val tspInformation: TSPInformation,
  @XmlElement(true)
  @XmlSerialName(
    "TSPServices",
    namespace = "http://uri.etsi.org/02231/v2#",
  )
  val tspServices: TSPServices,
)
