// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.gematik.int.version.productinformation11

import kotlin.String
import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName

@Serializable
data class ProductMiscellaneous(
  @XmlElement(true)
  @XmlSerialName(
    "ProductVendorName",
    namespace = "http://ws.gematik.de/int/version/ProductInformation/v1.1",
  )
  val productVendorName: String,
  @XmlElement(true)
  @XmlSerialName(
    "ProductName",
    namespace = "http://ws.gematik.de/int/version/ProductInformation/v1.1",
  )
  val productName: String,
)
