// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.gematik.int.version.productinformation11

import kotlin.String
import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName

@Serializable
data class ProductVersion(
  @XmlElement(true)
  @XmlSerialName(
    "Local",
    namespace = "http://ws.gematik.de/int/version/ProductInformation/v1.1",
  )
  val local: ProductVersionLocal? = null,
  @XmlElement(true)
  @XmlSerialName(
    "Central",
    namespace = "http://ws.gematik.de/int/version/ProductInformation/v1.1",
  )
  val central: String? = null,
)
