// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.gematik.int.version.productinformation11

import kotlin.String
import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName

@Serializable
data class ProductVersionLocal(
  @XmlElement(true)
  @XmlSerialName(
    "HWVersion",
    namespace = "http://ws.gematik.de/int/version/ProductInformation/v1.1",
  )
  val hwVersion: String,
  @XmlElement(true)
  @XmlSerialName(
    "FWVersion",
    namespace = "http://ws.gematik.de/int/version/ProductInformation/v1.1",
  )
  val fwVersion: String,
)
