// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.gematik.conn.certificateservice60

import kotlin.String
import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName

@Serializable
data class CertificateExpirationType(
  @XmlElement(true)
  @XmlSerialName(
    "CtID",
    namespace = "http://ws.gematik.de/conn/CertificateService/v6.0",
  )
  val ctId: String,
  @XmlElement(true)
  @XmlSerialName(
    "CardHandle",
    namespace = "http://ws.gematik.de/conn/ConnectorCommon/v5.0",
  )
  val cardHandle: String,
  @XmlElement(true)
  @XmlSerialName(
    "ICCSN",
    namespace = "http://ws.gematik.de/conn/CertificateService/v6.0",
  )
  val iccsn: String,
  @XmlElement(true)
  @XmlSerialName(
    "subject_commonName",
    namespace = "http://ws.gematik.de/conn/CertificateService/v6.0",
  )
  val subjectCommonName: String,
  @XmlElement(true)
  @XmlSerialName(
    "serialNumber",
    namespace = "http://ws.gematik.de/conn/CertificateService/v6.0",
  )
  val serialNumber: String,
  @XmlElement(true)
  @XmlSerialName(
    "validity",
    namespace = "http://ws.gematik.de/conn/CertificateService/v6.0",
  )
  val validity: String,
)
