// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.gematik.conn.certificateservice60

import de.gematik.connector.api.gematik.tel.error20.Error
import de.gematik.connector.api.soap.SoapEnvelope
import kotlin.Boolean
import kotlin.String
import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName

@Serializable
@XmlSerialName(
  "Envelope",
  namespace = "http://schemas.xmlsoap.org/soap/envelope/",
  prefix = "SOAP-ENV",
)
data class CheckCertificateExpirationEnvelope(
  @XmlElement(true)
  @XmlSerialName(
    "Body",
    namespace = "http://schemas.xmlsoap.org/soap/envelope/",
    prefix = "SOAP-ENV",
  )
  val body: Body,
) : SoapEnvelope {
  override fun isFault(): Boolean = false

  @Serializable
  data class Body(
    @XmlElement(true)
    val checkCertificateExpiration: CheckCertificateExpiration? = null,
  )
}

@Serializable
@XmlSerialName(
  "Envelope",
  namespace = "http://schemas.xmlsoap.org/soap/envelope/",
  prefix = "SOAP-ENV",
)
data class CheckCertificateExpirationResponseEnvelope(
  @XmlElement(true)
  @XmlSerialName(
    "Body",
    namespace = "http://schemas.xmlsoap.org/soap/envelope/",
    prefix = "SOAP-ENV",
  )
  val body: Body,
) : SoapEnvelope {
  override fun isFault(): Boolean = body.fault != null

  @Serializable
  data class Body(
    @XmlElement(true)
    val checkCertificateExpirationResponse: CheckCertificateExpirationResponse? = null,
    @XmlElement(true)
    @XmlSerialName(
      "Fault",
      namespace = "http://schemas.xmlsoap.org/soap/envelope/",
      prefix = "SOAP-ENV",
    )
    val fault: Fault? = null,
  )

  @Serializable
  data class Fault(
    @XmlElement(true)
    val faultcode: String = "",
    @XmlElement(true)
    val faultstring: String = "",
    @XmlElement(true)
    val faultactor: String? = null,
    @XmlElement(true)
    val detail: Error? = null,
  )
}

@Serializable
@XmlSerialName(
  "Envelope",
  namespace = "http://schemas.xmlsoap.org/soap/envelope/",
  prefix = "SOAP-ENV",
)
data class ReadCardCertificateEnvelope(
  @XmlElement(true)
  @XmlSerialName(
    "Body",
    namespace = "http://schemas.xmlsoap.org/soap/envelope/",
    prefix = "SOAP-ENV",
  )
  val body: Body,
) : SoapEnvelope {
  override fun isFault(): Boolean = false

  @Serializable
  data class Body(
    @XmlElement(true)
    val readCardCertificate: ReadCardCertificate? = null,
  )
}

@Serializable
@XmlSerialName(
  "Envelope",
  namespace = "http://schemas.xmlsoap.org/soap/envelope/",
  prefix = "SOAP-ENV",
)
data class ReadCardCertificateResponseEnvelope(
  @XmlElement(true)
  @XmlSerialName(
    "Body",
    namespace = "http://schemas.xmlsoap.org/soap/envelope/",
    prefix = "SOAP-ENV",
  )
  val body: Body,
) : SoapEnvelope {
  override fun isFault(): Boolean = body.fault != null

  @Serializable
  data class Body(
    @XmlElement(true)
    val readCardCertificateResponse: ReadCardCertificateResponse? = null,
    @XmlElement(true)
    @XmlSerialName(
      "Fault",
      namespace = "http://schemas.xmlsoap.org/soap/envelope/",
      prefix = "SOAP-ENV",
    )
    val fault: Fault? = null,
  )

  @Serializable
  data class Fault(
    @XmlElement(true)
    val faultcode: String = "",
    @XmlElement(true)
    val faultstring: String = "",
    @XmlElement(true)
    val faultactor: String? = null,
    @XmlElement(true)
    val detail: Error? = null,
  )
}

@Serializable
@XmlSerialName(
  "Envelope",
  namespace = "http://schemas.xmlsoap.org/soap/envelope/",
  prefix = "SOAP-ENV",
)
data class VerifyCertificateEnvelope(
  @XmlElement(true)
  @XmlSerialName(
    "Body",
    namespace = "http://schemas.xmlsoap.org/soap/envelope/",
    prefix = "SOAP-ENV",
  )
  val body: Body,
) : SoapEnvelope {
  override fun isFault(): Boolean = false

  @Serializable
  data class Body(
    @XmlElement(true)
    val verifyCertificate: VerifyCertificate? = null,
  )
}

@Serializable
@XmlSerialName(
  "Envelope",
  namespace = "http://schemas.xmlsoap.org/soap/envelope/",
  prefix = "SOAP-ENV",
)
data class VerifyCertificateResponseEnvelope(
  @XmlElement(true)
  @XmlSerialName(
    "Body",
    namespace = "http://schemas.xmlsoap.org/soap/envelope/",
    prefix = "SOAP-ENV",
  )
  val body: Body,
) : SoapEnvelope {
  override fun isFault(): Boolean = body.fault != null

  @Serializable
  data class Body(
    @XmlElement(true)
    val verifyCertificateResponse: VerifyCertificateResponse? = null,
    @XmlElement(true)
    @XmlSerialName(
      "Fault",
      namespace = "http://schemas.xmlsoap.org/soap/envelope/",
      prefix = "SOAP-ENV",
    )
    val fault: Fault? = null,
  )

  @Serializable
  data class Fault(
    @XmlElement(true)
    val faultcode: String = "",
    @XmlElement(true)
    val faultstring: String = "",
    @XmlElement(true)
    val faultactor: String? = null,
    @XmlElement(true)
    val detail: Error? = null,
  )
}
