// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.gematik.conn.signatureservice74

import kotlin.String
import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName

@Serializable
@XmlSerialName(
  "DisplayableAttribute",
  namespace = "http://ws.gematik.de/conn/SignatureService/v7.4",
)
data class DisplayableAttributesDisplayableAttribute(
  @XmlElement(true)
  @XmlSerialName("Key")
  val key: String,
  @XmlElement(true)
  @XmlSerialName("Value")
  val `value`: String,
)
