// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.gematik.conn.signatureservice74

import kotlin.collections.List
import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName

@Serializable
@XmlSerialName(
  "DisplayableAttributes",
  namespace = "http://ws.gematik.de/conn/SignatureService/v7.4",
)
data class DisplayableAttributes(
  @XmlElement(true)
  @XmlSerialName("DisplayableAttribute")
  val displayableAttribute: List<DisplayableAttributesDisplayableAttribute> = emptyList(),
)
