// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.gematik.conn.signatureservice74

import de.gematik.connector.api.oasis.dss10core.Base64Data
import kotlin.String
import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName

@Serializable
@XmlSerialName(
  "Document",
  namespace = "http://ws.gematik.de/conn/SignatureService/v7.4",
)
data class Document(
  @XmlElement(false)
  @XmlSerialName("ID")
  val id: String? = null,
  @XmlElement(false)
  @XmlSerialName("RefURI")
  val refUri: String? = null,
  @XmlElement(false)
  @XmlSerialName("RefType")
  val refType: String? = null,
  @XmlElement(false)
  @XmlSerialName("SchemaRefs")
  val schemaRefs: String? = null,
  @XmlElement(false)
  @XmlSerialName("ShortText")
  val shortText: String? = null,
  @XmlElement(true)
  @XmlSerialName(
    "Base64XML",
    namespace = "http://ws.gematik.de/conn/ConnectorCommon/v5.0",
  )
  val base64Xml: String? = null,
  @XmlElement(true)
  @XmlSerialName(
    "Base64Data",
    namespace = "urn:oasis:names:tc:dss:1.0:core:schema",
  )
  val base64Data: Base64Data? = null,
)
