// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.gematik.conn.signatureservice74

import de.gematik.connector.api.gematik.conn.connectorcommon50.Status
import de.gematik.connector.api.oasis.dss10core.SignatureObject
import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName

@Serializable
@XmlSerialName(
  "ExternalAuthenticateResponse",
  namespace = "http://ws.gematik.de/conn/SignatureService/v7.4",
)
data class ExternalAuthenticateResponse(
  @XmlElement(true)
  @XmlSerialName(
    "Status",
    namespace = "http://ws.gematik.de/conn/ConnectorCommon/v5.0",
  )
  val status: Status,
  @XmlElement(true)
  @XmlSerialName(
    "SignatureObject",
    namespace = "urn:oasis:names:tc:dss:1.0:core:schema",
  )
  val signatureObject: SignatureObject? = null,
)
