// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.gematik.conn.signatureservice74

import de.gematik.connector.api.gematik.conn.connectorcontext20.Context
import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName

@Serializable
@XmlSerialName(
  "GetJobNumber",
  namespace = "http://ws.gematik.de/conn/SignatureService/v7.4",
)
data class GetJobNumber(
  @XmlElement(true)
  @XmlSerialName(
    "Context",
    namespace = "http://ws.gematik.de/conn/ConnectorContext/v2.0",
  )
  val context: Context,
)
