// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.gematik.conn.signatureservice74

import de.gematik.connector.api.soap.SoapOperation

object Operations {
  val VerifyDocument: SoapOperation =
      SoapOperation("VerifyDocument", "http://ws.gematik.de/conn/SignatureService/v7.4#VerifyDocument", "soap11")

  val SignDocument: SoapOperation =
      SoapOperation("SignDocument", "http://ws.gematik.de/conn/SignatureService/v7.4#SignDocument", "soap11")

  val GetJobNumber: SoapOperation =
      SoapOperation("GetJobNumber", "http://ws.gematik.de/conn/SignatureService/v7.4#GetJobNumber", "soap11")

  val StopSignature: SoapOperation =
      SoapOperation("StopSignature", "http://ws.gematik.de/conn/SignatureService/v7.4#StopSignature", "soap11")
}
