// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.gematik.conn.signatureservice74

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
enum class SignatureForm {
  @SerialName("urn:oasis:names:tc:dss:1.0:profiles:AdES:forms:BES")
  UrnOasisNamesTcDss10ProfilesAdESFormsBES,
  @SerialName("urn:oasis:names:tc:dss:1.0:profiles:AdES:forms:ES-T")
  UrnOasisNamesTcDss10ProfilesAdESFormsEST,
  @SerialName("urn:oasis:names:tc:dss:1.0:profiles:AdES:forms:ES-C")
  UrnOasisNamesTcDss10ProfilesAdESFormsESC,
  @SerialName("urn:oasis:names:tc:dss:1.0:profiles:AdES:forms:ES-X")
  UrnOasisNamesTcDss10ProfilesAdESFormsESX,
  @SerialName("urn:oasis:names:tc:dss:1.0:profiles:AdES:forms:ES-X-L")
  UrnOasisNamesTcDss10ProfilesAdESFormsESXL,
}
