// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.gematik.conn.signatureservice74

import de.gematik.connector.api.gematik.conn.connectorcontext20.Context
import kotlin.String
import kotlin.collections.List
import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName

@Serializable
@XmlSerialName(
  "SignDocument",
  namespace = "http://ws.gematik.de/conn/SignatureService/v7.4",
)
data class SignDocument(
  @XmlElement(true)
  @XmlSerialName(
    "CardHandle",
    namespace = "http://ws.gematik.de/conn/ConnectorCommon/v5.0",
  )
  val cardHandle: String,
  @XmlElement(true)
  @XmlSerialName(
    "Context",
    namespace = "http://ws.gematik.de/conn/ConnectorContext/v2.0",
  )
  val context: Context,
  @XmlElement(true)
  @XmlSerialName("TvMode")
  val tvMode: TvMode,
  @XmlElement(true)
  @XmlSerialName("JobNumber")
  val jobNumber: String? = null,
  @XmlElement(true)
  @XmlSerialName("SignRequest")
  val signRequest: List<SignRequest> = emptyList(),
  @XmlElement(true)
  @XmlSerialName("Crypt")
  val crypt: String? = null,
)
