// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.gematik.conn.signatureservice74

import de.gematik.connector.api.oasis.dss10core.AdditionalKeyInfo
import de.gematik.connector.api.oasis.dss10core.Schemas
import de.gematik.connector.api.oasis.dssx10profiles.verificationreport.ReturnVerificationReport
import kotlin.String
import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName

@Serializable
@XmlSerialName(
  "OptionalInputs",
  namespace = "http://ws.gematik.de/conn/SignatureService/v7.4",
)
data class VerifyDocumentOptionalInputs(
  @XmlElement(true)
  @XmlSerialName("VerifyManifests")
  val verifyManifests: String? = null,
  @XmlElement(true)
  @XmlSerialName("UseVerificationTime")
  val useVerificationTime: UseVerificationTime? = null,
  @XmlElement(true)
  @XmlSerialName(
    "AdditionalKeyInfo",
    namespace = "urn:oasis:names:tc:dss:1.0:core:schema",
  )
  val additionalKeyInfo: AdditionalKeyInfo? = null,
  @XmlElement(true)
  @XmlSerialName(
    "ReturnVerificationReport",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val returnVerificationReport: ReturnVerificationReport? = null,
  @XmlElement(true)
  @XmlSerialName(
    "Schemas",
    namespace = "urn:oasis:names:tc:dss:1.0:core:schema",
  )
  val schemas: Schemas? = null,
  @XmlElement(true)
  @XmlSerialName("ViewerInfo")
  val viewerInfo: ViewerInfo? = null,
)
