// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.gematik.conn.signatureservice74

import de.gematik.connector.api.oasis.dss10core.UpdatedSignature
import de.gematik.connector.api.oasis.dss10core.VerifyManifestResults
import de.gematik.connector.api.oasis.dssx10profiles.verificationreport.VerificationReport
import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName

@Serializable
@XmlSerialName(
  "OptionalOutputs",
  namespace = "http://ws.gematik.de/conn/SignatureService/v7.4",
)
data class VerifyDocumentResponseOptionalOutputs(
  @XmlElement(true)
  @XmlSerialName(
    "VerifyManifestResults",
    namespace = "urn:oasis:names:tc:dss:1.0:core:schema",
  )
  val verifyManifestResults: VerifyManifestResults? = null,
  @XmlElement(true)
  @XmlSerialName("DocumentWithSignature")
  val documentWithSignature: DocumentWithSignature? = null,
  @XmlElement(true)
  @XmlSerialName(
    "UpdatedSignature",
    namespace = "urn:oasis:names:tc:dss:1.0:core:schema",
  )
  val updatedSignature: UpdatedSignature? = null,
  @XmlElement(true)
  @XmlSerialName(
    "VerificationReport",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val verificationReport: VerificationReport? = null,
)
