// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.gematik.conn.signatureservice74

import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName

@Serializable
@XmlSerialName(
  "ViewerInfo",
  namespace = "http://ws.gematik.de/conn/SignatureService/v7.4",
)
data class ViewerInfo(
  @XmlElement(true)
  @XmlSerialName("XslStyleSheets")
  val xslStyleSheets: ViewerInfoXslStyleSheets? = null,
)
