// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.gematik.conn.signatureservice74

import de.gematik.connector.api.gematik.conn.connectorcommon50.XslStylesheet
import kotlin.collections.List
import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName

@Serializable
@XmlSerialName(
  "XslStyleSheets",
  namespace = "http://ws.gematik.de/conn/SignatureService/v7.4",
)
data class ViewerInfoXslStyleSheets(
  @XmlElement(true)
  @XmlSerialName(
    "XslStylesheet",
    namespace = "http://ws.gematik.de/conn/ConnectorCommon/v5.0",
  )
  val xslStylesheet: List<XslStylesheet> = emptyList(),
)
