// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.gematik.conn.eventservice72

interface EventServicePort {
  fun subscribe(request: Subscribe): SubscribeResponse

  fun unsubscribe(request: Unsubscribe): UnsubscribeResponse

  fun getSubscription(request: GetSubscription): GetSubscriptionResponse

  fun getResourceInformation(request: GetResourceInformation): GetResourceInformationResponse

  fun getCardTerminals(request: GetCardTerminals): GetCardTerminalsResponse

  fun getCards(request: GetCards): GetCardsResponse

  fun renewSubscriptions(request: RenewSubscriptions): RenewSubscriptionsResponse
}
