// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.gematik.conn.eventservice72

import kotlin.String
import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName

@Serializable
@XmlSerialName(
  "Parameter",
  namespace = "http://ws.gematik.de/conn/EventService/v7.2",
)
data class EventMessageParameter(
  @XmlElement(true)
  @XmlSerialName("Key")
  val key: String,
  @XmlElement(true)
  @XmlSerialName("Value")
  val `value`: String,
)
