// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.gematik.conn.eventservice72

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
enum class EventSeverityType {
  @SerialName("Info")
  Info,
  @SerialName("Warning")
  Warning,
  @SerialName("Error")
  Error,
  @SerialName("Fatal")
  Fatal,
}
