// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.gematik.conn.eventservice72

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
enum class EventType {
  @SerialName("Operation")
  Operation,
  @SerialName("Security")
  Security,
  @SerialName("Infrastructure")
  Infrastructure,
  @SerialName("Business")
  Business,
  @SerialName("Other")
  Other,
}
