// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.gematik.conn.eventservice72

import de.gematik.connector.api.gematik.conn.cardservice81.Cards
import de.gematik.connector.api.gematik.conn.connectorcommon50.Status
import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName

@Serializable
@XmlSerialName(
  "GetCardsResponse",
  namespace = "http://ws.gematik.de/conn/EventService/v7.2",
)
data class GetCardsResponse(
  @XmlElement(true)
  @XmlSerialName(
    "Status",
    namespace = "http://ws.gematik.de/conn/ConnectorCommon/v5.0",
  )
  val status: Status,
  @XmlElement(true)
  @XmlSerialName(
    "Cards",
    namespace = "http://ws.gematik.de/conn/CardService/v8.1",
  )
  val cards: Cards,
)
