// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.gematik.conn.eventservice72

import de.gematik.connector.api.gematik.conn.cardterminalinfo80.CardTerminals
import de.gematik.connector.api.gematik.conn.connectorcommon50.Status
import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName

@Serializable
@XmlSerialName(
  "GetCardTerminalsResponse",
  namespace = "http://ws.gematik.de/conn/EventService/v7.2",
)
data class GetCardTerminalsResponse(
  @XmlElement(true)
  @XmlSerialName(
    "Status",
    namespace = "http://ws.gematik.de/conn/ConnectorCommon/v5.0",
  )
  val status: Status,
  @XmlElement(true)
  @XmlSerialName(
    "CardTerminals",
    namespace = "http://ws.gematik.de/conn/CardTerminalInfo/v8.0",
  )
  val cardTerminals: CardTerminals,
)
