// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.gematik.conn.eventservice72

import de.gematik.connector.api.gematik.conn.cardservicecommon20.CardType
import de.gematik.connector.api.gematik.conn.connectorcontext20.Context
import kotlin.Boolean
import kotlin.Int
import kotlin.String
import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName

@Serializable
@XmlSerialName(
  "GetCards",
  namespace = "http://ws.gematik.de/conn/EventService/v7.2",
)
data class GetCards(
  @XmlElement(false)
  @XmlSerialName("mandant-wide")
  val mandantWide: Boolean? = null,
  @XmlElement(true)
  @XmlSerialName(
    "Context",
    namespace = "http://ws.gematik.de/conn/ConnectorContext/v2.0",
  )
  val context: Context,
  @XmlElement(true)
  @XmlSerialName(
    "CtId",
    namespace = "http://ws.gematik.de/conn/CardServiceCommon/v2.0",
  )
  val ctId: String? = null,
  @XmlElement(true)
  @XmlSerialName(
    "SlotId",
    namespace = "http://ws.gematik.de/conn/CardServiceCommon/v2.0",
  )
  val slotId: Int? = null,
  @XmlElement(true)
  @XmlSerialName(
    "CardType",
    namespace = "http://ws.gematik.de/conn/CardServiceCommon/v2.0",
  )
  val cardType: CardType? = null,
)
