// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.gematik.conn.eventservice72

import kotlin.collections.List
import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName

@Serializable
@XmlSerialName(
  "Subscriptions",
  namespace = "http://ws.gematik.de/conn/EventService/v7.2",
)
data class GetSubscriptionResponseSubscriptions(
  @XmlElement(true)
  @XmlSerialName("Subscription")
  val subscription: List<Subscription> = emptyList(),
)
