// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.gematik.conn.eventservice72

import kotlin.String
import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName

@Serializable
@XmlSerialName(
  "Subscription",
  namespace = "http://ws.gematik.de/conn/EventService/v7.2",
)
data class Subscription(
  @XmlElement(true)
  @XmlSerialName("SubscriptionID")
  val subscriptionId: String? = null,
  @XmlElement(true)
  @XmlSerialName("TerminationTime")
  val terminationTime: String? = null,
  @XmlElement(true)
  @XmlSerialName("EventTo")
  val eventTo: String,
  @XmlElement(true)
  @XmlSerialName("Topic")
  val topic: String,
  @XmlElement(true)
  @XmlSerialName("Filter")
  val filter: String? = null,
)
