// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.gematik.conn.eventservice72

import kotlin.String
import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName

@Serializable
data class SubscriptionType(
  @XmlElement(true)
  @XmlSerialName(
    "SubscriptionID",
    namespace = "http://ws.gematik.de/conn/EventService/v7.2",
  )
  val subscriptionId: String? = null,
  @XmlElement(true)
  @XmlSerialName(
    "TerminationTime",
    namespace = "http://ws.gematik.de/conn/EventService/v7.2",
  )
  val terminationTime: String? = null,
  @XmlElement(true)
  @XmlSerialName(
    "EventTo",
    namespace = "http://ws.gematik.de/conn/EventService/v7.2",
  )
  val eventTo: String,
  @XmlElement(true)
  @XmlSerialName(
    "Topic",
    namespace = "http://ws.gematik.de/conn/EventService/v7.2",
  )
  val topic: String,
  @XmlElement(true)
  @XmlSerialName(
    "Filter",
    namespace = "http://ws.gematik.de/conn/EventService/v7.2",
  )
  val filter: String? = null,
)
