// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.gematik.conn.eventservice72

import de.gematik.connector.api.gematik.conn.connectorcontext20.Context
import kotlin.String
import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName

@Serializable
@XmlSerialName(
  "Unsubscribe",
  namespace = "http://ws.gematik.de/conn/EventService/v7.2",
)
data class Unsubscribe(
  @XmlElement(true)
  @XmlSerialName(
    "Context",
    namespace = "http://ws.gematik.de/conn/ConnectorContext/v2.0",
  )
  val context: Context,
  @XmlElement(true)
  @XmlSerialName("SubscriptionID")
  val subscriptionId: String? = null,
  @XmlElement(true)
  @XmlSerialName("EventTo")
  val eventTo: String? = null,
)
