// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.w3200104.xmlenc

import de.gematik.connector.api.w3200009.xmldsig.KeyInfoType
import kotlin.String
import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName

@Serializable
@XmlSerialName(
  "AgreementMethod",
  namespace = "http://www.w3.org/2001/04/xmlenc#",
)
data class AgreementMethod(
  @XmlElement(false)
  @XmlSerialName("Algorithm")
  val algorithm: String,
  @XmlElement(true)
  @XmlSerialName("KA-Nonce")
  val kaNonce: String? = null,
  @XmlElement(true)
  val unknownContent: String? = null,
  @XmlElement(true)
  @XmlSerialName("OriginatorKeyInfo")
  val originatorKeyInfo: KeyInfoType? = null,
  @XmlElement(true)
  @XmlSerialName("RecipientKeyInfo")
  val recipientKeyInfo: KeyInfoType? = null,
)
