// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.w3200104.xmlenc

import kotlin.String
import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName

@Serializable
data class CipherReferenceType(
  @XmlElement(false)
  @XmlSerialName("URI")
  val uri: String,
  @XmlElement(true)
  @XmlSerialName(
    "Transforms",
    namespace = "http://www.w3.org/2001/04/xmlenc#",
  )
  val transforms: TransformsType? = null,
)
