// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.w3200104.xmlenc

import kotlin.String
import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName

@Serializable
@XmlSerialName(
  "CipherData",
  namespace = "http://www.w3.org/2001/04/xmlenc#",
)
data class CipherData(
  @XmlElement(true)
  @XmlSerialName("CipherValue")
  val cipherValue: String? = null,
  @XmlElement(true)
  @XmlSerialName("CipherReference")
  val cipherReference: CipherReference? = null,
)
