// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.w3200104.xmlenc

import kotlin.String
import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName

@Serializable
data class CipherDataType(
  @XmlElement(true)
  @XmlSerialName(
    "CipherValue",
    namespace = "http://www.w3.org/2001/04/xmlenc#",
  )
  val cipherValue: String? = null,
  @XmlElement(true)
  @XmlSerialName(
    "CipherReference",
    namespace = "http://www.w3.org/2001/04/xmlenc#",
  )
  val cipherReference: CipherReference? = null,
)
