// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.w3200104.xmlenc

import kotlin.String
import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName

@Serializable
@XmlSerialName(
  "DHKeyValue",
  namespace = "http://www.w3.org/2001/04/xmlenc#",
)
data class DHKeyValue(
  @XmlElement(true)
  @XmlSerialName("P")
  val p: String,
  @XmlElement(true)
  @XmlSerialName("Q")
  val q: String,
  @XmlElement(true)
  @XmlSerialName("Generator")
  val generator: String,
  @XmlElement(true)
  @XmlSerialName("Public")
  val `public`: String,
  @XmlElement(true)
  @XmlSerialName("seed")
  val seed: String,
  @XmlElement(true)
  @XmlSerialName("pgenCounter")
  val pgenCounter: String,
)
