// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.w3200104.xmlenc

import kotlin.String
import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName

@Serializable
data class EncryptionPropertyType(
  @XmlElement(false)
  @XmlSerialName("Target")
  val target: String? = null,
  @XmlElement(false)
  @XmlSerialName("Id")
  val id: String? = null,
  @XmlElement(false)
  @XmlSerialName("anyAttribute")
  val unknownAttributes: String? = null,
  @XmlElement(true)
  val unknownContent: String? = null,
)
