// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.w3200104.xmlenc

import de.gematik.connector.api.w3200009.xmldsig.KeyInfo
import kotlin.String
import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName

@Serializable
data class EncryptedDataType(
  @XmlElement(false)
  @XmlSerialName("Id")
  val id: String? = null,
  @XmlElement(false)
  @XmlSerialName("Type")
  val type: String? = null,
  @XmlElement(false)
  @XmlSerialName("MimeType")
  val mimeType: String? = null,
  @XmlElement(false)
  @XmlSerialName("Encoding")
  val encoding: String? = null,
  @XmlElement(true)
  @XmlSerialName(
    "EncryptionMethod",
    namespace = "http://www.w3.org/2001/04/xmlenc#",
  )
  val encryptionMethod: EncryptionMethodType? = null,
  @XmlElement(true)
  @XmlSerialName(
    "KeyInfo",
    namespace = "http://www.w3.org/2000/09/xmldsig#",
  )
  val keyInfo: KeyInfo? = null,
  @XmlElement(true)
  @XmlSerialName(
    "CipherData",
    namespace = "http://www.w3.org/2001/04/xmlenc#",
  )
  val cipherData: CipherData,
  @XmlElement(true)
  @XmlSerialName(
    "EncryptionProperties",
    namespace = "http://www.w3.org/2001/04/xmlenc#",
  )
  val encryptionProperties: EncryptionProperties? = null,
)
