// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.w3200104.xmlenc

import kotlin.Int
import kotlin.String
import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName

@Serializable
data class EncryptionMethodType(
  @XmlElement(false)
  @XmlSerialName("Algorithm")
  val algorithm: String,
  @XmlElement(true)
  @XmlSerialName(
    "KeySize",
    namespace = "http://www.w3.org/2001/04/xmlenc#",
  )
  val keySize: Int? = null,
  @XmlElement(true)
  @XmlSerialName(
    "OAEPparams",
    namespace = "http://www.w3.org/2001/04/xmlenc#",
  )
  val oaePparams: String? = null,
  @XmlElement(true)
  val unknownContent: String? = null,
)
