// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.w3200104.xmlenc

import kotlin.collections.List
import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName

@Serializable
@XmlSerialName(
  "ReferenceList",
  namespace = "http://www.w3.org/2001/04/xmlenc#",
)
data class ReferenceList(
  @XmlElement(true)
  @XmlSerialName("DataReference")
  val dataReference: List<ReferenceType> = emptyList(),
  @XmlElement(true)
  @XmlSerialName("KeyReference")
  val keyReference: List<ReferenceType> = emptyList(),
)
