// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.w3200104.xmlenc

import de.gematik.connector.api.w3200009.xmldsig.KeyInfo
import de.gematik.connector.api.w3200009.xmldsig.KeyInfoType
import de.gematik.connector.api.w3200009.xmldsig.Transform
import kotlin.Int
import kotlin.String
import kotlin.collections.List
import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName

@Serializable
@XmlSerialName(
  "CipherData",
  namespace = "http://www.w3.org/2001/04/xmlenc#",
)
data class CipherData(
  @XmlElement(true)
  @XmlSerialName("CipherValue")
  val cipherValue: String? = null,
  @XmlElement(true)
  @XmlSerialName("CipherReference")
  val cipherReference: CipherReference? = null,
)

@Serializable
@XmlSerialName(
  "CipherReference",
  namespace = "http://www.w3.org/2001/04/xmlenc#",
)
data class CipherReference(
  @XmlElement(false)
  @XmlSerialName("URI")
  val uri: String,
  @XmlElement(true)
  @XmlSerialName("Transforms")
  val transforms: TransformsType? = null,
)

@Serializable
@XmlSerialName(
  "EncryptedData",
  namespace = "http://www.w3.org/2001/04/xmlenc#",
)
data class EncryptedData(
  @XmlElement(false)
  @XmlSerialName("Id")
  val id: String? = null,
  @XmlElement(false)
  @XmlSerialName("Type")
  val type: String? = null,
  @XmlElement(false)
  @XmlSerialName("MimeType")
  val mimeType: String? = null,
  @XmlElement(false)
  @XmlSerialName("Encoding")
  val encoding: String? = null,
  @XmlElement(true)
  @XmlSerialName("EncryptionMethod")
  val encryptionMethod: EncryptionMethodType? = null,
  @XmlElement(true)
  @XmlSerialName(
    "KeyInfo",
    namespace = "http://www.w3.org/2000/09/xmldsig#",
  )
  val keyInfo: KeyInfo? = null,
  @XmlElement(true)
  @XmlSerialName("CipherData")
  val cipherData: CipherData,
  @XmlElement(true)
  @XmlSerialName("EncryptionProperties")
  val encryptionProperties: EncryptionProperties? = null,
)

@Serializable
@XmlSerialName(
  "EncryptedKey",
  namespace = "http://www.w3.org/2001/04/xmlenc#",
)
data class EncryptedKey(
  @XmlElement(false)
  @XmlSerialName("Id")
  val id: String? = null,
  @XmlElement(false)
  @XmlSerialName("Type")
  val type: String? = null,
  @XmlElement(false)
  @XmlSerialName("MimeType")
  val mimeType: String? = null,
  @XmlElement(false)
  @XmlSerialName("Encoding")
  val encoding: String? = null,
  @XmlElement(false)
  @XmlSerialName("Recipient")
  val recipient: String? = null,
  @XmlElement(true)
  @XmlSerialName("EncryptionMethod")
  val encryptionMethod: EncryptionMethodType? = null,
  @XmlElement(true)
  @XmlSerialName(
    "KeyInfo",
    namespace = "http://www.w3.org/2000/09/xmldsig#",
  )
  val keyInfo: KeyInfo? = null,
  @XmlElement(true)
  @XmlSerialName("CipherData")
  val cipherData: CipherData,
  @XmlElement(true)
  @XmlSerialName("EncryptionProperties")
  val encryptionProperties: EncryptionProperties? = null,
  @XmlElement(true)
  @XmlSerialName("ReferenceList")
  val referenceList: ReferenceList? = null,
  @XmlElement(true)
  @XmlSerialName("CarriedKeyName")
  val carriedKeyName: String? = null,
)

@Serializable
@XmlSerialName(
  "AgreementMethod",
  namespace = "http://www.w3.org/2001/04/xmlenc#",
)
data class AgreementMethod(
  @XmlElement(false)
  @XmlSerialName("Algorithm")
  val algorithm: String,
  @XmlElement(true)
  @XmlSerialName("KA-Nonce")
  val kaNonce: String? = null,
  @XmlElement(true)
  val unknownContent: String? = null,
  @XmlElement(true)
  @XmlSerialName("OriginatorKeyInfo")
  val originatorKeyInfo: KeyInfoType? = null,
  @XmlElement(true)
  @XmlSerialName("RecipientKeyInfo")
  val recipientKeyInfo: KeyInfoType? = null,
)

@Serializable
@XmlSerialName(
  "ReferenceList",
  namespace = "http://www.w3.org/2001/04/xmlenc#",
)
data class ReferenceList(
  @XmlElement(true)
  @XmlSerialName("DataReference")
  val dataReference: List<ReferenceType> = emptyList(),
  @XmlElement(true)
  @XmlSerialName("KeyReference")
  val keyReference: List<ReferenceType> = emptyList(),
)

@Serializable
@XmlSerialName(
  "EncryptionProperties",
  namespace = "http://www.w3.org/2001/04/xmlenc#",
)
data class EncryptionProperties(
  @XmlElement(false)
  @XmlSerialName("Id")
  val id: String? = null,
  @XmlElement(true)
  @XmlSerialName("EncryptionProperty")
  val encryptionProperty: List<EncryptionProperty> = emptyList(),
)

@Serializable
@XmlSerialName(
  "EncryptionProperty",
  namespace = "http://www.w3.org/2001/04/xmlenc#",
)
data class EncryptionProperty(
  @XmlElement(false)
  @XmlSerialName("Target")
  val target: String? = null,
  @XmlElement(false)
  @XmlSerialName("Id")
  val id: String? = null,
  @XmlElement(false)
  @XmlSerialName("anyAttribute")
  val unknownAttributes: String? = null,
  @XmlElement(true)
  val unknownContent: String? = null,
)

@Serializable
@XmlSerialName(
  "DHKeyValue",
  namespace = "http://www.w3.org/2001/04/xmlenc#",
)
data class DHKeyValue(
  @XmlElement(true)
  @XmlSerialName("P")
  val p: String,
  @XmlElement(true)
  @XmlSerialName("Q")
  val q: String,
  @XmlElement(true)
  @XmlSerialName("Generator")
  val generator: String,
  @XmlElement(true)
  @XmlSerialName("Public")
  val `public`: String,
  @XmlElement(true)
  @XmlSerialName("seed")
  val seed: String,
  @XmlElement(true)
  @XmlSerialName("pgenCounter")
  val pgenCounter: String,
)

@Serializable
data class EncryptedType(
  @XmlElement(false)
  @XmlSerialName("Id")
  val id: String? = null,
  @XmlElement(false)
  @XmlSerialName("Type")
  val type: String? = null,
  @XmlElement(false)
  @XmlSerialName("MimeType")
  val mimeType: String? = null,
  @XmlElement(false)
  @XmlSerialName("Encoding")
  val encoding: String? = null,
  @XmlElement(true)
  @XmlSerialName(
    "EncryptionMethod",
    namespace = "http://www.w3.org/2001/04/xmlenc#",
  )
  val encryptionMethod: EncryptionMethodType? = null,
  @XmlElement(true)
  @XmlSerialName(
    "KeyInfo",
    namespace = "http://www.w3.org/2000/09/xmldsig#",
  )
  val keyInfo: KeyInfo? = null,
  @XmlElement(true)
  @XmlSerialName(
    "CipherData",
    namespace = "http://www.w3.org/2001/04/xmlenc#",
  )
  val cipherData: CipherData,
  @XmlElement(true)
  @XmlSerialName(
    "EncryptionProperties",
    namespace = "http://www.w3.org/2001/04/xmlenc#",
  )
  val encryptionProperties: EncryptionProperties? = null,
)

@Serializable
data class EncryptionMethodType(
  @XmlElement(false)
  @XmlSerialName("Algorithm")
  val algorithm: String,
  @XmlElement(true)
  @XmlSerialName(
    "KeySize",
    namespace = "http://www.w3.org/2001/04/xmlenc#",
  )
  val keySize: Int? = null,
  @XmlElement(true)
  @XmlSerialName(
    "OAEPparams",
    namespace = "http://www.w3.org/2001/04/xmlenc#",
  )
  val oaePparams: String? = null,
  @XmlElement(true)
  val unknownContent: String? = null,
)

@Serializable
data class CipherDataType(
  @XmlElement(true)
  @XmlSerialName(
    "CipherValue",
    namespace = "http://www.w3.org/2001/04/xmlenc#",
  )
  val cipherValue: String? = null,
  @XmlElement(true)
  @XmlSerialName(
    "CipherReference",
    namespace = "http://www.w3.org/2001/04/xmlenc#",
  )
  val cipherReference: CipherReference? = null,
)

@Serializable
data class CipherReferenceType(
  @XmlElement(false)
  @XmlSerialName("URI")
  val uri: String,
  @XmlElement(true)
  @XmlSerialName(
    "Transforms",
    namespace = "http://www.w3.org/2001/04/xmlenc#",
  )
  val transforms: TransformsType? = null,
)

@Serializable
data class TransformsType(
  @XmlElement(true)
  @XmlSerialName(
    "Transform",
    namespace = "http://www.w3.org/2000/09/xmldsig#",
  )
  val transform: List<Transform> = emptyList(),
)

@Serializable
data class EncryptedDataType(
  @XmlElement(false)
  @XmlSerialName("Id")
  val id: String? = null,
  @XmlElement(false)
  @XmlSerialName("Type")
  val type: String? = null,
  @XmlElement(false)
  @XmlSerialName("MimeType")
  val mimeType: String? = null,
  @XmlElement(false)
  @XmlSerialName("Encoding")
  val encoding: String? = null,
  @XmlElement(true)
  @XmlSerialName(
    "EncryptionMethod",
    namespace = "http://www.w3.org/2001/04/xmlenc#",
  )
  val encryptionMethod: EncryptionMethodType? = null,
  @XmlElement(true)
  @XmlSerialName(
    "KeyInfo",
    namespace = "http://www.w3.org/2000/09/xmldsig#",
  )
  val keyInfo: KeyInfo? = null,
  @XmlElement(true)
  @XmlSerialName(
    "CipherData",
    namespace = "http://www.w3.org/2001/04/xmlenc#",
  )
  val cipherData: CipherData,
  @XmlElement(true)
  @XmlSerialName(
    "EncryptionProperties",
    namespace = "http://www.w3.org/2001/04/xmlenc#",
  )
  val encryptionProperties: EncryptionProperties? = null,
)

@Serializable
data class EncryptedKeyType(
  @XmlElement(false)
  @XmlSerialName("Id")
  val id: String? = null,
  @XmlElement(false)
  @XmlSerialName("Type")
  val type: String? = null,
  @XmlElement(false)
  @XmlSerialName("MimeType")
  val mimeType: String? = null,
  @XmlElement(false)
  @XmlSerialName("Encoding")
  val encoding: String? = null,
  @XmlElement(false)
  @XmlSerialName("Recipient")
  val recipient: String? = null,
  @XmlElement(true)
  @XmlSerialName(
    "EncryptionMethod",
    namespace = "http://www.w3.org/2001/04/xmlenc#",
  )
  val encryptionMethod: EncryptionMethodType? = null,
  @XmlElement(true)
  @XmlSerialName(
    "KeyInfo",
    namespace = "http://www.w3.org/2000/09/xmldsig#",
  )
  val keyInfo: KeyInfo? = null,
  @XmlElement(true)
  @XmlSerialName(
    "CipherData",
    namespace = "http://www.w3.org/2001/04/xmlenc#",
  )
  val cipherData: CipherData,
  @XmlElement(true)
  @XmlSerialName(
    "EncryptionProperties",
    namespace = "http://www.w3.org/2001/04/xmlenc#",
  )
  val encryptionProperties: EncryptionProperties? = null,
  @XmlElement(true)
  @XmlSerialName(
    "ReferenceList",
    namespace = "http://www.w3.org/2001/04/xmlenc#",
  )
  val referenceList: ReferenceList? = null,
  @XmlElement(true)
  @XmlSerialName(
    "CarriedKeyName",
    namespace = "http://www.w3.org/2001/04/xmlenc#",
  )
  val carriedKeyName: String? = null,
)

@Serializable
data class AgreementMethodType(
  @XmlElement(false)
  @XmlSerialName("Algorithm")
  val algorithm: String,
  @XmlElement(true)
  @XmlSerialName(
    "KA-Nonce",
    namespace = "http://www.w3.org/2001/04/xmlenc#",
  )
  val kaNonce: String? = null,
  @XmlElement(true)
  val unknownContent: String? = null,
  @XmlElement(true)
  @XmlSerialName(
    "OriginatorKeyInfo",
    namespace = "http://www.w3.org/2001/04/xmlenc#",
  )
  val originatorKeyInfo: KeyInfoType? = null,
  @XmlElement(true)
  @XmlSerialName(
    "RecipientKeyInfo",
    namespace = "http://www.w3.org/2001/04/xmlenc#",
  )
  val recipientKeyInfo: KeyInfoType? = null,
)

@Serializable
data class ReferenceType(
  @XmlElement(false)
  @XmlSerialName("URI")
  val uri: String,
  @XmlElement(true)
  val unknownContent: String? = null,
)

@Serializable
data class EncryptionPropertiesType(
  @XmlElement(false)
  @XmlSerialName("Id")
  val id: String? = null,
  @XmlElement(true)
  @XmlSerialName(
    "EncryptionProperty",
    namespace = "http://www.w3.org/2001/04/xmlenc#",
  )
  val encryptionProperty: List<EncryptionProperty> = emptyList(),
)

@Serializable
data class EncryptionPropertyType(
  @XmlElement(false)
  @XmlSerialName("Target")
  val target: String? = null,
  @XmlElement(false)
  @XmlSerialName("Id")
  val id: String? = null,
  @XmlElement(false)
  @XmlSerialName("anyAttribute")
  val unknownAttributes: String? = null,
  @XmlElement(true)
  val unknownContent: String? = null,
)

@Serializable
data class DHKeyValueType(
  @XmlElement(true)
  @XmlSerialName(
    "P",
    namespace = "http://www.w3.org/2001/04/xmlenc#",
  )
  val p: String,
  @XmlElement(true)
  @XmlSerialName(
    "Q",
    namespace = "http://www.w3.org/2001/04/xmlenc#",
  )
  val q: String,
  @XmlElement(true)
  @XmlSerialName(
    "Generator",
    namespace = "http://www.w3.org/2001/04/xmlenc#",
  )
  val generator: String,
  @XmlElement(true)
  @XmlSerialName(
    "Public",
    namespace = "http://www.w3.org/2001/04/xmlenc#",
  )
  val `public`: String,
  @XmlElement(true)
  @XmlSerialName(
    "seed",
    namespace = "http://www.w3.org/2001/04/xmlenc#",
  )
  val seed: String,
  @XmlElement(true)
  @XmlSerialName(
    "pgenCounter",
    namespace = "http://www.w3.org/2001/04/xmlenc#",
  )
  val pgenCounter: String,
)
