// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.gematik.conn.cardterminalinfo80

import de.gematik.connector.api.gematik.conn.connectorcommon50.WorkplaceIds
import de.gematik.connector.api.gematik.int.version.productinformation11.ProductInformation
import kotlin.Boolean
import kotlin.Int
import kotlin.String
import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName

@Serializable
data class CardTerminalInfoType(
  @XmlElement(true)
  @XmlSerialName(
    "ProductInformation",
    namespace = "http://ws.gematik.de/int/version/ProductInformation/v1.1",
  )
  val productInformation: ProductInformation,
  @XmlElement(true)
  @XmlSerialName(
    "CtId",
    namespace = "http://ws.gematik.de/conn/CardServiceCommon/v2.0",
  )
  val ctId: String,
  @XmlElement(true)
  @XmlSerialName(
    "WorkplaceIds",
    namespace = "http://ws.gematik.de/conn/ConnectorCommon/v5.0",
  )
  val workplaceIds: WorkplaceIds,
  @XmlElement(true)
  @XmlSerialName(
    "Name",
    namespace = "http://ws.gematik.de/conn/CardTerminalInfo/v8.0",
  )
  val name: String,
  @XmlElement(true)
  @XmlSerialName(
    "MacAddress",
    namespace = "http://ws.gematik.de/conn/CardTerminalInfo/v8.0",
  )
  val macAddress: String,
  @XmlElement(true)
  @XmlSerialName(
    "IPAddress",
    namespace = "http://ws.gematik.de/conn/CardTerminalInfo/v8.0",
  )
  val ipAddress: CardTerminalInfoTypeIpAddress? = null,
  @XmlElement(true)
  @XmlSerialName(
    "Slots",
    namespace = "http://ws.gematik.de/conn/CardTerminalInfo/v8.0",
  )
  val slots: Int,
  @XmlElement(true)
  @XmlSerialName(
    "IS_PHYSICAL",
    namespace = "http://ws.gematik.de/conn/CardTerminalInfo/v8.0",
  )
  val isPhysical: Boolean,
  @XmlElement(true)
  @XmlSerialName(
    "Connected",
    namespace = "http://ws.gematik.de/conn/CardTerminalInfo/v8.0",
  )
  val connected: Boolean,
)
