// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.gematik.conn.cardterminalinfo80

import kotlin.String
import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName

@Serializable
@XmlSerialName(
  "IPAddress",
  namespace = "http://ws.gematik.de/conn/CardTerminalInfo/v8.0",
)
data class CardTerminalInfoTypeIpAddress(
  @XmlElement(true)
  @XmlSerialName("IPV4Address")
  val ipv4Address: String? = null,
  @XmlElement(true)
  @XmlSerialName("IPV6Address")
  val ipv6Address: String? = null,
)
