// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.gematik.conn.certificateservice602

interface CertificateServicePort {
  fun checkCertificateExpiration(request: CheckCertificateExpiration): CheckCertificateExpirationResponse

  fun readCardCertificate(request: ReadCardCertificate): ReadCardCertificateResponse

  fun verifyCertificate(request: VerifyCertificate): VerifyCertificateResponse
}
