// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.gematik.conn.certificateservice602

import de.gematik.connector.api.gematik.conn.certificateservicecommon20.X509DataInfoList
import de.gematik.connector.api.gematik.conn.connectorcommon50.Status
import de.gematik.connector.api.gematik.conn.connectorcontext20.Context
import de.gematik.connector.api.gematik.tel.error20.Error
import kotlin.String
import kotlin.collections.List
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName

@Serializable
@XmlSerialName(
  "CheckCertificateExpiration",
  namespace = "http://ws.gematik.de/conn/CertificateService/v6.0",
)
data class CheckCertificateExpiration(
  @XmlElement(true)
  @XmlSerialName(
    "CardHandle",
    namespace = "http://ws.gematik.de/conn/ConnectorCommon/v5.0",
  )
  val cardHandle: String? = null,
  @XmlElement(true)
  @XmlSerialName(
    "Context",
    namespace = "http://ws.gematik.de/conn/ConnectorContext/v2.0",
  )
  val context: Context,
  @XmlElement(true)
  @XmlSerialName("Crypt")
  val crypt: CryptType? = null,
)

@Serializable
@XmlSerialName(
  "CheckCertificateExpirationResponse",
  namespace = "http://ws.gematik.de/conn/CertificateService/v6.0",
)
data class CheckCertificateExpirationResponse(
  @XmlElement(true)
  @XmlSerialName(
    "Status",
    namespace = "http://ws.gematik.de/conn/ConnectorCommon/v5.0",
  )
  val status: Status,
  @XmlElement(true)
  @XmlSerialName("CertificateExpiration")
  val certificateExpiration: List<CertificateExpirationType> = emptyList(),
)

@Serializable
@XmlSerialName(
  "ReadCardCertificate",
  namespace = "http://ws.gematik.de/conn/CertificateService/v6.0",
)
data class ReadCardCertificate(
  @XmlElement(true)
  @XmlSerialName(
    "CardHandle",
    namespace = "http://ws.gematik.de/conn/ConnectorCommon/v5.0",
  )
  val cardHandle: String,
  @XmlElement(true)
  @XmlSerialName(
    "Context",
    namespace = "http://ws.gematik.de/conn/ConnectorContext/v2.0",
  )
  val context: Context,
  @XmlElement(true)
  @XmlSerialName("CertRefList")
  val certRefList: ReadCardCertificateCertRefList,
  @XmlElement(true)
  @XmlSerialName("Crypt")
  val crypt: CryptType? = null,
)

@Serializable
@XmlSerialName(
  "ReadCardCertificateResponse",
  namespace = "http://ws.gematik.de/conn/CertificateService/v6.0",
)
data class ReadCardCertificateResponse(
  @XmlElement(true)
  @XmlSerialName(
    "Status",
    namespace = "http://ws.gematik.de/conn/ConnectorCommon/v5.0",
  )
  val status: Status,
  @XmlElement(true)
  @XmlSerialName(
    "X509DataInfoList",
    namespace = "http://ws.gematik.de/conn/CertificateServiceCommon/v2.0",
  )
  val x509DataInfoList: X509DataInfoList,
)

@Serializable
@XmlSerialName(
  "VerifyCertificate",
  namespace = "http://ws.gematik.de/conn/CertificateService/v6.0",
)
data class VerifyCertificate(
  @XmlElement(true)
  @XmlSerialName(
    "Context",
    namespace = "http://ws.gematik.de/conn/ConnectorContext/v2.0",
  )
  val context: Context,
  @XmlElement(true)
  @XmlSerialName(
    "X509Certificate",
    namespace = "http://ws.gematik.de/conn/CertificateServiceCommon/v2.0",
  )
  val x509Certificate: String,
  @XmlElement(true)
  @XmlSerialName("VerificationTime")
  val verificationTime: String? = null,
)

@Serializable
@XmlSerialName(
  "VerifyCertificateResponse",
  namespace = "http://ws.gematik.de/conn/CertificateService/v6.0",
)
data class VerifyCertificateResponse(
  @XmlElement(true)
  @XmlSerialName(
    "Status",
    namespace = "http://ws.gematik.de/conn/ConnectorCommon/v5.0",
  )
  val status: Status,
  @XmlElement(true)
  @XmlSerialName("VerificationStatus")
  val verificationStatus: VerifyCertificateResponseVerificationStatus,
  @XmlElement(true)
  @XmlSerialName("RoleList")
  val roleList: VerifyCertificateResponseRoleList,
)

@Serializable
data class CertificateExpirationType(
  @XmlElement(true)
  @XmlSerialName(
    "CtID",
    namespace = "http://ws.gematik.de/conn/CertificateService/v6.0",
  )
  val ctId: String,
  @XmlElement(true)
  @XmlSerialName(
    "CardHandle",
    namespace = "http://ws.gematik.de/conn/ConnectorCommon/v5.0",
  )
  val cardHandle: String,
  @XmlElement(true)
  @XmlSerialName(
    "ICCSN",
    namespace = "http://ws.gematik.de/conn/CertificateService/v6.0",
  )
  val iccsn: String,
  @XmlElement(true)
  @XmlSerialName(
    "subject_commonName",
    namespace = "http://ws.gematik.de/conn/CertificateService/v6.0",
  )
  val subjectCommonName: String,
  @XmlElement(true)
  @XmlSerialName(
    "serialNumber",
    namespace = "http://ws.gematik.de/conn/CertificateService/v6.0",
  )
  val serialNumber: String,
  @XmlElement(true)
  @XmlSerialName(
    "validity",
    namespace = "http://ws.gematik.de/conn/CertificateService/v6.0",
  )
  val validity: String,
)

@Serializable
enum class CryptType {
  @SerialName("RSA")
  Rsa,
  @SerialName("ECC")
  Ecc,
}

@Serializable
enum class VerificationResultType {
  @SerialName("VALID")
  Valid,
  @SerialName("INCONCLUSIVE")
  Inconclusive,
  @SerialName("INVALID")
  Invalid,
}

@Serializable
@XmlSerialName(
  "CertRefList",
  namespace = "http://ws.gematik.de/conn/CertificateService/v6.0",
)
data class ReadCardCertificateCertRefList(
  @XmlElement(true)
  @XmlSerialName("CertRef")
  val certRef: List<String> = emptyList(),
)

@Serializable
@XmlSerialName(
  "VerificationStatus",
  namespace = "http://ws.gematik.de/conn/CertificateService/v6.0",
)
data class VerifyCertificateResponseVerificationStatus(
  @XmlElement(true)
  @XmlSerialName("VerificationResult")
  val verificationResult: VerificationResultType,
  @XmlElement(true)
  @XmlSerialName(
    "Error",
    namespace = "http://ws.gematik.de/tel/error/v2.0",
  )
  val error: Error? = null,
)

@Serializable
@XmlSerialName(
  "RoleList",
  namespace = "http://ws.gematik.de/conn/CertificateService/v6.0",
)
data class VerifyCertificateResponseRoleList(
  @XmlElement(true)
  @XmlSerialName("Role")
  val role: List<String> = emptyList(),
)
