// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.gematik.conn.certificateservicecommon20

import kotlin.collections.List
import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName

@Serializable
data class CheckCertificateDetailsType(
  @XmlElement(true)
  @XmlSerialName(
    "CheckCertificateDetail",
    namespace = "http://ws.gematik.de/conn/CertificateServiceCommon/v2.0",
  )
  val checkCertificateDetail: List<CheckCertificateDetailEnum> = emptyList(),
)
