// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.gematik.conn.certificateservicecommon20

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
enum class CheckCertificateDetailEnum {
  @SerialName("CERT_SIG_ERROR")
  CertSigError,
  @SerialName("BUILD_CHAIN_FAILED")
  BuildChainFailed,
  @SerialName("CHECK_REVOCATION_FAILED")
  CheckRevocationFailed,
  @SerialName("CERT_REVOKED")
  CertRevoked,
  @SerialName("CERT_EXPIRED")
  CertExpired,
  @SerialName("CERT_BAD_FORMAT")
  CertBadFormat,
  @SerialName("POLICY_ERROR")
  PolicyError,
  @SerialName("QC_STATEMENT_ERROR")
  QcStatementError,
  @SerialName("WRONG_ROLE")
  WrongRole,
  @SerialName("UNKNOWN_CRITICAL_EXTENSIONS")
  UnknownCriticalExtensions,
  @SerialName("CERT_REVOKED_AFTER")
  CertRevokedAfter,
  @SerialName("NO_REVOCATION_CHECK")
  NoRevocationCheck,
  @SerialName("TSL_OUT_OF_DATE")
  TslOutOfDate,
  @SerialName("QUALIFIED")
  Qualified,
}
