// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.gematik.conn.certificateservicecommon20

import kotlin.String
import kotlin.collections.List
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName

@Serializable
@XmlSerialName(
  "X509DataInfoList",
  namespace = "http://ws.gematik.de/conn/CertificateServiceCommon/v2.0",
)
data class X509DataInfoList(
  @XmlElement(true)
  @XmlSerialName("X509DataInfo")
  val x509DataInfo: List<X509DataInfoListTypeX509DataInfo> = emptyList(),
)

@Serializable
@XmlSerialName(
  "CheckCertificateDetails",
  namespace = "http://ws.gematik.de/conn/CertificateServiceCommon/v2.0",
)
data class CheckCertificateDetails(
  @XmlElement(true)
  @XmlSerialName("CheckCertificateDetail")
  val checkCertificateDetail: List<CheckCertificateDetailEnum> = emptyList(),
)

@Serializable
enum class CertRefEnum {
  @SerialName("C.AUT")
  CAut,
  @SerialName("C.ENC")
  CEnc,
  @SerialName("C.SIG")
  CSig,
  @SerialName("C.QES")
  CQes,
}

@Serializable
enum class CheckCertificateDetailEnum {
  @SerialName("CERT_SIG_ERROR")
  CertSigError,
  @SerialName("BUILD_CHAIN_FAILED")
  BuildChainFailed,
  @SerialName("CHECK_REVOCATION_FAILED")
  CheckRevocationFailed,
  @SerialName("CERT_REVOKED")
  CertRevoked,
  @SerialName("CERT_EXPIRED")
  CertExpired,
  @SerialName("CERT_BAD_FORMAT")
  CertBadFormat,
  @SerialName("POLICY_ERROR")
  PolicyError,
  @SerialName("QC_STATEMENT_ERROR")
  QcStatementError,
  @SerialName("WRONG_ROLE")
  WrongRole,
  @SerialName("UNKNOWN_CRITICAL_EXTENSIONS")
  UnknownCriticalExtensions,
  @SerialName("CERT_REVOKED_AFTER")
  CertRevokedAfter,
  @SerialName("NO_REVOCATION_CHECK")
  NoRevocationCheck,
  @SerialName("TSL_OUT_OF_DATE")
  TslOutOfDate,
  @SerialName("QUALIFIED")
  Qualified,
}

@Serializable
data class CheckCertificateDetailsType(
  @XmlElement(true)
  @XmlSerialName(
    "CheckCertificateDetail",
    namespace = "http://ws.gematik.de/conn/CertificateServiceCommon/v2.0",
  )
  val checkCertificateDetail: List<CheckCertificateDetailEnum> = emptyList(),
)

@Serializable
data class X509DataInfoListType(
  @XmlElement(true)
  @XmlSerialName(
    "X509DataInfo",
    namespace = "http://ws.gematik.de/conn/CertificateServiceCommon/v2.0",
  )
  val x509DataInfo: List<X509DataInfoListTypeX509DataInfo> = emptyList(),
)

@Serializable
@XmlSerialName(
  "X509DataInfo",
  namespace = "http://ws.gematik.de/conn/CertificateServiceCommon/v2.0",
)
data class X509DataInfoListTypeX509DataInfo(
  @XmlElement(true)
  @XmlSerialName("CertRef")
  val certRef: CertRefEnum,
  @XmlElement(true)
  @XmlSerialName("X509Data")
  val x509Data: X509DataInfoListTypeX509DataInfoX509Data? = null,
)

@Serializable
@XmlSerialName(
  "X509Data",
  namespace = "http://ws.gematik.de/conn/CertificateServiceCommon/v2.0",
)
data class X509DataInfoListTypeX509DataInfoX509Data(
  @XmlElement(true)
  @XmlSerialName("X509IssuerSerial")
  val x509IssuerSerial: X509DataInfoListTypeX509DataInfoX509DataX509IssuerSerial,
  @XmlElement(true)
  @XmlSerialName("X509SubjectName")
  val x509SubjectName: String,
  @XmlElement(true)
  @XmlSerialName("X509Certificate")
  val x509Certificate: String,
)

@Serializable
@XmlSerialName(
  "X509IssuerSerial",
  namespace = "http://ws.gematik.de/conn/CertificateServiceCommon/v2.0",
)
data class X509DataInfoListTypeX509DataInfoX509DataX509IssuerSerial(
  @XmlElement(true)
  @XmlSerialName("X509IssuerName")
  val x509IssuerName: String,
  @XmlElement(true)
  @XmlSerialName("X509SerialNumber")
  val x509SerialNumber: String,
)
