// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.gematik.conn.certificateservicecommon20

import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName

@Serializable
@XmlSerialName(
  "X509DataInfo",
  namespace = "http://ws.gematik.de/conn/CertificateServiceCommon/v2.0",
)
data class X509DataInfoListTypeX509DataInfo(
  @XmlElement(true)
  @XmlSerialName("CertRef")
  val certRef: CertRefEnum,
  @XmlElement(true)
  @XmlSerialName("X509Data")
  val x509Data: X509DataInfoListTypeX509DataInfoX509Data? = null,
)
