// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.gematik.conn.certificateservicecommon20

import kotlin.String
import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName

@Serializable
@XmlSerialName(
  "X509IssuerSerial",
  namespace = "http://ws.gematik.de/conn/CertificateServiceCommon/v2.0",
)
data class X509DataInfoListTypeX509DataInfoX509DataX509IssuerSerial(
  @XmlElement(true)
  @XmlSerialName("X509IssuerName")
  val x509IssuerName: String,
  @XmlElement(true)
  @XmlSerialName("X509SerialNumber")
  val x509SerialNumber: String,
)
