// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.gematik.conn.connectorcontext20

import kotlin.String
import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName

@Serializable
@XmlSerialName(
  "Context",
  namespace = "http://ws.gematik.de/conn/ConnectorContext/v2.0",
)
data class Context(
  @XmlElement(true)
  @XmlSerialName(
    "MandantId",
    namespace = "http://ws.gematik.de/conn/ConnectorCommon/v5.0",
  )
  val mandantId: String,
  @XmlElement(true)
  @XmlSerialName(
    "ClientSystemId",
    namespace = "http://ws.gematik.de/conn/ConnectorCommon/v5.0",
  )
  val clientSystemId: String,
  @XmlElement(true)
  @XmlSerialName(
    "WorkplaceId",
    namespace = "http://ws.gematik.de/conn/ConnectorCommon/v5.0",
  )
  val workplaceId: String,
  @XmlElement(true)
  @XmlSerialName(
    "UserId",
    namespace = "http://ws.gematik.de/conn/ConnectorCommon/v5.0",
  )
  val userId: String? = null,
)

@Serializable
data class ContextType(
  @XmlElement(true)
  @XmlSerialName(
    "MandantId",
    namespace = "http://ws.gematik.de/conn/ConnectorCommon/v5.0",
  )
  val mandantId: String,
  @XmlElement(true)
  @XmlSerialName(
    "ClientSystemId",
    namespace = "http://ws.gematik.de/conn/ConnectorCommon/v5.0",
  )
  val clientSystemId: String,
  @XmlElement(true)
  @XmlSerialName(
    "WorkplaceId",
    namespace = "http://ws.gematik.de/conn/ConnectorCommon/v5.0",
  )
  val workplaceId: String,
  @XmlElement(true)
  @XmlSerialName(
    "UserId",
    namespace = "http://ws.gematik.de/conn/ConnectorCommon/v5.0",
  )
  val userId: String? = null,
)
