// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.oasis.dss10core

import kotlin.String
import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName
import nl.adaptivity.xmlutil.serialization.XmlValue

@Serializable
@XmlSerialName(
  "AdditionalTimeInfo",
  namespace = "urn:oasis:names:tc:dss:1.0:core:schema",
)
data class AdditionalTimeInfo(
  @XmlElement(false)
  @XmlSerialName("Type")
  val type: String,
  @XmlElement(false)
  @XmlSerialName("Ref")
  val ref: String? = null,
  @XmlValue(true)
  val charData: String,
)
