// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.oasis.dss10core

import kotlin.String
import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName

@Serializable
@XmlSerialName(
  "Document",
  namespace = "urn:oasis:names:tc:dss:1.0:core:schema",
)
data class Document(
  @XmlElement(false)
  @XmlSerialName("ID")
  val id: String? = null,
  @XmlElement(false)
  @XmlSerialName("RefURI")
  val refUri: String? = null,
  @XmlElement(false)
  @XmlSerialName("RefType")
  val refType: String? = null,
  @XmlElement(false)
  @XmlSerialName("SchemaRefs")
  val schemaRefs: String? = null,
  @XmlElement(true)
  @XmlSerialName("InlineXML")
  val inlineXml: InlineXMLType? = null,
  @XmlElement(true)
  @XmlSerialName("Base64XML")
  val base64Xml: String? = null,
  @XmlElement(true)
  @XmlSerialName("EscapedXML")
  val escapedXml: String? = null,
  @XmlElement(true)
  @XmlSerialName("Base64Data")
  val base64Data: Base64Data? = null,
  @XmlElement(true)
  @XmlSerialName("AttachmentReference")
  val attachmentReference: AttachmentReference? = null,
)
