// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.oasis.dss10core

import kotlin.String
import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName

@Serializable
data class DocumentBaseType(
  @XmlElement(false)
  @XmlSerialName("ID")
  val id: String? = null,
  @XmlElement(false)
  @XmlSerialName("RefURI")
  val refUri: String? = null,
  @XmlElement(false)
  @XmlSerialName("RefType")
  val refType: String? = null,
  @XmlElement(false)
  @XmlSerialName("SchemaRefs")
  val schemaRefs: String? = null,
)
