// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.oasis.dss10core

import kotlin.Boolean
import kotlin.String
import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName

@Serializable
@XmlSerialName(
  "IncludeObject",
  namespace = "urn:oasis:names:tc:dss:1.0:core:schema",
)
data class IncludeObject(
  @XmlElement(false)
  @XmlSerialName("WhichDocument")
  val whichDocument: String? = null,
  @XmlElement(false)
  @XmlSerialName("hasObjectTagsAndAttributesSet")
  val hasObjectTagsAndAttributesSet: Boolean? = null,
  @XmlElement(false)
  @XmlSerialName("ObjId")
  val objId: String? = null,
  @XmlElement(false)
  @XmlSerialName("createReference")
  val createReference: Boolean? = null,
)
