// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.oasis.dss10core

import kotlin.Boolean
import kotlin.String
import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName

@Serializable
data class InlineXMLType(
  @XmlElement(false)
  @XmlSerialName("ignorePIs")
  val ignoreProcessingInstructions: Boolean? = null,
  @XmlElement(false)
  @XmlSerialName("ignoreComments")
  val ignoreComments: Boolean? = null,
  @XmlElement(true)
  val unknownContent: String? = null,
)
