// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.oasis.dss10core

import kotlin.collections.List
import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName

@Serializable
@XmlSerialName(
  "InputDocuments",
  namespace = "urn:oasis:names:tc:dss:1.0:core:schema",
)
data class InputDocuments(
  @XmlElement(true)
  @XmlSerialName("Document")
  val document: List<Document> = emptyList(),
  @XmlElement(true)
  @XmlSerialName("TransformedData")
  val transformedData: List<TransformedData> = emptyList(),
  @XmlElement(true)
  @XmlSerialName("DocumentHash")
  val documentHash: List<DocumentHash> = emptyList(),
  @XmlElement(true)
  @XmlSerialName("Other")
  val other: List<AnyType> = emptyList(),
)
