// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.oasis.dss10core

import kotlin.String
import kotlin.collections.List
import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName

@Serializable
@XmlSerialName(
  "IntendedAudience",
  namespace = "urn:oasis:names:tc:dss:1.0:core:schema",
)
data class IntendedAudience(
  @XmlElement(true)
  @XmlSerialName("Recipient")
  val recipient: List<String> = emptyList(),
)
