// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.oasis.dss10core

import kotlin.String
import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName

@Serializable
@XmlSerialName(
  "ManifestResult",
  namespace = "urn:oasis:names:tc:dss:1.0:core:schema",
)
data class ManifestResult(
  @XmlElement(true)
  @XmlSerialName("ReferenceXpath")
  val referenceXpath: String,
  @XmlElement(true)
  @XmlSerialName("Status")
  val status: String,
)
