// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.oasis.dss10core

import kotlin.collections.List
import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName

@Serializable
@XmlSerialName(
  "ProcessingDetails",
  namespace = "urn:oasis:names:tc:dss:1.0:core:schema",
)
data class ProcessingDetails(
  @XmlElement(true)
  @XmlSerialName("ValidDetail")
  val validDetail: List<DetailType> = emptyList(),
  @XmlElement(true)
  @XmlSerialName("IndeterminateDetail")
  val indeterminateDetail: List<DetailType> = emptyList(),
  @XmlElement(true)
  @XmlSerialName("InvalidDetail")
  val invalidDetail: List<DetailType> = emptyList(),
)
