// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.oasis.dss10core

import de.gematik.connector.api.w3200009.xmldsig.DigestMethod
import de.gematik.connector.api.w3200009.xmldsig.KeyInfo
import de.gematik.connector.api.w3200009.xmldsig.Signature
import de.gematik.connector.api.w3200009.xmldsig.Transforms
import kotlin.Boolean
import kotlin.Int
import kotlin.String
import kotlin.collections.List
import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName
import nl.adaptivity.xmlutil.serialization.XmlValue

@Serializable
@XmlSerialName(
  "InputDocuments",
  namespace = "urn:oasis:names:tc:dss:1.0:core:schema",
)
data class InputDocuments(
  @XmlElement(true)
  @XmlSerialName("Document")
  val document: List<Document> = emptyList(),
  @XmlElement(true)
  @XmlSerialName("TransformedData")
  val transformedData: List<TransformedData> = emptyList(),
  @XmlElement(true)
  @XmlSerialName("DocumentHash")
  val documentHash: List<DocumentHash> = emptyList(),
  @XmlElement(true)
  @XmlSerialName("Other")
  val other: List<AnyType> = emptyList(),
)

@Serializable
@XmlSerialName(
  "Document",
  namespace = "urn:oasis:names:tc:dss:1.0:core:schema",
)
data class Document(
  @XmlElement(false)
  @XmlSerialName("ID")
  val id: String? = null,
  @XmlElement(false)
  @XmlSerialName("RefURI")
  val refUri: String? = null,
  @XmlElement(false)
  @XmlSerialName("RefType")
  val refType: String? = null,
  @XmlElement(false)
  @XmlSerialName("SchemaRefs")
  val schemaRefs: String? = null,
  @XmlElement(true)
  @XmlSerialName("InlineXML")
  val inlineXml: InlineXMLType? = null,
  @XmlElement(true)
  @XmlSerialName("Base64XML")
  val base64Xml: String? = null,
  @XmlElement(true)
  @XmlSerialName("EscapedXML")
  val escapedXml: String? = null,
  @XmlElement(true)
  @XmlSerialName("Base64Data")
  val base64Data: Base64Data? = null,
  @XmlElement(true)
  @XmlSerialName("AttachmentReference")
  val attachmentReference: AttachmentReference? = null,
)

@Serializable
@XmlSerialName(
  "Base64Data",
  namespace = "urn:oasis:names:tc:dss:1.0:core:schema",
)
data class Base64Data(
  @XmlElement(false)
  @XmlSerialName("MimeType")
  val mimeType: String? = null,
  @XmlValue(true)
  val charData: String,
)

@Serializable
@XmlSerialName(
  "TransformedData",
  namespace = "urn:oasis:names:tc:dss:1.0:core:schema",
)
data class TransformedData(
  @XmlElement(false)
  @XmlSerialName("ID")
  val id: String? = null,
  @XmlElement(false)
  @XmlSerialName("RefURI")
  val refUri: String? = null,
  @XmlElement(false)
  @XmlSerialName("RefType")
  val refType: String? = null,
  @XmlElement(false)
  @XmlSerialName("SchemaRefs")
  val schemaRefs: String? = null,
  @XmlElement(false)
  @XmlSerialName("WhichReference")
  val whichReference: Int? = null,
  @XmlElement(true)
  @XmlSerialName(
    "Transforms",
    namespace = "http://www.w3.org/2000/09/xmldsig#",
  )
  val transforms: Transforms? = null,
  @XmlElement(true)
  @XmlSerialName("Base64Data")
  val base64Data: Base64Data,
)

@Serializable
@XmlSerialName(
  "DocumentHash",
  namespace = "urn:oasis:names:tc:dss:1.0:core:schema",
)
data class DocumentHash(
  @XmlElement(false)
  @XmlSerialName("ID")
  val id: String? = null,
  @XmlElement(false)
  @XmlSerialName("RefURI")
  val refUri: String? = null,
  @XmlElement(false)
  @XmlSerialName("RefType")
  val refType: String? = null,
  @XmlElement(false)
  @XmlSerialName("SchemaRefs")
  val schemaRefs: String? = null,
  @XmlElement(false)
  @XmlSerialName("WhichReference")
  val whichReference: Int? = null,
  @XmlElement(true)
  @XmlSerialName(
    "Transforms",
    namespace = "http://www.w3.org/2000/09/xmldsig#",
  )
  val transforms: Transforms? = null,
  @XmlElement(true)
  @XmlSerialName(
    "DigestMethod",
    namespace = "http://www.w3.org/2000/09/xmldsig#",
  )
  val digestMethod: DigestMethod? = null,
  @XmlElement(true)
  @XmlSerialName(
    "DigestValue",
    namespace = "http://www.w3.org/2000/09/xmldsig#",
  )
  val digestValue: String,
)

@Serializable
@XmlSerialName(
  "SignatureObject",
  namespace = "urn:oasis:names:tc:dss:1.0:core:schema",
)
data class SignatureObject(
  @XmlElement(false)
  @XmlSerialName("SchemaRefs")
  val schemaRefs: String? = null,
  @XmlElement(true)
  @XmlSerialName(
    "Signature",
    namespace = "http://www.w3.org/2000/09/xmldsig#",
  )
  val signature: Signature? = null,
  @XmlElement(true)
  @XmlSerialName("Timestamp")
  val timestamp: Timestamp? = null,
  @XmlElement(true)
  @XmlSerialName("Base64Signature")
  val base64Signature: Base64Signature? = null,
  @XmlElement(true)
  @XmlSerialName("SignaturePtr")
  val signaturePtr: SignaturePtr? = null,
  @XmlElement(true)
  @XmlSerialName("Other")
  val other: AnyType? = null,
)

@Serializable
@XmlSerialName(
  "Base64Signature",
  namespace = "urn:oasis:names:tc:dss:1.0:core:schema",
)
data class Base64Signature(
  @XmlElement(false)
  @XmlSerialName("Type")
  val type: String? = null,
  @XmlValue(true)
  val charData: String,
)

@Serializable
@XmlSerialName(
  "SignaturePtr",
  namespace = "urn:oasis:names:tc:dss:1.0:core:schema",
)
data class SignaturePtr(
  @XmlElement(false)
  @XmlSerialName("WhichDocument")
  val whichDocument: String? = null,
  @XmlElement(false)
  @XmlSerialName("XPath")
  val xPath: String? = null,
)

@Serializable
@XmlSerialName(
  "Result",
  namespace = "urn:oasis:names:tc:dss:1.0:core:schema",
)
data class Result(
  @XmlElement(true)
  @XmlSerialName("ResultMajor")
  val resultMajor: String,
  @XmlElement(true)
  @XmlSerialName("ResultMinor")
  val resultMinor: String? = null,
  @XmlElement(true)
  @XmlSerialName("ResultMessage")
  val resultMessage: InternationalStringType? = null,
)

@Serializable
@XmlSerialName(
  "OptionalInputs",
  namespace = "urn:oasis:names:tc:dss:1.0:core:schema",
)
data class OptionalInputs(
  @XmlElement(true)
  val unknownContent: String? = null,
)

@Serializable
@XmlSerialName(
  "OptionalOutputs",
  namespace = "urn:oasis:names:tc:dss:1.0:core:schema",
)
data class OptionalOutputs(
  @XmlElement(true)
  val unknownContent: String? = null,
)

@Serializable
@XmlSerialName(
  "ClaimedIdentity",
  namespace = "urn:oasis:names:tc:dss:1.0:core:schema",
)
data class ClaimedIdentity(
  @XmlElement(true)
  @XmlSerialName("Name")
  val name: String,
  @XmlElement(true)
  @XmlSerialName("SupportingInfo")
  val supportingInfo: AnyType? = null,
)

@Serializable
@XmlSerialName(
  "Schemas",
  namespace = "urn:oasis:names:tc:dss:1.0:core:schema",
)
data class Schemas(
  @XmlElement(true)
  @XmlSerialName("Schema")
  val schema: List<Schema> = emptyList(),
)

@Serializable
@XmlSerialName(
  "Schema",
  namespace = "urn:oasis:names:tc:dss:1.0:core:schema",
)
data class Schema(
  @XmlElement(false)
  @XmlSerialName("ID")
  val id: String? = null,
  @XmlElement(false)
  @XmlSerialName("RefURI")
  val refUri: String? = null,
  @XmlElement(false)
  @XmlSerialName("RefType")
  val refType: String? = null,
  @XmlElement(false)
  @XmlSerialName("SchemaRefs")
  val schemaRefs: String? = null,
  @XmlElement(true)
  @XmlSerialName("InlineXML")
  val inlineXml: InlineXMLType? = null,
  @XmlElement(true)
  @XmlSerialName("Base64XML")
  val base64Xml: String? = null,
  @XmlElement(true)
  @XmlSerialName("EscapedXML")
  val escapedXml: String? = null,
  @XmlElement(true)
  @XmlSerialName("Base64Data")
  val base64Data: Base64Data? = null,
  @XmlElement(true)
  @XmlSerialName("AttachmentReference")
  val attachmentReference: AttachmentReference? = null,
)

@Serializable
@XmlSerialName(
  "Response",
  namespace = "urn:oasis:names:tc:dss:1.0:core:schema",
)
data class Response(
  @XmlElement(false)
  @XmlSerialName("RequestID")
  val requestId: String? = null,
  @XmlElement(false)
  @XmlSerialName("Profile")
  val profile: String,
  @XmlElement(true)
  @XmlSerialName("Result")
  val result: Result,
  @XmlElement(true)
  @XmlSerialName("OptionalOutputs")
  val optionalOutputs: OptionalOutputs? = null,
)

@Serializable
@XmlSerialName(
  "SignRequest",
  namespace = "urn:oasis:names:tc:dss:1.0:core:schema",
)
data class SignRequest(
  @XmlElement(false)
  @XmlSerialName("RequestID")
  val requestId: String? = null,
  @XmlElement(false)
  @XmlSerialName("Profile")
  val profile: String? = null,
  @XmlElement(true)
  @XmlSerialName("OptionalInputs")
  val optionalInputs: OptionalInputs? = null,
  @XmlElement(true)
  @XmlSerialName("InputDocuments")
  val inputDocuments: InputDocuments? = null,
)

@Serializable
@XmlSerialName(
  "SignResponse",
  namespace = "urn:oasis:names:tc:dss:1.0:core:schema",
)
data class SignResponse(
  @XmlElement(false)
  @XmlSerialName("RequestID")
  val requestId: String? = null,
  @XmlElement(false)
  @XmlSerialName("Profile")
  val profile: String,
  @XmlElement(true)
  @XmlSerialName("Result")
  val result: Result,
  @XmlElement(true)
  @XmlSerialName("OptionalOutputs")
  val optionalOutputs: OptionalOutputs? = null,
  @XmlElement(true)
  @XmlSerialName("SignatureObject")
  val signatureObject: SignatureObject? = null,
)

@Serializable
@XmlSerialName(
  "AddTimestamp",
  namespace = "urn:oasis:names:tc:dss:1.0:core:schema",
)
data class AddTimestamp(
  @XmlElement(false)
  @XmlSerialName("Type")
  val type: String? = null,
)

@Serializable
@XmlSerialName(
  "IntendedAudience",
  namespace = "urn:oasis:names:tc:dss:1.0:core:schema",
)
data class IntendedAudience(
  @XmlElement(true)
  @XmlSerialName("Recipient")
  val recipient: List<String> = emptyList(),
)

@Serializable
@XmlSerialName(
  "KeySelector",
  namespace = "urn:oasis:names:tc:dss:1.0:core:schema",
)
data class KeySelector(
  @XmlElement(true)
  @XmlSerialName(
    "KeyInfo",
    namespace = "http://www.w3.org/2000/09/xmldsig#",
  )
  val keyInfo: KeyInfo? = null,
  @XmlElement(true)
  @XmlSerialName("Other")
  val other: AnyType? = null,
)

@Serializable
@XmlSerialName(
  "Properties",
  namespace = "urn:oasis:names:tc:dss:1.0:core:schema",
)
data class Properties(
  @XmlElement(true)
  @XmlSerialName("SignedProperties")
  val signedProperties: PropertiesType? = null,
  @XmlElement(true)
  @XmlSerialName("UnsignedProperties")
  val unsignedProperties: PropertiesType? = null,
)

@Serializable
@XmlSerialName(
  "Property",
  namespace = "urn:oasis:names:tc:dss:1.0:core:schema",
)
data class Property(
  @XmlElement(true)
  @XmlSerialName("Identifier")
  val identifier: String,
  @XmlElement(true)
  @XmlSerialName("Value")
  val `value`: AnyType? = null,
)

@Serializable
@XmlSerialName(
  "IncludeObject",
  namespace = "urn:oasis:names:tc:dss:1.0:core:schema",
)
data class IncludeObject(
  @XmlElement(false)
  @XmlSerialName("WhichDocument")
  val whichDocument: String? = null,
  @XmlElement(false)
  @XmlSerialName("hasObjectTagsAndAttributesSet")
  val hasObjectTagsAndAttributesSet: Boolean? = null,
  @XmlElement(false)
  @XmlSerialName("ObjId")
  val objId: String? = null,
  @XmlElement(false)
  @XmlSerialName("createReference")
  val createReference: Boolean? = null,
)

@Serializable
@XmlSerialName(
  "SignaturePlacement",
  namespace = "urn:oasis:names:tc:dss:1.0:core:schema",
)
data class SignaturePlacement(
  @XmlElement(false)
  @XmlSerialName("WhichDocument")
  val whichDocument: String? = null,
  @XmlElement(false)
  @XmlSerialName("CreateEnvelopedSignature")
  val createEnvelopedSignature: Boolean? = null,
  @XmlElement(true)
  @XmlSerialName("XPathAfter")
  val xPathAfter: String? = null,
  @XmlElement(true)
  @XmlSerialName("XPathFirstChildOf")
  val xPathFirstChildOf: String? = null,
)

@Serializable
@XmlSerialName(
  "DocumentWithSignature",
  namespace = "urn:oasis:names:tc:dss:1.0:core:schema",
)
data class DocumentWithSignature(
  @XmlElement(true)
  @XmlSerialName("Document")
  val document: Document,
)

@Serializable
@XmlSerialName(
  "SignedReferences",
  namespace = "urn:oasis:names:tc:dss:1.0:core:schema",
)
data class SignedReferences(
  @XmlElement(true)
  @XmlSerialName("SignedReference")
  val signedReference: List<SignedReference> = emptyList(),
)

@Serializable
@XmlSerialName(
  "SignedReference",
  namespace = "urn:oasis:names:tc:dss:1.0:core:schema",
)
data class SignedReference(
  @XmlElement(false)
  @XmlSerialName("WhichDocument")
  val whichDocument: String,
  @XmlElement(false)
  @XmlSerialName("RefURI")
  val refUri: String? = null,
  @XmlElement(false)
  @XmlSerialName("RefId")
  val refId: String? = null,
  @XmlElement(true)
  @XmlSerialName(
    "Transforms",
    namespace = "http://www.w3.org/2000/09/xmldsig#",
  )
  val transforms: Transforms? = null,
)

@Serializable
@XmlSerialName(
  "VerifyRequest",
  namespace = "urn:oasis:names:tc:dss:1.0:core:schema",
)
data class VerifyRequest(
  @XmlElement(false)
  @XmlSerialName("RequestID")
  val requestId: String? = null,
  @XmlElement(false)
  @XmlSerialName("Profile")
  val profile: String? = null,
  @XmlElement(true)
  @XmlSerialName("OptionalInputs")
  val optionalInputs: OptionalInputs? = null,
  @XmlElement(true)
  @XmlSerialName("InputDocuments")
  val inputDocuments: InputDocuments? = null,
  @XmlElement(true)
  @XmlSerialName("SignatureObject")
  val signatureObject: SignatureObject? = null,
)

@Serializable
@XmlSerialName(
  "VerifyResponse",
  namespace = "urn:oasis:names:tc:dss:1.0:core:schema",
)
data class VerifyResponse(
  @XmlElement(false)
  @XmlSerialName("RequestID")
  val requestId: String? = null,
  @XmlElement(false)
  @XmlSerialName("Profile")
  val profile: String,
  @XmlElement(true)
  @XmlSerialName("Result")
  val result: Result,
  @XmlElement(true)
  @XmlSerialName("OptionalOutputs")
  val optionalOutputs: OptionalOutputs? = null,
)

@Serializable
@XmlSerialName(
  "VerifyManifestResults",
  namespace = "urn:oasis:names:tc:dss:1.0:core:schema",
)
data class VerifyManifestResults(
  @XmlElement(true)
  @XmlSerialName("ManifestResult")
  val manifestResult: List<ManifestResult> = emptyList(),
)

@Serializable
@XmlSerialName(
  "ManifestResult",
  namespace = "urn:oasis:names:tc:dss:1.0:core:schema",
)
data class ManifestResult(
  @XmlElement(true)
  @XmlSerialName("ReferenceXpath")
  val referenceXpath: String,
  @XmlElement(true)
  @XmlSerialName("Status")
  val status: String,
)

@Serializable
@XmlSerialName(
  "AdditionalTimeInfo",
  namespace = "urn:oasis:names:tc:dss:1.0:core:schema",
)
data class AdditionalTimeInfo(
  @XmlElement(false)
  @XmlSerialName("Type")
  val type: String,
  @XmlElement(false)
  @XmlSerialName("Ref")
  val ref: String? = null,
  @XmlValue(true)
  val charData: String,
)

@Serializable
@XmlSerialName(
  "VerificationTimeInfo",
  namespace = "urn:oasis:names:tc:dss:1.0:core:schema",
)
data class VerificationTimeInfo(
  @XmlElement(true)
  @XmlSerialName("VerificationTime")
  val verificationTime: String,
  @XmlElement(true)
  @XmlSerialName("AdditionalTimeInfo")
  val additionalTimeInfo: List<AdditionalTimeInfo> = emptyList(),
)

@Serializable
@XmlSerialName(
  "AdditionalKeyInfo",
  namespace = "urn:oasis:names:tc:dss:1.0:core:schema",
)
data class AdditionalKeyInfo(
  @XmlElement(true)
  @XmlSerialName(
    "KeyInfo",
    namespace = "http://www.w3.org/2000/09/xmldsig#",
  )
  val keyInfo: KeyInfo,
)

@Serializable
@XmlSerialName(
  "ProcessingDetails",
  namespace = "urn:oasis:names:tc:dss:1.0:core:schema",
)
data class ProcessingDetails(
  @XmlElement(true)
  @XmlSerialName("ValidDetail")
  val validDetail: List<DetailType> = emptyList(),
  @XmlElement(true)
  @XmlSerialName("IndeterminateDetail")
  val indeterminateDetail: List<DetailType> = emptyList(),
  @XmlElement(true)
  @XmlSerialName("InvalidDetail")
  val invalidDetail: List<DetailType> = emptyList(),
)

@Serializable
@XmlSerialName(
  "SigningTimeInfo",
  namespace = "urn:oasis:names:tc:dss:1.0:core:schema",
)
data class SigningTimeInfo(
  @XmlElement(true)
  @XmlSerialName("SigningTime")
  val signingTime: String,
  @XmlElement(true)
  @XmlSerialName("SigningTimeBoundaries")
  val signingTimeBoundaries: SigningTimeInfoTypeSigningTimeBoundaries? = null,
)

@Serializable
@XmlSerialName(
  "ReturnUpdatedSignature",
  namespace = "urn:oasis:names:tc:dss:1.0:core:schema",
)
data class ReturnUpdatedSignature(
  @XmlElement(false)
  @XmlSerialName("Type")
  val type: String? = null,
)

@Serializable
@XmlSerialName(
  "UpdatedSignature",
  namespace = "urn:oasis:names:tc:dss:1.0:core:schema",
)
data class UpdatedSignature(
  @XmlElement(false)
  @XmlSerialName("Type")
  val type: String? = null,
  @XmlElement(true)
  @XmlSerialName("SignatureObject")
  val signatureObject: SignatureObject,
)

@Serializable
@XmlSerialName(
  "ReturnTransformedDocument",
  namespace = "urn:oasis:names:tc:dss:1.0:core:schema",
)
data class ReturnTransformedDocument(
  @XmlElement(false)
  @XmlSerialName("WhichReference")
  val whichReference: Int,
)

@Serializable
@XmlSerialName(
  "TransformedDocument",
  namespace = "urn:oasis:names:tc:dss:1.0:core:schema",
)
data class TransformedDocument(
  @XmlElement(false)
  @XmlSerialName("WhichReference")
  val whichReference: Int,
  @XmlElement(true)
  @XmlSerialName("Document")
  val document: Document,
)

@Serializable
@XmlSerialName(
  "ReturnTimestampedSignature",
  namespace = "urn:oasis:names:tc:dss:1.0:core:schema",
)
data class ReturnTimestampedSignature(
  @XmlElement(false)
  @XmlSerialName("Type")
  val type: String? = null,
)

@Serializable
@XmlSerialName(
  "TimestampedSignature",
  namespace = "urn:oasis:names:tc:dss:1.0:core:schema",
)
data class TimestampedSignature(
  @XmlElement(false)
  @XmlSerialName("Type")
  val type: String? = null,
  @XmlElement(true)
  @XmlSerialName("SignatureObject")
  val signatureObject: SignatureObject,
)

@Serializable
@XmlSerialName(
  "Timestamp",
  namespace = "urn:oasis:names:tc:dss:1.0:core:schema",
)
data class Timestamp(
  @XmlElement(true)
  @XmlSerialName(
    "Signature",
    namespace = "http://www.w3.org/2000/09/xmldsig#",
  )
  val signature: Signature? = null,
  @XmlElement(true)
  @XmlSerialName("RFC3161TimeStampToken")
  val rfc3161TimeStampToken: String? = null,
  @XmlElement(true)
  @XmlSerialName("Other")
  val other: AnyType? = null,
)

@Serializable
@XmlSerialName(
  "TstInfo",
  namespace = "urn:oasis:names:tc:dss:1.0:core:schema",
)
data class TstInfo(
  @XmlElement(true)
  @XmlSerialName("SerialNumber")
  val serialNumber: Int,
  @XmlElement(true)
  @XmlSerialName("CreationTime")
  val creationTime: String,
  @XmlElement(true)
  @XmlSerialName("Policy")
  val policy: String? = null,
  @XmlElement(true)
  @XmlSerialName("ErrorBound")
  val errorBound: String? = null,
  @XmlElement(true)
  @XmlSerialName("Ordered")
  val ordered: Boolean? = null,
  @XmlElement(true)
  @XmlSerialName("TSA")
  val tsa: String? = null,
)

@Serializable
@XmlSerialName(
  "RequesterIdentity",
  namespace = "urn:oasis:names:tc:dss:1.0:core:schema",
)
data class RequesterIdentity(
  @XmlElement(true)
  @XmlSerialName("Name")
  val name: String,
  @XmlElement(true)
  @XmlSerialName("SupportingInfo")
  val supportingInfo: AnyType? = null,
)

@Serializable
@XmlSerialName(
  "AttachmentReference",
  namespace = "urn:oasis:names:tc:dss:1.0:core:schema",
)
data class AttachmentReference(
  @XmlElement(false)
  @XmlSerialName("AttRefURI")
  val attRefUri: String? = null,
  @XmlElement(false)
  @XmlSerialName("MimeType")
  val mimeType: String? = null,
  @XmlElement(true)
  @XmlSerialName(
    "DigestMethod",
    namespace = "http://www.w3.org/2000/09/xmldsig#",
  )
  val digestMethod: DigestMethod,
  @XmlElement(true)
  @XmlSerialName(
    "DigestValue",
    namespace = "http://www.w3.org/2000/09/xmldsig#",
  )
  val digestValue: String,
)

@Serializable
data class AnyType(
  @XmlElement(true)
  val unknownContent: String? = null,
)

@Serializable
data class InternationalStringType(
  @XmlElement(false)
  @XmlSerialName(
    "lang",
    namespace = "http://www.w3.org/XML/1998/namespace",
  )
  val lang: String? = null,
  @XmlValue(true)
  val charData: String,
)

@Serializable
data class DocumentBaseType(
  @XmlElement(false)
  @XmlSerialName("ID")
  val id: String? = null,
  @XmlElement(false)
  @XmlSerialName("RefURI")
  val refUri: String? = null,
  @XmlElement(false)
  @XmlSerialName("RefType")
  val refType: String? = null,
  @XmlElement(false)
  @XmlSerialName("SchemaRefs")
  val schemaRefs: String? = null,
)

@Serializable
data class DocumentType(
  @XmlElement(false)
  @XmlSerialName("ID")
  val id: String? = null,
  @XmlElement(false)
  @XmlSerialName("RefURI")
  val refUri: String? = null,
  @XmlElement(false)
  @XmlSerialName("RefType")
  val refType: String? = null,
  @XmlElement(false)
  @XmlSerialName("SchemaRefs")
  val schemaRefs: String? = null,
  @XmlElement(true)
  @XmlSerialName(
    "InlineXML",
    namespace = "urn:oasis:names:tc:dss:1.0:core:schema",
  )
  val inlineXml: InlineXMLType? = null,
  @XmlElement(true)
  @XmlSerialName(
    "Base64XML",
    namespace = "urn:oasis:names:tc:dss:1.0:core:schema",
  )
  val base64Xml: String? = null,
  @XmlElement(true)
  @XmlSerialName(
    "EscapedXML",
    namespace = "urn:oasis:names:tc:dss:1.0:core:schema",
  )
  val escapedXml: String? = null,
  @XmlElement(true)
  @XmlSerialName(
    "Base64Data",
    namespace = "urn:oasis:names:tc:dss:1.0:core:schema",
  )
  val base64Data: Base64Data? = null,
  @XmlElement(true)
  @XmlSerialName(
    "AttachmentReference",
    namespace = "urn:oasis:names:tc:dss:1.0:core:schema",
  )
  val attachmentReference: AttachmentReference? = null,
)

@Serializable
data class InlineXMLType(
  @XmlElement(false)
  @XmlSerialName("ignorePIs")
  val ignoreProcessingInstructions: Boolean? = null,
  @XmlElement(false)
  @XmlSerialName("ignoreComments")
  val ignoreComments: Boolean? = null,
  @XmlElement(true)
  val unknownContent: String? = null,
)

@Serializable
data class SchemasType(
  @XmlElement(true)
  @XmlSerialName(
    "Schema",
    namespace = "urn:oasis:names:tc:dss:1.0:core:schema",
  )
  val schema: List<Schema> = emptyList(),
)

@Serializable
data class RequestBaseType(
  @XmlElement(false)
  @XmlSerialName("RequestID")
  val requestId: String? = null,
  @XmlElement(false)
  @XmlSerialName("Profile")
  val profile: String? = null,
  @XmlElement(true)
  @XmlSerialName(
    "OptionalInputs",
    namespace = "urn:oasis:names:tc:dss:1.0:core:schema",
  )
  val optionalInputs: OptionalInputs? = null,
  @XmlElement(true)
  @XmlSerialName(
    "InputDocuments",
    namespace = "urn:oasis:names:tc:dss:1.0:core:schema",
  )
  val inputDocuments: InputDocuments? = null,
)

@Serializable
data class ResponseBaseType(
  @XmlElement(false)
  @XmlSerialName("RequestID")
  val requestId: String? = null,
  @XmlElement(false)
  @XmlSerialName("Profile")
  val profile: String,
  @XmlElement(true)
  @XmlSerialName(
    "Result",
    namespace = "urn:oasis:names:tc:dss:1.0:core:schema",
  )
  val result: Result,
  @XmlElement(true)
  @XmlSerialName(
    "OptionalOutputs",
    namespace = "urn:oasis:names:tc:dss:1.0:core:schema",
  )
  val optionalOutputs: OptionalOutputs? = null,
)

@Serializable
data class TimeSignatureInstructionType(
  @XmlElement(false)
  @XmlSerialName("Type")
  val type: String? = null,
  @XmlElement(false)
  @XmlSerialName("TimeStampTheGivenSignature")
  val timeStampTheGivenSignature: Boolean? = null,
  @XmlValue(true)
  val charData: String,
)

@Serializable
data class UpdateSignatureInstructionType(
  @XmlElement(false)
  @XmlSerialName("Type")
  val type: String? = null,
)

@Serializable
data class PropertiesType(
  @XmlElement(true)
  @XmlSerialName(
    "Property",
    namespace = "urn:oasis:names:tc:dss:1.0:core:schema",
  )
  val `property`: List<Property> = emptyList(),
)

@Serializable
data class VerifyManifestResultsType(
  @XmlElement(true)
  @XmlSerialName(
    "ManifestResult",
    namespace = "urn:oasis:names:tc:dss:1.0:core:schema",
  )
  val manifestResult: List<ManifestResult> = emptyList(),
)

@Serializable
data class UseVerificationTimeType(
  @XmlElement(true)
  @XmlSerialName(
    "CurrentTime",
    namespace = "urn:oasis:names:tc:dss:1.0:core:schema",
  )
  val currentTime: String? = null,
  @XmlElement(true)
  @XmlSerialName(
    "SpecificTime",
    namespace = "urn:oasis:names:tc:dss:1.0:core:schema",
  )
  val specificTime: String? = null,
  @XmlElement(true)
  val unknownContent: String? = null,
)

@Serializable
data class AdditionalTimeInfoType(
  @XmlElement(false)
  @XmlSerialName("Type")
  val type: String,
  @XmlElement(false)
  @XmlSerialName("Ref")
  val ref: String? = null,
  @XmlValue(true)
  val charData: String,
)

@Serializable
data class VerificationTimeInfoType(
  @XmlElement(true)
  @XmlSerialName(
    "VerificationTime",
    namespace = "urn:oasis:names:tc:dss:1.0:core:schema",
  )
  val verificationTime: String,
  @XmlElement(true)
  @XmlSerialName(
    "AdditionalTimeInfo",
    namespace = "urn:oasis:names:tc:dss:1.0:core:schema",
  )
  val additionalTimeInfo: List<AdditionalTimeInfo> = emptyList(),
)

@Serializable
data class DetailType(
  @XmlElement(false)
  @XmlSerialName("Type")
  val type: String,
  @XmlElement(true)
  @XmlSerialName(
    "Code",
    namespace = "urn:oasis:names:tc:dss:1.0:core:schema",
  )
  val code: String? = null,
  @XmlElement(true)
  @XmlSerialName(
    "Message",
    namespace = "urn:oasis:names:tc:dss:1.0:core:schema",
  )
  val message: InternationalStringType? = null,
  @XmlElement(true)
  val unknownContent: String? = null,
)

@Serializable
data class SigningTimeInfoType(
  @XmlElement(true)
  @XmlSerialName(
    "SigningTime",
    namespace = "urn:oasis:names:tc:dss:1.0:core:schema",
  )
  val signingTime: String,
  @XmlElement(true)
  @XmlSerialName(
    "SigningTimeBoundaries",
    namespace = "urn:oasis:names:tc:dss:1.0:core:schema",
  )
  val signingTimeBoundaries: SigningTimeInfoTypeSigningTimeBoundaries? = null,
)

@Serializable
data class UpdatedSignatureType(
  @XmlElement(false)
  @XmlSerialName("Type")
  val type: String? = null,
  @XmlElement(true)
  @XmlSerialName(
    "SignatureObject",
    namespace = "urn:oasis:names:tc:dss:1.0:core:schema",
  )
  val signatureObject: SignatureObject,
)

@Serializable
data class AttachmentReferenceType(
  @XmlElement(false)
  @XmlSerialName("AttRefURI")
  val attRefUri: String? = null,
  @XmlElement(false)
  @XmlSerialName("MimeType")
  val mimeType: String? = null,
  @XmlElement(true)
  @XmlSerialName(
    "DigestMethod",
    namespace = "http://www.w3.org/2000/09/xmldsig#",
  )
  val digestMethod: DigestMethod,
  @XmlElement(true)
  @XmlSerialName(
    "DigestValue",
    namespace = "http://www.w3.org/2000/09/xmldsig#",
  )
  val digestValue: String,
)

@Serializable
@XmlSerialName(
  "SigningTimeBoundaries",
  namespace = "urn:oasis:names:tc:dss:1.0:core:schema",
)
data class SigningTimeInfoTypeSigningTimeBoundaries(
  @XmlElement(true)
  @XmlSerialName("LowerBoundary")
  val lowerBoundary: String? = null,
  @XmlElement(true)
  @XmlSerialName("UpperBoundary")
  val upperBoundary: String? = null,
)
