// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.oasis.dss10core

import kotlin.collections.List
import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName

@Serializable
data class SchemasType(
  @XmlElement(true)
  @XmlSerialName(
    "Schema",
    namespace = "urn:oasis:names:tc:dss:1.0:core:schema",
  )
  val schema: List<Schema> = emptyList(),
)
