// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.oasis.dss10core

import kotlin.Boolean
import kotlin.String
import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName

@Serializable
@XmlSerialName(
  "SignaturePlacement",
  namespace = "urn:oasis:names:tc:dss:1.0:core:schema",
)
data class SignaturePlacement(
  @XmlElement(false)
  @XmlSerialName("WhichDocument")
  val whichDocument: String? = null,
  @XmlElement(false)
  @XmlSerialName("CreateEnvelopedSignature")
  val createEnvelopedSignature: Boolean? = null,
  @XmlElement(true)
  @XmlSerialName("XPathAfter")
  val xPathAfter: String? = null,
  @XmlElement(true)
  @XmlSerialName("XPathFirstChildOf")
  val xPathFirstChildOf: String? = null,
)
