// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.oasis.dss10core

import kotlin.String
import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName

@Serializable
@XmlSerialName(
  "SignaturePtr",
  namespace = "urn:oasis:names:tc:dss:1.0:core:schema",
)
data class SignaturePtr(
  @XmlElement(false)
  @XmlSerialName("WhichDocument")
  val whichDocument: String? = null,
  @XmlElement(false)
  @XmlSerialName("XPath")
  val xPath: String? = null,
)
