// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.oasis.dss10core

import kotlin.collections.List
import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName

@Serializable
@XmlSerialName(
  "SignedReferences",
  namespace = "urn:oasis:names:tc:dss:1.0:core:schema",
)
data class SignedReferences(
  @XmlElement(true)
  @XmlSerialName("SignedReference")
  val signedReference: List<SignedReference> = emptyList(),
)
