// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.oasis.dss10core

import kotlin.String
import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName

@Serializable
data class SigningTimeInfoType(
  @XmlElement(true)
  @XmlSerialName(
    "SigningTime",
    namespace = "urn:oasis:names:tc:dss:1.0:core:schema",
  )
  val signingTime: String,
  @XmlElement(true)
  @XmlSerialName(
    "SigningTimeBoundaries",
    namespace = "urn:oasis:names:tc:dss:1.0:core:schema",
  )
  val signingTimeBoundaries: SigningTimeInfoTypeSigningTimeBoundaries? = null,
)
