// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.oasis.dss10core

import kotlin.Boolean
import kotlin.String
import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName
import nl.adaptivity.xmlutil.serialization.XmlValue

@Serializable
data class TimeSignatureInstructionType(
  @XmlElement(false)
  @XmlSerialName("Type")
  val type: String? = null,
  @XmlElement(false)
  @XmlSerialName("TimeStampTheGivenSignature")
  val timeStampTheGivenSignature: Boolean? = null,
  @XmlValue(true)
  val charData: String,
)
