// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.oasis.dss10core

import de.gematik.connector.api.w3200009.xmldsig.Signature
import kotlin.String
import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName

@Serializable
@XmlSerialName(
  "Timestamp",
  namespace = "urn:oasis:names:tc:dss:1.0:core:schema",
)
data class Timestamp(
  @XmlElement(true)
  @XmlSerialName(
    "Signature",
    namespace = "http://www.w3.org/2000/09/xmldsig#",
  )
  val signature: Signature? = null,
  @XmlElement(true)
  @XmlSerialName("RFC3161TimeStampToken")
  val rfc3161TimeStampToken: String? = null,
  @XmlElement(true)
  @XmlSerialName("Other")
  val other: AnyType? = null,
)
