// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.oasis.dss10core

import de.gematik.connector.api.w3200009.xmldsig.Transforms
import kotlin.Int
import kotlin.String
import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName

@Serializable
@XmlSerialName(
  "TransformedData",
  namespace = "urn:oasis:names:tc:dss:1.0:core:schema",
)
data class TransformedData(
  @XmlElement(false)
  @XmlSerialName("ID")
  val id: String? = null,
  @XmlElement(false)
  @XmlSerialName("RefURI")
  val refUri: String? = null,
  @XmlElement(false)
  @XmlSerialName("RefType")
  val refType: String? = null,
  @XmlElement(false)
  @XmlSerialName("SchemaRefs")
  val schemaRefs: String? = null,
  @XmlElement(false)
  @XmlSerialName("WhichReference")
  val whichReference: Int? = null,
  @XmlElement(true)
  @XmlSerialName(
    "Transforms",
    namespace = "http://www.w3.org/2000/09/xmldsig#",
  )
  val transforms: Transforms? = null,
  @XmlElement(true)
  @XmlSerialName("Base64Data")
  val base64Data: Base64Data,
)
