// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.oasis.dss10core

import kotlin.Boolean
import kotlin.Int
import kotlin.String
import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName

@Serializable
@XmlSerialName(
  "TstInfo",
  namespace = "urn:oasis:names:tc:dss:1.0:core:schema",
)
data class TstInfo(
  @XmlElement(true)
  @XmlSerialName("SerialNumber")
  val serialNumber: Int,
  @XmlElement(true)
  @XmlSerialName("CreationTime")
  val creationTime: String,
  @XmlElement(true)
  @XmlSerialName("Policy")
  val policy: String? = null,
  @XmlElement(true)
  @XmlSerialName("ErrorBound")
  val errorBound: String? = null,
  @XmlElement(true)
  @XmlSerialName("Ordered")
  val ordered: Boolean? = null,
  @XmlElement(true)
  @XmlSerialName("TSA")
  val tsa: String? = null,
)
