// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.gematik.tel.error20

import kotlin.Int
import kotlin.String
import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName

@Serializable
@XmlSerialName(
  "Trace",
  namespace = "http://ws.gematik.de/tel/error/v2.0",
)
data class ErrorTrace(
  @XmlElement(true)
  @XmlSerialName("EventID")
  val eventId: String,
  @XmlElement(true)
  @XmlSerialName("Instance")
  val instance: String,
  @XmlElement(true)
  @XmlSerialName("LogReference")
  val logReference: String,
  @XmlElement(true)
  @XmlSerialName("CompType")
  val compType: String,
  @XmlElement(true)
  @XmlSerialName("Code")
  val code: Int,
  @XmlElement(true)
  @XmlSerialName("Severity")
  val severity: String,
  @XmlElement(true)
  @XmlSerialName("ErrorType")
  val errorType: String,
  @XmlElement(true)
  @XmlSerialName("ErrorText")
  val errorText: String,
  @XmlElement(true)
  @XmlSerialName("Detail")
  val detail: ErrorTraceDetail? = null,
)
