// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.gematik.tel.error20

import kotlin.String
import kotlin.collections.List
import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName

@Serializable
@XmlSerialName(
  "Error",
  namespace = "http://ws.gematik.de/tel/error/v2.0",
)
data class Error(
  @XmlElement(true)
  @XmlSerialName("MessageID")
  val messageId: String,
  @XmlElement(true)
  @XmlSerialName("Timestamp")
  val timestamp: String,
  @XmlElement(true)
  @XmlSerialName("Trace")
  val trace: List<ErrorTrace> = emptyList(),
)
