// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.gematik.tel.error20

import kotlin.String
import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName
import nl.adaptivity.xmlutil.serialization.XmlValue

@Serializable
@XmlSerialName(
  "Detail",
  namespace = "http://ws.gematik.de/tel/error/v2.0",
)
data class ErrorTraceDetail(
  @XmlElement(false)
  @XmlSerialName("Encoding")
  val encoding: String? = null,
  @XmlValue(true)
  val charData: String,
)
