// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.w3200009.xmldsig

import kotlin.String
import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName

@Serializable
data class CanonicalizationMethodType(
  @XmlElement(false)
  @XmlSerialName("Algorithm")
  val algorithm: String,
  @XmlElement(true)
  val unknownContent: String? = null,
)
