// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.w3200009.xmldsig

import kotlin.String
import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName

@Serializable
data class DSAKeyValueType(
  @XmlElement(true)
  @XmlSerialName(
    "P",
    namespace = "http://www.w3.org/2000/09/xmldsig#",
  )
  val p: String,
  @XmlElement(true)
  @XmlSerialName(
    "Q",
    namespace = "http://www.w3.org/2000/09/xmldsig#",
  )
  val q: String,
  @XmlElement(true)
  @XmlSerialName(
    "G",
    namespace = "http://www.w3.org/2000/09/xmldsig#",
  )
  val g: String? = null,
  @XmlElement(true)
  @XmlSerialName(
    "Y",
    namespace = "http://www.w3.org/2000/09/xmldsig#",
  )
  val y: String,
  @XmlElement(true)
  @XmlSerialName(
    "J",
    namespace = "http://www.w3.org/2000/09/xmldsig#",
  )
  val j: String? = null,
  @XmlElement(true)
  @XmlSerialName(
    "Seed",
    namespace = "http://www.w3.org/2000/09/xmldsig#",
  )
  val seed: String,
  @XmlElement(true)
  @XmlSerialName(
    "PgenCounter",
    namespace = "http://www.w3.org/2000/09/xmldsig#",
  )
  val pgenCounter: String,
)
