// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.w3200009.xmldsig

import kotlin.String
import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName

@Serializable
data class ObjectType(
  @XmlElement(false)
  @XmlSerialName("Id")
  val id: String? = null,
  @XmlElement(false)
  @XmlSerialName("MimeType")
  val mimeType: String? = null,
  @XmlElement(false)
  @XmlSerialName("Encoding")
  val encoding: String? = null,
  @XmlElement(true)
  val unknownContent: String? = null,
)
