// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.w3200009.xmldsig

import kotlin.String
import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName

@Serializable
data class ReferenceType(
  @XmlElement(false)
  @XmlSerialName("Id")
  val id: String? = null,
  @XmlElement(false)
  @XmlSerialName("URI")
  val uri: String? = null,
  @XmlElement(false)
  @XmlSerialName("Type")
  val type: String? = null,
  @XmlElement(true)
  @XmlSerialName(
    "Transforms",
    namespace = "http://www.w3.org/2000/09/xmldsig#",
  )
  val transforms: Transforms? = null,
  @XmlElement(true)
  @XmlSerialName(
    "DigestMethod",
    namespace = "http://www.w3.org/2000/09/xmldsig#",
  )
  val digestMethod: DigestMethod,
  @XmlElement(true)
  @XmlSerialName(
    "DigestValue",
    namespace = "http://www.w3.org/2000/09/xmldsig#",
  )
  val digestValue: String,
)
