// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.w3200009.xmldsig

import kotlin.String
import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName

@Serializable
@XmlSerialName(
  "Reference",
  namespace = "http://www.w3.org/2000/09/xmldsig#",
)
data class Reference(
  @XmlElement(false)
  @XmlSerialName("Id")
  val id: String? = null,
  @XmlElement(false)
  @XmlSerialName("URI")
  val uri: String? = null,
  @XmlElement(false)
  @XmlSerialName("Type")
  val type: String? = null,
  @XmlElement(true)
  @XmlSerialName("Transforms")
  val transforms: Transforms? = null,
  @XmlElement(true)
  @XmlSerialName("DigestMethod")
  val digestMethod: DigestMethod,
  @XmlElement(true)
  @XmlSerialName("DigestValue")
  val digestValue: String,
)
