// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.w3200009.xmldsig

import kotlin.Int
import kotlin.String
import kotlin.collections.List
import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName
import nl.adaptivity.xmlutil.serialization.XmlValue

@Serializable
@XmlSerialName(
  "Signature",
  namespace = "http://www.w3.org/2000/09/xmldsig#",
)
data class Signature(
  @XmlElement(false)
  @XmlSerialName("Id")
  val id: String? = null,
  @XmlElement(true)
  @XmlSerialName("SignedInfo")
  val signedInfo: SignedInfo,
  @XmlElement(true)
  @XmlSerialName("SignatureValue")
  val signatureValue: SignatureValue,
  @XmlElement(true)
  @XmlSerialName("KeyInfo")
  val keyInfo: KeyInfo? = null,
  @XmlElement(true)
  @XmlSerialName("Object")
  val `object`: List<Object> = emptyList(),
)

@Serializable
@XmlSerialName(
  "SignatureValue",
  namespace = "http://www.w3.org/2000/09/xmldsig#",
)
data class SignatureValue(
  @XmlElement(false)
  @XmlSerialName("Id")
  val id: String? = null,
  @XmlValue(true)
  val charData: String,
)

@Serializable
@XmlSerialName(
  "SignedInfo",
  namespace = "http://www.w3.org/2000/09/xmldsig#",
)
data class SignedInfo(
  @XmlElement(false)
  @XmlSerialName("Id")
  val id: String? = null,
  @XmlElement(true)
  @XmlSerialName("CanonicalizationMethod")
  val canonicalizationMethod: CanonicalizationMethod,
  @XmlElement(true)
  @XmlSerialName("SignatureMethod")
  val signatureMethod: SignatureMethod,
  @XmlElement(true)
  @XmlSerialName("Reference")
  val reference: List<Reference> = emptyList(),
)

@Serializable
@XmlSerialName(
  "CanonicalizationMethod",
  namespace = "http://www.w3.org/2000/09/xmldsig#",
)
data class CanonicalizationMethod(
  @XmlElement(false)
  @XmlSerialName("Algorithm")
  val algorithm: String,
  @XmlElement(true)
  val unknownContent: String? = null,
)

@Serializable
@XmlSerialName(
  "SignatureMethod",
  namespace = "http://www.w3.org/2000/09/xmldsig#",
)
data class SignatureMethod(
  @XmlElement(false)
  @XmlSerialName("Algorithm")
  val algorithm: String,
  @XmlElement(true)
  @XmlSerialName("HMACOutputLength")
  val hmacOutputLength: Int? = null,
  @XmlElement(true)
  val unknownContent: String? = null,
)

@Serializable
@XmlSerialName(
  "Reference",
  namespace = "http://www.w3.org/2000/09/xmldsig#",
)
data class Reference(
  @XmlElement(false)
  @XmlSerialName("Id")
  val id: String? = null,
  @XmlElement(false)
  @XmlSerialName("URI")
  val uri: String? = null,
  @XmlElement(false)
  @XmlSerialName("Type")
  val type: String? = null,
  @XmlElement(true)
  @XmlSerialName("Transforms")
  val transforms: Transforms? = null,
  @XmlElement(true)
  @XmlSerialName("DigestMethod")
  val digestMethod: DigestMethod,
  @XmlElement(true)
  @XmlSerialName("DigestValue")
  val digestValue: String,
)

@Serializable
@XmlSerialName(
  "Transforms",
  namespace = "http://www.w3.org/2000/09/xmldsig#",
)
data class Transforms(
  @XmlElement(true)
  @XmlSerialName("Transform")
  val transform: List<Transform> = emptyList(),
)

@Serializable
@XmlSerialName(
  "Transform",
  namespace = "http://www.w3.org/2000/09/xmldsig#",
)
data class Transform(
  @XmlElement(false)
  @XmlSerialName("Algorithm")
  val algorithm: String,
  @XmlElement(true)
  val unknownContent: String? = null,
  @XmlElement(true)
  @XmlSerialName("XPath")
  val xPath: List<String> = emptyList(),
)

@Serializable
@XmlSerialName(
  "DigestMethod",
  namespace = "http://www.w3.org/2000/09/xmldsig#",
)
data class DigestMethod(
  @XmlElement(false)
  @XmlSerialName("Algorithm")
  val algorithm: String,
  @XmlElement(true)
  val unknownContent: String? = null,
)

@Serializable
@XmlSerialName(
  "KeyInfo",
  namespace = "http://www.w3.org/2000/09/xmldsig#",
)
data class KeyInfo(
  @XmlElement(false)
  @XmlSerialName("Id")
  val id: String? = null,
  @XmlElement(true)
  @XmlSerialName("KeyName")
  val keyName: List<String> = emptyList(),
  @XmlElement(true)
  @XmlSerialName("KeyValue")
  val keyValue: List<KeyValue> = emptyList(),
  @XmlElement(true)
  @XmlSerialName("RetrievalMethod")
  val retrievalMethod: List<RetrievalMethod> = emptyList(),
  @XmlElement(true)
  @XmlSerialName("X509Data")
  val x509Data: List<X509Data> = emptyList(),
  @XmlElement(true)
  @XmlSerialName("PGPData")
  val pgpData: List<PGPData> = emptyList(),
  @XmlElement(true)
  @XmlSerialName("SPKIData")
  val spkiData: List<SPKIData> = emptyList(),
  @XmlElement(true)
  @XmlSerialName("MgmtData")
  val mgmtData: List<String> = emptyList(),
  @XmlElement(true)
  val unknownContent: String? = null,
)

@Serializable
@XmlSerialName(
  "KeyValue",
  namespace = "http://www.w3.org/2000/09/xmldsig#",
)
data class KeyValue(
  @XmlElement(true)
  @XmlSerialName("DSAKeyValue")
  val dsaKeyValue: DSAKeyValue? = null,
  @XmlElement(true)
  @XmlSerialName("RSAKeyValue")
  val rsaKeyValue: RSAKeyValue? = null,
  @XmlElement(true)
  val unknownContent: String? = null,
)

@Serializable
@XmlSerialName(
  "RetrievalMethod",
  namespace = "http://www.w3.org/2000/09/xmldsig#",
)
data class RetrievalMethod(
  @XmlElement(false)
  @XmlSerialName("URI")
  val uri: String? = null,
  @XmlElement(false)
  @XmlSerialName("Type")
  val type: String? = null,
  @XmlElement(true)
  @XmlSerialName("Transforms")
  val transforms: Transforms? = null,
)

@Serializable
@XmlSerialName(
  "X509Data",
  namespace = "http://www.w3.org/2000/09/xmldsig#",
)
data class X509Data(
  @XmlElement(true)
  @XmlSerialName("X509IssuerSerial")
  val x509IssuerSerial: X509IssuerSerialType? = null,
  @XmlElement(true)
  @XmlSerialName("X509SKI")
  val x509Ski: String? = null,
  @XmlElement(true)
  @XmlSerialName("X509SubjectName")
  val x509SubjectName: String? = null,
  @XmlElement(true)
  @XmlSerialName("X509Certificate")
  val x509Certificate: String? = null,
  @XmlElement(true)
  @XmlSerialName("X509CRL")
  val x509Crl: String? = null,
  @XmlElement(true)
  val unknownContent: String? = null,
)

@Serializable
@XmlSerialName(
  "PGPData",
  namespace = "http://www.w3.org/2000/09/xmldsig#",
)
data class PGPData(
  @XmlElement(true)
  @XmlSerialName("PGPKeyID")
  val pgpKeyId: String,
  @XmlElement(true)
  @XmlSerialName("PGPKeyPacket")
  val pgpKeyPacket: String? = null,
  @XmlElement(true)
  val unknownContent: String? = null,
)

@Serializable
@XmlSerialName(
  "SPKIData",
  namespace = "http://www.w3.org/2000/09/xmldsig#",
)
data class SPKIData(
  @XmlElement(true)
  @XmlSerialName("SPKISexp")
  val spkiSexp: List<String> = emptyList(),
  @XmlElement(true)
  val unknownContent: String? = null,
)

@Serializable
@XmlSerialName(
  "Object",
  namespace = "http://www.w3.org/2000/09/xmldsig#",
)
data class Object(
  @XmlElement(false)
  @XmlSerialName("Id")
  val id: String? = null,
  @XmlElement(false)
  @XmlSerialName("MimeType")
  val mimeType: String? = null,
  @XmlElement(false)
  @XmlSerialName("Encoding")
  val encoding: String? = null,
  @XmlElement(true)
  val unknownContent: String? = null,
)

@Serializable
@XmlSerialName(
  "Manifest",
  namespace = "http://www.w3.org/2000/09/xmldsig#",
)
data class Manifest(
  @XmlElement(false)
  @XmlSerialName("Id")
  val id: String? = null,
  @XmlElement(true)
  @XmlSerialName("Reference")
  val reference: List<Reference> = emptyList(),
)

@Serializable
@XmlSerialName(
  "SignatureProperties",
  namespace = "http://www.w3.org/2000/09/xmldsig#",
)
data class SignatureProperties(
  @XmlElement(false)
  @XmlSerialName("Id")
  val id: String? = null,
  @XmlElement(true)
  @XmlSerialName("SignatureProperty")
  val signatureProperty: List<SignatureProperty> = emptyList(),
)

@Serializable
@XmlSerialName(
  "SignatureProperty",
  namespace = "http://www.w3.org/2000/09/xmldsig#",
)
data class SignatureProperty(
  @XmlElement(false)
  @XmlSerialName("Target")
  val target: String,
  @XmlElement(false)
  @XmlSerialName("Id")
  val id: String? = null,
  @XmlElement(true)
  val unknownContent: String? = null,
)

@Serializable
@XmlSerialName(
  "DSAKeyValue",
  namespace = "http://www.w3.org/2000/09/xmldsig#",
)
data class DSAKeyValue(
  @XmlElement(true)
  @XmlSerialName("P")
  val p: String,
  @XmlElement(true)
  @XmlSerialName("Q")
  val q: String,
  @XmlElement(true)
  @XmlSerialName("G")
  val g: String? = null,
  @XmlElement(true)
  @XmlSerialName("Y")
  val y: String,
  @XmlElement(true)
  @XmlSerialName("J")
  val j: String? = null,
  @XmlElement(true)
  @XmlSerialName("Seed")
  val seed: String,
  @XmlElement(true)
  @XmlSerialName("PgenCounter")
  val pgenCounter: String,
)

@Serializable
@XmlSerialName(
  "RSAKeyValue",
  namespace = "http://www.w3.org/2000/09/xmldsig#",
)
data class RSAKeyValue(
  @XmlElement(true)
  @XmlSerialName("Modulus")
  val modulus: String,
  @XmlElement(true)
  @XmlSerialName("Exponent")
  val exponent: String,
)

@Serializable
data class SignatureType(
  @XmlElement(false)
  @XmlSerialName("Id")
  val id: String? = null,
  @XmlElement(true)
  @XmlSerialName(
    "SignedInfo",
    namespace = "http://www.w3.org/2000/09/xmldsig#",
  )
  val signedInfo: SignedInfo,
  @XmlElement(true)
  @XmlSerialName(
    "SignatureValue",
    namespace = "http://www.w3.org/2000/09/xmldsig#",
  )
  val signatureValue: SignatureValue,
  @XmlElement(true)
  @XmlSerialName(
    "KeyInfo",
    namespace = "http://www.w3.org/2000/09/xmldsig#",
  )
  val keyInfo: KeyInfo? = null,
  @XmlElement(true)
  @XmlSerialName(
    "Object",
    namespace = "http://www.w3.org/2000/09/xmldsig#",
  )
  val `object`: List<Object> = emptyList(),
)

@Serializable
data class SignatureValueType(
  @XmlElement(false)
  @XmlSerialName("Id")
  val id: String? = null,
  @XmlValue(true)
  val charData: String,
)

@Serializable
data class SignedInfoType(
  @XmlElement(false)
  @XmlSerialName("Id")
  val id: String? = null,
  @XmlElement(true)
  @XmlSerialName(
    "CanonicalizationMethod",
    namespace = "http://www.w3.org/2000/09/xmldsig#",
  )
  val canonicalizationMethod: CanonicalizationMethod,
  @XmlElement(true)
  @XmlSerialName(
    "SignatureMethod",
    namespace = "http://www.w3.org/2000/09/xmldsig#",
  )
  val signatureMethod: SignatureMethod,
  @XmlElement(true)
  @XmlSerialName(
    "Reference",
    namespace = "http://www.w3.org/2000/09/xmldsig#",
  )
  val reference: List<Reference> = emptyList(),
)

@Serializable
data class CanonicalizationMethodType(
  @XmlElement(false)
  @XmlSerialName("Algorithm")
  val algorithm: String,
  @XmlElement(true)
  val unknownContent: String? = null,
)

@Serializable
data class SignatureMethodType(
  @XmlElement(false)
  @XmlSerialName("Algorithm")
  val algorithm: String,
  @XmlElement(true)
  @XmlSerialName(
    "HMACOutputLength",
    namespace = "http://www.w3.org/2000/09/xmldsig#",
  )
  val hmacOutputLength: Int? = null,
  @XmlElement(true)
  val unknownContent: String? = null,
)

@Serializable
data class ReferenceType(
  @XmlElement(false)
  @XmlSerialName("Id")
  val id: String? = null,
  @XmlElement(false)
  @XmlSerialName("URI")
  val uri: String? = null,
  @XmlElement(false)
  @XmlSerialName("Type")
  val type: String? = null,
  @XmlElement(true)
  @XmlSerialName(
    "Transforms",
    namespace = "http://www.w3.org/2000/09/xmldsig#",
  )
  val transforms: Transforms? = null,
  @XmlElement(true)
  @XmlSerialName(
    "DigestMethod",
    namespace = "http://www.w3.org/2000/09/xmldsig#",
  )
  val digestMethod: DigestMethod,
  @XmlElement(true)
  @XmlSerialName(
    "DigestValue",
    namespace = "http://www.w3.org/2000/09/xmldsig#",
  )
  val digestValue: String,
)

@Serializable
data class TransformsType(
  @XmlElement(true)
  @XmlSerialName(
    "Transform",
    namespace = "http://www.w3.org/2000/09/xmldsig#",
  )
  val transform: List<Transform> = emptyList(),
)

@Serializable
data class TransformType(
  @XmlElement(false)
  @XmlSerialName("Algorithm")
  val algorithm: String,
  @XmlElement(true)
  val unknownContent: String? = null,
  @XmlElement(true)
  @XmlSerialName(
    "XPath",
    namespace = "http://www.w3.org/2000/09/xmldsig#",
  )
  val xPath: List<String> = emptyList(),
)

@Serializable
data class DigestMethodType(
  @XmlElement(false)
  @XmlSerialName("Algorithm")
  val algorithm: String,
  @XmlElement(true)
  val unknownContent: String? = null,
)

@Serializable
data class KeyInfoType(
  @XmlElement(false)
  @XmlSerialName("Id")
  val id: String? = null,
  @XmlElement(true)
  @XmlSerialName(
    "KeyName",
    namespace = "http://www.w3.org/2000/09/xmldsig#",
  )
  val keyName: List<String> = emptyList(),
  @XmlElement(true)
  @XmlSerialName(
    "KeyValue",
    namespace = "http://www.w3.org/2000/09/xmldsig#",
  )
  val keyValue: List<KeyValue> = emptyList(),
  @XmlElement(true)
  @XmlSerialName(
    "RetrievalMethod",
    namespace = "http://www.w3.org/2000/09/xmldsig#",
  )
  val retrievalMethod: List<RetrievalMethod> = emptyList(),
  @XmlElement(true)
  @XmlSerialName(
    "X509Data",
    namespace = "http://www.w3.org/2000/09/xmldsig#",
  )
  val x509Data: List<X509Data> = emptyList(),
  @XmlElement(true)
  @XmlSerialName(
    "PGPData",
    namespace = "http://www.w3.org/2000/09/xmldsig#",
  )
  val pgpData: List<PGPData> = emptyList(),
  @XmlElement(true)
  @XmlSerialName(
    "SPKIData",
    namespace = "http://www.w3.org/2000/09/xmldsig#",
  )
  val spkiData: List<SPKIData> = emptyList(),
  @XmlElement(true)
  @XmlSerialName(
    "MgmtData",
    namespace = "http://www.w3.org/2000/09/xmldsig#",
  )
  val mgmtData: List<String> = emptyList(),
  @XmlElement(true)
  val unknownContent: String? = null,
)

@Serializable
data class KeyValueType(
  @XmlElement(true)
  @XmlSerialName(
    "DSAKeyValue",
    namespace = "http://www.w3.org/2000/09/xmldsig#",
  )
  val dsaKeyValue: DSAKeyValue? = null,
  @XmlElement(true)
  @XmlSerialName(
    "RSAKeyValue",
    namespace = "http://www.w3.org/2000/09/xmldsig#",
  )
  val rsaKeyValue: RSAKeyValue? = null,
  @XmlElement(true)
  val unknownContent: String? = null,
)

@Serializable
data class RetrievalMethodType(
  @XmlElement(false)
  @XmlSerialName("URI")
  val uri: String? = null,
  @XmlElement(false)
  @XmlSerialName("Type")
  val type: String? = null,
  @XmlElement(true)
  @XmlSerialName(
    "Transforms",
    namespace = "http://www.w3.org/2000/09/xmldsig#",
  )
  val transforms: Transforms? = null,
)

@Serializable
data class X509DataType(
  @XmlElement(true)
  @XmlSerialName(
    "X509IssuerSerial",
    namespace = "http://www.w3.org/2000/09/xmldsig#",
  )
  val x509IssuerSerial: X509IssuerSerialType? = null,
  @XmlElement(true)
  @XmlSerialName(
    "X509SKI",
    namespace = "http://www.w3.org/2000/09/xmldsig#",
  )
  val x509Ski: String? = null,
  @XmlElement(true)
  @XmlSerialName(
    "X509SubjectName",
    namespace = "http://www.w3.org/2000/09/xmldsig#",
  )
  val x509SubjectName: String? = null,
  @XmlElement(true)
  @XmlSerialName(
    "X509Certificate",
    namespace = "http://www.w3.org/2000/09/xmldsig#",
  )
  val x509Certificate: String? = null,
  @XmlElement(true)
  @XmlSerialName(
    "X509CRL",
    namespace = "http://www.w3.org/2000/09/xmldsig#",
  )
  val x509Crl: String? = null,
  @XmlElement(true)
  val unknownContent: String? = null,
)

@Serializable
data class X509IssuerSerialType(
  @XmlElement(true)
  @XmlSerialName(
    "X509IssuerName",
    namespace = "http://www.w3.org/2000/09/xmldsig#",
  )
  val x509IssuerName: String,
  @XmlElement(true)
  @XmlSerialName(
    "X509SerialNumber",
    namespace = "http://www.w3.org/2000/09/xmldsig#",
  )
  val x509SerialNumber: Int,
)

@Serializable
data class PGPDataType(
  @XmlElement(true)
  @XmlSerialName(
    "PGPKeyID",
    namespace = "http://www.w3.org/2000/09/xmldsig#",
  )
  val pgpKeyId: String,
  @XmlElement(true)
  @XmlSerialName(
    "PGPKeyPacket",
    namespace = "http://www.w3.org/2000/09/xmldsig#",
  )
  val pgpKeyPacket: String? = null,
  @XmlElement(true)
  val unknownContent: String? = null,
)

@Serializable
data class SPKIDataType(
  @XmlElement(true)
  @XmlSerialName(
    "SPKISexp",
    namespace = "http://www.w3.org/2000/09/xmldsig#",
  )
  val spkiSexp: List<String> = emptyList(),
  @XmlElement(true)
  val unknownContent: String? = null,
)

@Serializable
data class ObjectType(
  @XmlElement(false)
  @XmlSerialName("Id")
  val id: String? = null,
  @XmlElement(false)
  @XmlSerialName("MimeType")
  val mimeType: String? = null,
  @XmlElement(false)
  @XmlSerialName("Encoding")
  val encoding: String? = null,
  @XmlElement(true)
  val unknownContent: String? = null,
)

@Serializable
data class ManifestType(
  @XmlElement(false)
  @XmlSerialName("Id")
  val id: String? = null,
  @XmlElement(true)
  @XmlSerialName(
    "Reference",
    namespace = "http://www.w3.org/2000/09/xmldsig#",
  )
  val reference: List<Reference> = emptyList(),
)

@Serializable
data class SignaturePropertiesType(
  @XmlElement(false)
  @XmlSerialName("Id")
  val id: String? = null,
  @XmlElement(true)
  @XmlSerialName(
    "SignatureProperty",
    namespace = "http://www.w3.org/2000/09/xmldsig#",
  )
  val signatureProperty: List<SignatureProperty> = emptyList(),
)

@Serializable
data class SignaturePropertyType(
  @XmlElement(false)
  @XmlSerialName("Target")
  val target: String,
  @XmlElement(false)
  @XmlSerialName("Id")
  val id: String? = null,
  @XmlElement(true)
  val unknownContent: String? = null,
)

@Serializable
data class DSAKeyValueType(
  @XmlElement(true)
  @XmlSerialName(
    "P",
    namespace = "http://www.w3.org/2000/09/xmldsig#",
  )
  val p: String,
  @XmlElement(true)
  @XmlSerialName(
    "Q",
    namespace = "http://www.w3.org/2000/09/xmldsig#",
  )
  val q: String,
  @XmlElement(true)
  @XmlSerialName(
    "G",
    namespace = "http://www.w3.org/2000/09/xmldsig#",
  )
  val g: String? = null,
  @XmlElement(true)
  @XmlSerialName(
    "Y",
    namespace = "http://www.w3.org/2000/09/xmldsig#",
  )
  val y: String,
  @XmlElement(true)
  @XmlSerialName(
    "J",
    namespace = "http://www.w3.org/2000/09/xmldsig#",
  )
  val j: String? = null,
  @XmlElement(true)
  @XmlSerialName(
    "Seed",
    namespace = "http://www.w3.org/2000/09/xmldsig#",
  )
  val seed: String,
  @XmlElement(true)
  @XmlSerialName(
    "PgenCounter",
    namespace = "http://www.w3.org/2000/09/xmldsig#",
  )
  val pgenCounter: String,
)

@Serializable
data class RSAKeyValueType(
  @XmlElement(true)
  @XmlSerialName(
    "Modulus",
    namespace = "http://www.w3.org/2000/09/xmldsig#",
  )
  val modulus: String,
  @XmlElement(true)
  @XmlSerialName(
    "Exponent",
    namespace = "http://www.w3.org/2000/09/xmldsig#",
  )
  val exponent: String,
)
