// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.w3200009.xmldsig

import kotlin.String
import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName

@Serializable
@XmlSerialName(
  "SignatureProperty",
  namespace = "http://www.w3.org/2000/09/xmldsig#",
)
data class SignatureProperty(
  @XmlElement(false)
  @XmlSerialName("Target")
  val target: String,
  @XmlElement(false)
  @XmlSerialName("Id")
  val id: String? = null,
  @XmlElement(true)
  val unknownContent: String? = null,
)
