// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.w3200009.xmldsig

import kotlin.String
import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName
import nl.adaptivity.xmlutil.serialization.XmlValue

@Serializable
data class SignatureValueType(
  @XmlElement(false)
  @XmlSerialName("Id")
  val id: String? = null,
  @XmlValue(true)
  val charData: String,
)
