// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.w3200009.xmldsig

import kotlin.Int
import kotlin.String
import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName

@Serializable
data class SignatureMethodType(
  @XmlElement(false)
  @XmlSerialName("Algorithm")
  val algorithm: String,
  @XmlElement(true)
  @XmlSerialName(
    "HMACOutputLength",
    namespace = "http://www.w3.org/2000/09/xmldsig#",
  )
  val hmacOutputLength: Int? = null,
  @XmlElement(true)
  val unknownContent: String? = null,
)
