// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.w3200009.xmldsig

import kotlin.String
import kotlin.collections.List
import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName

@Serializable
data class SignatureType(
  @XmlElement(false)
  @XmlSerialName("Id")
  val id: String? = null,
  @XmlElement(true)
  @XmlSerialName(
    "SignedInfo",
    namespace = "http://www.w3.org/2000/09/xmldsig#",
  )
  val signedInfo: SignedInfo,
  @XmlElement(true)
  @XmlSerialName(
    "SignatureValue",
    namespace = "http://www.w3.org/2000/09/xmldsig#",
  )
  val signatureValue: SignatureValue,
  @XmlElement(true)
  @XmlSerialName(
    "KeyInfo",
    namespace = "http://www.w3.org/2000/09/xmldsig#",
  )
  val keyInfo: KeyInfo? = null,
  @XmlElement(true)
  @XmlSerialName(
    "Object",
    namespace = "http://www.w3.org/2000/09/xmldsig#",
  )
  val `object`: List<Object> = emptyList(),
)
