// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.w3200009.xmldsig

import kotlin.String
import kotlin.collections.List
import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName

@Serializable
@XmlSerialName(
  "SPKIData",
  namespace = "http://www.w3.org/2000/09/xmldsig#",
)
data class SPKIData(
  @XmlElement(true)
  @XmlSerialName("SPKISexp")
  val spkiSexp: List<String> = emptyList(),
  @XmlElement(true)
  val unknownContent: String? = null,
)
