// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.w3200009.xmldsig

import kotlin.String
import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName

@Serializable
@XmlSerialName(
  "X509Data",
  namespace = "http://www.w3.org/2000/09/xmldsig#",
)
data class X509Data(
  @XmlElement(true)
  @XmlSerialName("X509IssuerSerial")
  val x509IssuerSerial: X509IssuerSerialType? = null,
  @XmlElement(true)
  @XmlSerialName("X509SKI")
  val x509Ski: String? = null,
  @XmlElement(true)
  @XmlSerialName("X509SubjectName")
  val x509SubjectName: String? = null,
  @XmlElement(true)
  @XmlSerialName("X509Certificate")
  val x509Certificate: String? = null,
  @XmlElement(true)
  @XmlSerialName("X509CRL")
  val x509Crl: String? = null,
  @XmlElement(true)
  val unknownContent: String? = null,
)
