// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.w3200009.xmldsig

import kotlin.Int
import kotlin.String
import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName

@Serializable
data class X509IssuerSerialType(
  @XmlElement(true)
  @XmlSerialName(
    "X509IssuerName",
    namespace = "http://www.w3.org/2000/09/xmldsig#",
  )
  val x509IssuerName: String,
  @XmlElement(true)
  @XmlSerialName(
    "X509SerialNumber",
    namespace = "http://www.w3.org/2000/09/xmldsig#",
  )
  val x509SerialNumber: Int,
)
