// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.gematik.conn.certificateservice601

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
enum class CryptType {
  @SerialName("RSA")
  Rsa,
  @SerialName("ECC")
  Ecc,
}
