// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.gematik.conn.certificateservice601

import de.gematik.connector.api.soap.SoapOperation

object Operations {
  val CheckCertificateExpiration: SoapOperation =
      SoapOperation("CheckCertificateExpiration", "http://ws.gematik.de/conn/CertificateService/v6.0#CheckCertificateExpiration", "soap11")

  val ReadCardCertificate: SoapOperation =
      SoapOperation("ReadCardCertificate", "http://ws.gematik.de/conn/CertificateService/v6.0#ReadCardCertificate", "soap11")

  val VerifyCertificate: SoapOperation =
      SoapOperation("VerifyCertificate", "http://ws.gematik.de/conn/CertificateService/v6.0#VerifyCertificate", "soap11")
}
