// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.gematik.conn.certificateservice601

import kotlin.String
import kotlin.collections.List
import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName

@Serializable
@XmlSerialName(
  "RoleList",
  namespace = "http://ws.gematik.de/conn/CertificateService/v6.0",
)
data class VerifyCertificateResponseRoleList(
  @XmlElement(true)
  @XmlSerialName("Role")
  val role: List<String> = emptyList(),
)
