// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.gematik.conn.certificateservice601

import de.gematik.connector.api.gematik.tel.error20.Error
import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName

@Serializable
@XmlSerialName(
  "VerificationStatus",
  namespace = "http://ws.gematik.de/conn/CertificateService/v6.0",
)
data class VerifyCertificateResponseVerificationStatus(
  @XmlElement(true)
  @XmlSerialName("VerificationResult")
  val verificationResult: VerificationResultType,
  @XmlElement(true)
  @XmlSerialName(
    "Error",
    namespace = "http://ws.gematik.de/tel/error/v2.0",
  )
  val error: Error? = null,
)
