// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.oasis.dssx10profiles.verificationreport

import de.gematik.connector.api.oasis.dss10core.AnyType
import kotlin.String
import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName

@Serializable
data class AlgorithmValidityType(
  @XmlElement(true)
  @XmlSerialName(
    "Algorithm",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val algorithm: String,
  @XmlElement(true)
  @XmlSerialName(
    "Parameters",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val parameters: AnyType? = null,
  @XmlElement(true)
  @XmlSerialName(
    "Suitability",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val suitability: VerificationResultType? = null,
)
