// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.oasis.dssx10profiles.verificationreport

import kotlin.String
import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName

@Serializable
data class ArchiveTimeStampValidityType(
  @XmlElement(false)
  @XmlSerialName("Id")
  val id: String? = null,
  @XmlElement(true)
  @XmlSerialName(
    "FormatOK",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val formatOk: VerificationResultType,
  @XmlElement(true)
  @XmlSerialName(
    "DigestAlgorithm",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val digestAlgorithm: AlgorithmValidityType? = null,
  @XmlElement(true)
  @XmlSerialName(
    "Attributes",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val attributes: ArchiveTimeStampValidityTypeAttributes? = null,
  @XmlElement(true)
  @XmlSerialName(
    "ReducedHashTree",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val reducedHashTree: ArchiveTimeStampValidityTypeReducedHashTree? = null,
  @XmlElement(true)
  @XmlSerialName(
    "TimeStamp",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val timeStamp: TimeStampValidityType,
)
