// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.oasis.dssx10profiles.verificationreport

import kotlin.Int
import kotlin.String
import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName

@Serializable
data class AttributeCertificateContentType(
  @XmlElement(true)
  @XmlSerialName(
    "Version",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val version: Int? = null,
  @XmlElement(true)
  @XmlSerialName(
    "Holder",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val holder: EntityType,
  @XmlElement(true)
  @XmlSerialName(
    "Issuer",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val issuer: EntityType,
  @XmlElement(true)
  @XmlSerialName(
    "SignatureAlgorithm",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val signatureAlgorithm: String,
  @XmlElement(true)
  @XmlSerialName(
    "SerialNumber",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val serialNumber: Int,
  @XmlElement(true)
  @XmlSerialName(
    "AttCertValidityPeriod",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val attCertValidityPeriod: ValidityPeriodType,
  @XmlElement(true)
  @XmlSerialName(
    "Attributes",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val attributes: AttributeCertificateContentTypeAttributes,
  @XmlElement(true)
  @XmlSerialName(
    "IssuerUniqueID",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val issuerUniqueId: String? = null,
  @XmlElement(true)
  @XmlSerialName(
    "Extensions",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val extensions: ExtensionsType? = null,
)
