// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.oasis.dssx10profiles.verificationreport

import de.gematik.connector.api.w3200009.xmldsig.X509IssuerSerialType
import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName

@Serializable
data class CertificatePathValidityType(
  @XmlElement(true)
  @XmlSerialName(
    "PathValiditySummary",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val pathValiditySummary: VerificationResultType,
  @XmlElement(true)
  @XmlSerialName(
    "CertificateIdentifier",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val certificateIdentifier: X509IssuerSerialType,
  @XmlElement(true)
  @XmlSerialName(
    "PathValidityDetail",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val pathValidityDetail: CertificatePathValidityVerificationDetailType? = null,
)
