// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.oasis.dssx10profiles.verificationreport

import kotlin.collections.List
import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName

@Serializable
data class CertificatePathValidityVerificationDetailType(
  @XmlElement(true)
  @XmlSerialName(
    "CertificateValidity",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val certificateValidity: List<CertificateValidityType> = emptyList(),
  @XmlElement(true)
  @XmlSerialName(
    "TSLValidity",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val tslValidity: TrustStatusListValidityType? = null,
  @XmlElement(true)
  @XmlSerialName(
    "TrustAnchor",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val trustAnchor: VerificationResultType,
)
