// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.oasis.dssx10profiles.verificationreport

import kotlin.Int
import kotlin.String
import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName

@Serializable
data class CertificateContentType(
  @XmlElement(true)
  @XmlSerialName(
    "Version",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val version: Int? = null,
  @XmlElement(true)
  @XmlSerialName(
    "SerialNumber",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val serialNumber: Int,
  @XmlElement(true)
  @XmlSerialName(
    "SignatureAlgorithm",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val signatureAlgorithm: String,
  @XmlElement(true)
  @XmlSerialName(
    "Issuer",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val issuer: String,
  @XmlElement(true)
  @XmlSerialName(
    "ValidityPeriod",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val validityPeriod: ValidityPeriodType,
  @XmlElement(true)
  @XmlSerialName(
    "Subject",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val subject: String,
  @XmlElement(true)
  @XmlSerialName(
    "Extensions",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val extensions: ExtensionsType? = null,
)
