// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.oasis.dssx10profiles.verificationreport

import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName

@Serializable
data class CertificateStatusType(
  @XmlElement(true)
  @XmlSerialName(
    "CertStatusOK",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val certStatusOk: VerificationResultType,
  @XmlElement(true)
  @XmlSerialName(
    "RevocationInfo",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val revocationInfo: CertificateStatusTypeRevocationInfo? = null,
  @XmlElement(true)
  @XmlSerialName(
    "RevocationEvidence",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val revocationEvidence: CertificateStatusTypeRevocationEvidence? = null,
)
