// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.oasis.dssx10profiles.verificationreport

import kotlin.Int
import kotlin.String
import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName

@Serializable
data class CRLContentType(
  @XmlElement(true)
  @XmlSerialName(
    "Version",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val version: Int? = null,
  @XmlElement(true)
  @XmlSerialName(
    "Signature",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val signature: VerificationResultType,
  @XmlElement(true)
  @XmlSerialName(
    "Issuer",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val issuer: String,
  @XmlElement(true)
  @XmlSerialName(
    "ThisUpdate",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val thisUpdate: String,
  @XmlElement(true)
  @XmlSerialName(
    "NextUpdate",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val nextUpdate: String? = null,
  @XmlElement(true)
  @XmlSerialName(
    "RevokedCertificates",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val revokedCertificates: CRLContentTypeRevokedCertificates? = null,
  @XmlElement(true)
  @XmlSerialName(
    "CrlExtensions",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val crlExtensions: ExtensionsType? = null,
)
