// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.oasis.dssx10profiles.verificationreport

import kotlin.Int
import kotlin.String
import kotlin.collections.List
import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName

@Serializable
@XmlSerialName(
  "RevokedCertificates",
  namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
)
data class CRLContentTypeRevokedCertificates(
  @XmlElement(true)
  @XmlSerialName("UserCertificate")
  val userCertificate: List<Int> = emptyList(),
  @XmlElement(true)
  @XmlSerialName("RevocationDate")
  val revocationDate: List<String> = emptyList(),
  @XmlElement(true)
  @XmlSerialName("CrlEntryExtensions")
  val crlEntryExtensions: List<ExtensionsType> = emptyList(),
)
