// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.oasis.dssx10profiles.verificationreport

import de.gematik.connector.api.etsi01903132.CRLIdentifierType
import kotlin.String
import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName

@Serializable
data class CRLValidityType(
  @XmlElement(false)
  @XmlSerialName("Id")
  val id: String? = null,
  @XmlElement(true)
  @XmlSerialName(
    "CRLIdentifier",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val crlIdentifier: CRLIdentifierType,
  @XmlElement(true)
  @XmlSerialName(
    "CRLValue",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val crlValue: String? = null,
  @XmlElement(true)
  @XmlSerialName(
    "CRLContent",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val crlContent: CRLContentType? = null,
  @XmlElement(true)
  @XmlSerialName(
    "SignatureOK",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val signatureOk: SignatureValidityType,
  @XmlElement(true)
  @XmlSerialName(
    "CertificatePathValidity",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val certificatePathValidity: CertificatePathValidityType,
)
