// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.oasis.dssx10profiles.verificationreport

import de.gematik.connector.api.oasis.dss10core.AnyType
import de.gematik.connector.api.w3200009.xmldsig.X509IssuerSerialType
import kotlin.String
import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName

@Serializable
data class EntityType(
  @XmlElement(true)
  @XmlSerialName(
    "BaseCertificateID",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val baseCertificateId: X509IssuerSerialType? = null,
  @XmlElement(true)
  @XmlSerialName(
    "Name",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val name: String? = null,
  @XmlElement(true)
  @XmlSerialName(
    "Other",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val other: AnyType? = null,
)
