// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.oasis.dssx10profiles.verificationreport

import kotlin.collections.List
import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName

@Serializable
@XmlSerialName(
  "ArchiveTimeStampSequence",
  namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
)
data class EvidenceRecordValidityTypeArchiveTimeStampSequence(
  @XmlElement(true)
  @XmlSerialName("ArchiveTimeStampChain")
  val archiveTimeStampChain:
      List<EvidenceRecordValidityTypeArchiveTimeStampSequenceArchiveTimeStampChain> = emptyList(),
)
