// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.oasis.dssx10profiles.verificationreport

import de.gematik.connector.api.oasis.dss10core.AnyType
import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName

@Serializable
@XmlSerialName(
  "EncryptionInfo",
  namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
)
data class EvidenceRecordValidityTypeEncryptionInfo(
  @XmlElement(true)
  @XmlSerialName("EncryptionInfoType")
  val encryptionInfoType: AlgorithmValidityType,
  @XmlElement(true)
  @XmlSerialName("EncryptionInfoValue")
  val encryptionInfoValue: AnyType,
)
