// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.oasis.dssx10profiles.verificationreport

import kotlin.Int
import kotlin.String
import kotlin.collections.List
import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName

@Serializable
data class EvidenceRecordValidityType(
  @XmlElement(false)
  @XmlSerialName("Id")
  val id: String? = null,
  @XmlElement(true)
  @XmlSerialName(
    "FormatOK",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val formatOk: VerificationResultType,
  @XmlElement(true)
  @XmlSerialName(
    "Version",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val version: Int? = null,
  @XmlElement(true)
  @XmlSerialName(
    "DigestAlgorithm",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val digestAlgorithm: List<AlgorithmValidityType> = emptyList(),
  @XmlElement(true)
  @XmlSerialName(
    "CryptoInfos",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val cryptoInfos: EvidenceRecordValidityTypeCryptoInfos? = null,
  @XmlElement(true)
  @XmlSerialName(
    "EncryptionInfo",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val encryptionInfo: EvidenceRecordValidityTypeEncryptionInfo? = null,
  @XmlElement(true)
  @XmlSerialName(
    "ArchiveTimeStampSequence",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val archiveTimeStampSequence: EvidenceRecordValidityTypeArchiveTimeStampSequence,
)
