// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.oasis.dssx10profiles.verificationreport

import de.gematik.connector.api.oasis.dss10core.AnyType
import de.gematik.connector.api.w3200009.xmldsig.X509Data
import kotlin.String
import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName

@Serializable
data class IdentifierType(
  @XmlElement(true)
  @XmlSerialName(
    "X509Data",
    namespace = "http://www.w3.org/2000/09/xmldsig#",
  )
  val x509Data: X509Data? = null,
  @XmlElement(true)
  @XmlSerialName(
    "SAMLv1Identifier",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val samLv1Identifier: String? = null,
  @XmlElement(true)
  @XmlSerialName(
    "SAMLv2Identifier",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val samLv2Identifier: String? = null,
  @XmlElement(true)
  @XmlSerialName(
    "Other",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val other: AnyType? = null,
)
