// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.oasis.dssx10profiles.verificationreport

import de.gematik.connector.api.w3200009.xmldsig.X509IssuerSerialType
import kotlin.String
import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName

@Serializable
@XmlSerialName(
  "IndividualCertificateReport",
  namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
)
data class IndividualCertificateReport(
  @XmlElement(true)
  @XmlSerialName("CertificateIdentifier")
  val certificateIdentifier: X509IssuerSerialType,
  @XmlElement(true)
  @XmlSerialName("Subject")
  val subject: String,
  @XmlElement(true)
  @XmlSerialName("ChainingOK")
  val chainingOk: VerificationResultType,
  @XmlElement(true)
  @XmlSerialName("ValidityPeriodOK")
  val validityPeriodOk: VerificationResultType,
  @XmlElement(true)
  @XmlSerialName("ExtensionsOK")
  val extensionsOk: VerificationResultType,
  @XmlElement(true)
  @XmlSerialName("CertificateValue")
  val certificateValue: String? = null,
  @XmlElement(true)
  @XmlSerialName("CertificateContent")
  val certificateContent: CertificateContentType? = null,
  @XmlElement(true)
  @XmlSerialName("SignatureOK")
  val signatureOk: SignatureValidityType,
  @XmlElement(true)
  @XmlSerialName("CertificateStatus")
  val certificateStatus: CertificateStatusType,
)
