// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.oasis.dssx10profiles.verificationreport

import de.gematik.connector.api.etsi01903132.CRLIdentifierType
import kotlin.String
import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName

@Serializable
@XmlSerialName(
  "IndividualCRLReport",
  namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
)
data class IndividualCRLReport(
  @XmlElement(false)
  @XmlSerialName("Id")
  val id: String? = null,
  @XmlElement(true)
  @XmlSerialName("CRLIdentifier")
  val crlIdentifier: CRLIdentifierType,
  @XmlElement(true)
  @XmlSerialName("CRLValue")
  val crlValue: String? = null,
  @XmlElement(true)
  @XmlSerialName("CRLContent")
  val crlContent: CRLContentType? = null,
  @XmlElement(true)
  @XmlSerialName("SignatureOK")
  val signatureOk: SignatureValidityType,
  @XmlElement(true)
  @XmlSerialName("CertificatePathValidity")
  val certificatePathValidity: CertificatePathValidityType,
)
