// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.oasis.dssx10profiles.verificationreport

import kotlin.Int
import kotlin.String
import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName

@Serializable
data class OCSPContentType(
  @XmlElement(true)
  @XmlSerialName(
    "Version",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val version: Int,
  @XmlElement(true)
  @XmlSerialName(
    "ResponderID",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val responderId: String,
  @XmlElement(true)
  @XmlSerialName(
    "producedAt",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val producedAt: String,
  @XmlElement(true)
  @XmlSerialName(
    "Responses",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val responses: OCSPContentTypeResponses,
  @XmlElement(true)
  @XmlSerialName(
    "ResponseExtensions",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val responseExtensions: ExtensionsType? = null,
)
