// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.oasis.dssx10profiles.verificationreport

import de.gematik.connector.api.etsi01903132.OCSPIdentifierType
import kotlin.String
import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName

@Serializable
data class OCSPValidityType(
  @XmlElement(false)
  @XmlSerialName("Id")
  val id: String? = null,
  @XmlElement(true)
  @XmlSerialName(
    "OCSPIdentifier",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val ocspIdentifier: OCSPIdentifierType,
  @XmlElement(true)
  @XmlSerialName(
    "OCSPValue",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val ocspValue: String? = null,
  @XmlElement(true)
  @XmlSerialName(
    "OCSPContent",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val ocspContent: OCSPContentType? = null,
  @XmlElement(true)
  @XmlSerialName(
    "SignatureOK",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val signatureOk: SignatureValidityType,
  @XmlElement(true)
  @XmlSerialName(
    "CertificatePathValidity",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val certificatePathValidity: CertificatePathValidityType,
)
