// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.oasis.dssx10profiles.verificationreport

import de.gematik.connector.api.etsi01903132.AttributeCertificateRefs
import de.gematik.connector.api.etsi01903132.AttributeRevocationRefs
import de.gematik.connector.api.etsi01903132.CRLIdentifierType
import de.gematik.connector.api.etsi01903132.ClaimedRolesListType
import de.gematik.connector.api.etsi01903132.CommitmentTypeIndication
import de.gematik.connector.api.etsi01903132.CompleteCertificateRefs
import de.gematik.connector.api.etsi01903132.CompleteRevocationRefs
import de.gematik.connector.api.etsi01903132.DataObjectFormat
import de.gematik.connector.api.etsi01903132.DigestAlgAndValueType
import de.gematik.connector.api.etsi01903132.OCSPIdentifierType
import de.gematik.connector.api.etsi01903132.ObjectIdentifierType
import de.gematik.connector.api.etsi01903132.SignaturePolicyIdentifier
import de.gematik.connector.api.etsi01903132.SignatureProductionPlace
import de.gematik.connector.api.etsi01903132.SigningCertificate
import de.gematik.connector.api.etsi01903132.UnsignedDataObjectProperties
import de.gematik.connector.api.etsi022312.SchemeInformation
import de.gematik.connector.api.etsi022312.TSLTagType
import de.gematik.connector.api.etsi022312.TrustServiceProviderList
import de.gematik.connector.api.oasis.dss10core.AnyType
import de.gematik.connector.api.oasis.dss10core.InternationalStringType
import de.gematik.connector.api.oasis.dss10core.Result
import de.gematik.connector.api.oasis.dss10core.TstInfo
import de.gematik.connector.api.oasis.dss10core.VerificationTimeInfo
import de.gematik.connector.api.oasis.dss10core.VerifyManifestResults
import de.gematik.connector.api.w3200009.xmldsig.CanonicalizationMethod
import de.gematik.connector.api.w3200009.xmldsig.SignatureValue
import de.gematik.connector.api.w3200009.xmldsig.X509Data
import de.gematik.connector.api.w3200009.xmldsig.X509IssuerSerialType
import kotlin.Boolean
import kotlin.Int
import kotlin.String
import kotlin.collections.List
import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName

@Serializable
@XmlSerialName(
  "ReturnVerificationReport",
  namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
)
data class ReturnVerificationReport(
  @XmlElement(true)
  @XmlSerialName("IncludeVerifier")
  val includeVerifier: Boolean? = null,
  @XmlElement(true)
  @XmlSerialName("IncludeCertificateValues")
  val includeCertificateValues: Boolean? = null,
  @XmlElement(true)
  @XmlSerialName("IncludeRevocationValues")
  val includeRevocationValues: Boolean? = null,
  @XmlElement(true)
  @XmlSerialName("ExpandBinaryValues")
  val expandBinaryValues: Boolean? = null,
  @XmlElement(true)
  @XmlSerialName("ReportDetailLevel")
  val reportDetailLevel: String? = null,
)

@Serializable
@XmlSerialName(
  "VerificationReport",
  namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
)
data class VerificationReport(
  @XmlElement(true)
  @XmlSerialName(
    "VerificationTimeInfo",
    namespace = "urn:oasis:names:tc:dss:1.0:core:schema",
  )
  val verificationTimeInfo: VerificationTimeInfo? = null,
  @XmlElement(true)
  @XmlSerialName("VerifierIdentity")
  val verifierIdentity: IdentifierType? = null,
  @XmlElement(true)
  @XmlSerialName("IndividualReport")
  val individualReport: List<IndividualReportType> = emptyList(),
)

@Serializable
@XmlSerialName(
  "DetailedSignatureReport",
  namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
)
data class DetailedSignatureReport(
  @XmlElement(true)
  @XmlSerialName("FormatOK")
  val formatOk: VerificationResultType,
  @XmlElement(true)
  @XmlSerialName("Properties")
  val properties: PropertiesType? = null,
  @XmlElement(true)
  @XmlSerialName(
    "VerifyManifestResults",
    namespace = "urn:oasis:names:tc:dss:1.0:core:schema",
  )
  val verifyManifestResults: VerifyManifestResults? = null,
  @XmlElement(true)
  @XmlSerialName("SignatureHasVisibleContent")
  val signatureHasVisibleContent: Boolean? = null,
  @XmlElement(true)
  @XmlSerialName("SignatureOK")
  val signatureOk: SignatureValidityType,
  @XmlElement(true)
  @XmlSerialName("CertificatePathValidity")
  val certificatePathValidity: CertificatePathValidityType,
)

@Serializable
@XmlSerialName(
  "IndividualTimeStampReport",
  namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
)
data class IndividualTimeStampReport(
  @XmlElement(false)
  @XmlSerialName("Id")
  val id: String? = null,
  @XmlElement(true)
  @XmlSerialName("FormatOK")
  val formatOk: VerificationResultType,
  @XmlElement(true)
  @XmlSerialName("TimeStampContent")
  val timeStampContent: TstContentType? = null,
  @XmlElement(true)
  @XmlSerialName("MessageHashAlgorithm")
  val messageHashAlgorithm: AlgorithmValidityType? = null,
  @XmlElement(true)
  @XmlSerialName("SignatureOK")
  val signatureOk: SignatureValidityType,
  @XmlElement(true)
  @XmlSerialName("CertificatePathValidity")
  val certificatePathValidity: CertificatePathValidityType,
)

@Serializable
@XmlSerialName(
  "IndividualCertificateReport",
  namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
)
data class IndividualCertificateReport(
  @XmlElement(true)
  @XmlSerialName("CertificateIdentifier")
  val certificateIdentifier: X509IssuerSerialType,
  @XmlElement(true)
  @XmlSerialName("Subject")
  val subject: String,
  @XmlElement(true)
  @XmlSerialName("ChainingOK")
  val chainingOk: VerificationResultType,
  @XmlElement(true)
  @XmlSerialName("ValidityPeriodOK")
  val validityPeriodOk: VerificationResultType,
  @XmlElement(true)
  @XmlSerialName("ExtensionsOK")
  val extensionsOk: VerificationResultType,
  @XmlElement(true)
  @XmlSerialName("CertificateValue")
  val certificateValue: String? = null,
  @XmlElement(true)
  @XmlSerialName("CertificateContent")
  val certificateContent: CertificateContentType? = null,
  @XmlElement(true)
  @XmlSerialName("SignatureOK")
  val signatureOk: SignatureValidityType,
  @XmlElement(true)
  @XmlSerialName("CertificateStatus")
  val certificateStatus: CertificateStatusType,
)

@Serializable
@XmlSerialName(
  "IndividualAttributeCertificateReport",
  namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
)
data class IndividualAttributeCertificateReport(
  @XmlElement(true)
  @XmlSerialName("AttributeCertificateIdentifier")
  val attributeCertificateIdentifier: AttrCertIDType,
  @XmlElement(true)
  @XmlSerialName("AttributeCertificateValue")
  val attributeCertificateValue: String? = null,
  @XmlElement(true)
  @XmlSerialName("AttributeCertificateContent")
  val attributeCertificateContent: AttributeCertificateContentType? = null,
  @XmlElement(true)
  @XmlSerialName("SignatureOK")
  val signatureOk: SignatureValidityType,
  @XmlElement(true)
  @XmlSerialName("CertificatePathValidity")
  val certificatePathValidity: CertificatePathValidityType,
)

@Serializable
@XmlSerialName(
  "IndividualCRLReport",
  namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
)
data class IndividualCRLReport(
  @XmlElement(false)
  @XmlSerialName("Id")
  val id: String? = null,
  @XmlElement(true)
  @XmlSerialName("CRLIdentifier")
  val crlIdentifier: CRLIdentifierType,
  @XmlElement(true)
  @XmlSerialName("CRLValue")
  val crlValue: String? = null,
  @XmlElement(true)
  @XmlSerialName("CRLContent")
  val crlContent: CRLContentType? = null,
  @XmlElement(true)
  @XmlSerialName("SignatureOK")
  val signatureOk: SignatureValidityType,
  @XmlElement(true)
  @XmlSerialName("CertificatePathValidity")
  val certificatePathValidity: CertificatePathValidityType,
)

@Serializable
@XmlSerialName(
  "IndividualOCSPReport",
  namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
)
data class IndividualOCSPReport(
  @XmlElement(false)
  @XmlSerialName("Id")
  val id: String? = null,
  @XmlElement(true)
  @XmlSerialName("OCSPIdentifier")
  val ocspIdentifier: OCSPIdentifierType,
  @XmlElement(true)
  @XmlSerialName("OCSPValue")
  val ocspValue: String? = null,
  @XmlElement(true)
  @XmlSerialName("OCSPContent")
  val ocspContent: OCSPContentType? = null,
  @XmlElement(true)
  @XmlSerialName("SignatureOK")
  val signatureOk: SignatureValidityType,
  @XmlElement(true)
  @XmlSerialName("CertificatePathValidity")
  val certificatePathValidity: CertificatePathValidityType,
)

@Serializable
@XmlSerialName(
  "EvidenceRecordReport",
  namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
)
data class EvidenceRecordReport(
  @XmlElement(false)
  @XmlSerialName("Id")
  val id: String? = null,
  @XmlElement(true)
  @XmlSerialName("FormatOK")
  val formatOk: VerificationResultType,
  @XmlElement(true)
  @XmlSerialName("Version")
  val version: Int? = null,
  @XmlElement(true)
  @XmlSerialName("DigestAlgorithm")
  val digestAlgorithm: List<AlgorithmValidityType> = emptyList(),
  @XmlElement(true)
  @XmlSerialName("CryptoInfos")
  val cryptoInfos: EvidenceRecordValidityTypeCryptoInfos? = null,
  @XmlElement(true)
  @XmlSerialName("EncryptionInfo")
  val encryptionInfo: EvidenceRecordValidityTypeEncryptionInfo? = null,
  @XmlElement(true)
  @XmlSerialName("ArchiveTimeStampSequence")
  val archiveTimeStampSequence: EvidenceRecordValidityTypeArchiveTimeStampSequence,
)

@Serializable
data class VerificationReportType(
  @XmlElement(true)
  @XmlSerialName(
    "VerificationTimeInfo",
    namespace = "urn:oasis:names:tc:dss:1.0:core:schema",
  )
  val verificationTimeInfo: VerificationTimeInfo? = null,
  @XmlElement(true)
  @XmlSerialName(
    "VerifierIdentity",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val verifierIdentity: IdentifierType? = null,
  @XmlElement(true)
  @XmlSerialName(
    "IndividualReport",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val individualReport: List<IndividualReportType> = emptyList(),
)

@Serializable
data class IdentifierType(
  @XmlElement(true)
  @XmlSerialName(
    "X509Data",
    namespace = "http://www.w3.org/2000/09/xmldsig#",
  )
  val x509Data: X509Data? = null,
  @XmlElement(true)
  @XmlSerialName(
    "SAMLv1Identifier",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val samLv1Identifier: String? = null,
  @XmlElement(true)
  @XmlSerialName(
    "SAMLv2Identifier",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val samLv2Identifier: String? = null,
  @XmlElement(true)
  @XmlSerialName(
    "Other",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val other: AnyType? = null,
)

@Serializable
data class IndividualReportType(
  @XmlElement(true)
  @XmlSerialName(
    "SignedObjectIdentifier",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val signedObjectIdentifier: SignedObjectIdentifierType,
  @XmlElement(true)
  @XmlSerialName(
    "Result",
    namespace = "urn:oasis:names:tc:dss:1.0:core:schema",
  )
  val result: Result,
  @XmlElement(true)
  @XmlSerialName(
    "Details",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val details: AnyType? = null,
)

@Serializable
data class SignedObjectIdentifierType(
  @XmlElement(false)
  @XmlSerialName("WhichDocument")
  val whichDocument: String? = null,
  @XmlElement(false)
  @XmlSerialName("XPath")
  val xPath: String? = null,
  @XmlElement(false)
  @XmlSerialName("Offset")
  val offset: Int? = null,
  @XmlElement(false)
  @XmlSerialName("FieldName")
  val fieldName: String? = null,
  @XmlElement(true)
  @XmlSerialName(
    "DigestAlgAndValue",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val digestAlgAndValue: DigestAlgAndValueType? = null,
  @XmlElement(true)
  @XmlSerialName(
    "CanonicalizationMethod",
    namespace = "http://www.w3.org/2000/09/xmldsig#",
  )
  val canonicalizationMethod: CanonicalizationMethod? = null,
  @XmlElement(true)
  @XmlSerialName(
    "SignedProperties",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val signedProperties: SignedPropertiesType? = null,
  @XmlElement(true)
  @XmlSerialName(
    "SignatureValue",
    namespace = "http://www.w3.org/2000/09/xmldsig#",
  )
  val signatureValue: SignatureValue? = null,
  @XmlElement(true)
  @XmlSerialName(
    "Other",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val other: AnyType? = null,
)

@Serializable
data class VerificationResultType(
  @XmlElement(true)
  @XmlSerialName(
    "ResultMajor",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val resultMajor: String,
  @XmlElement(true)
  @XmlSerialName(
    "ResultMinor",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val resultMinor: String? = null,
  @XmlElement(true)
  @XmlSerialName(
    "ResultMessage",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val resultMessage: InternationalStringType? = null,
  @XmlElement(true)
  val unknownContent: String? = null,
)

@Serializable
data class DetailedSignatureReportType(
  @XmlElement(true)
  @XmlSerialName(
    "FormatOK",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val formatOk: VerificationResultType,
  @XmlElement(true)
  @XmlSerialName(
    "Properties",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val properties: PropertiesType? = null,
  @XmlElement(true)
  @XmlSerialName(
    "VerifyManifestResults",
    namespace = "urn:oasis:names:tc:dss:1.0:core:schema",
  )
  val verifyManifestResults: VerifyManifestResults? = null,
  @XmlElement(true)
  @XmlSerialName(
    "SignatureHasVisibleContent",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val signatureHasVisibleContent: Boolean? = null,
  @XmlElement(true)
  @XmlSerialName(
    "SignatureOK",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val signatureOk: SignatureValidityType,
  @XmlElement(true)
  @XmlSerialName(
    "CertificatePathValidity",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val certificatePathValidity: CertificatePathValidityType,
)

@Serializable
data class PropertiesType(
  @XmlElement(false)
  @XmlSerialName("Target")
  val target: String? = null,
  @XmlElement(false)
  @XmlSerialName("Id")
  val id: String? = null,
  @XmlElement(true)
  @XmlSerialName(
    "SignedProperties",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val signedProperties: SignedPropertiesType? = null,
  @XmlElement(true)
  @XmlSerialName(
    "UnsignedProperties",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val unsignedProperties: UnsignedPropertiesType? = null,
)

@Serializable
data class SignedPropertiesType(
  @XmlElement(false)
  @XmlSerialName("Id")
  val id: String? = null,
  @XmlElement(true)
  @XmlSerialName(
    "SignedSignatureProperties",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val signedSignatureProperties: SignedSignaturePropertiesType? = null,
  @XmlElement(true)
  @XmlSerialName(
    "SignedDataObjectProperties",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val signedDataObjectProperties: SignedDataObjectPropertiesType? = null,
  @XmlElement(true)
  @XmlSerialName(
    "Other",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val other: AnyType? = null,
)

@Serializable
data class SignedSignaturePropertiesType(
  @XmlElement(true)
  @XmlSerialName(
    "SigningTime",
    namespace = "http://uri.etsi.org/01903/v1.3.2#",
  )
  val signingTime: String? = null,
  @XmlElement(true)
  @XmlSerialName(
    "SigningCertificate",
    namespace = "http://uri.etsi.org/01903/v1.3.2#",
  )
  val signingCertificate: SigningCertificate? = null,
  @XmlElement(true)
  @XmlSerialName(
    "SignaturePolicyIdentifier",
    namespace = "http://uri.etsi.org/01903/v1.3.2#",
  )
  val signaturePolicyIdentifier: SignaturePolicyIdentifier? = null,
  @XmlElement(true)
  @XmlSerialName(
    "SignatureProductionPlace",
    namespace = "http://uri.etsi.org/01903/v1.3.2#",
  )
  val signatureProductionPlace: SignatureProductionPlace? = null,
  @XmlElement(true)
  @XmlSerialName(
    "Location",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val location: String? = null,
  @XmlElement(true)
  @XmlSerialName(
    "SignerRole",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val signerRole: SignerRoleType? = null,
)

@Serializable
data class SignerRoleType(
  @XmlElement(true)
  @XmlSerialName(
    "ClaimedRoles",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val claimedRoles: ClaimedRolesListType? = null,
  @XmlElement(true)
  @XmlSerialName(
    "CertifiedRoles",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val certifiedRoles: CertifiedRolesListType? = null,
)

@Serializable
data class CertifiedRolesListType(
  @XmlElement(true)
  @XmlSerialName(
    "AttributeCertificateValidity",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val attributeCertificateValidity: List<AttributeCertificateValidityType> = emptyList(),
)

@Serializable
data class AttributeCertificateValidityType(
  @XmlElement(true)
  @XmlSerialName(
    "AttributeCertificateIdentifier",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val attributeCertificateIdentifier: AttrCertIDType,
  @XmlElement(true)
  @XmlSerialName(
    "AttributeCertificateValue",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val attributeCertificateValue: String? = null,
  @XmlElement(true)
  @XmlSerialName(
    "AttributeCertificateContent",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val attributeCertificateContent: AttributeCertificateContentType? = null,
  @XmlElement(true)
  @XmlSerialName(
    "SignatureOK",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val signatureOk: SignatureValidityType,
  @XmlElement(true)
  @XmlSerialName(
    "CertificatePathValidity",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val certificatePathValidity: CertificatePathValidityType,
)

@Serializable
data class AttrCertIDType(
  @XmlElement(true)
  @XmlSerialName(
    "Holder",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val holder: EntityType? = null,
  @XmlElement(true)
  @XmlSerialName(
    "Issuer",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val issuer: EntityType,
  @XmlElement(true)
  @XmlSerialName(
    "SerialNumber",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val serialNumber: Int,
)

@Serializable
data class EntityType(
  @XmlElement(true)
  @XmlSerialName(
    "BaseCertificateID",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val baseCertificateId: X509IssuerSerialType? = null,
  @XmlElement(true)
  @XmlSerialName(
    "Name",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val name: String? = null,
  @XmlElement(true)
  @XmlSerialName(
    "Other",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val other: AnyType? = null,
)

@Serializable
data class AttributeCertificateContentType(
  @XmlElement(true)
  @XmlSerialName(
    "Version",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val version: Int? = null,
  @XmlElement(true)
  @XmlSerialName(
    "Holder",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val holder: EntityType,
  @XmlElement(true)
  @XmlSerialName(
    "Issuer",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val issuer: EntityType,
  @XmlElement(true)
  @XmlSerialName(
    "SignatureAlgorithm",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val signatureAlgorithm: String,
  @XmlElement(true)
  @XmlSerialName(
    "SerialNumber",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val serialNumber: Int,
  @XmlElement(true)
  @XmlSerialName(
    "AttCertValidityPeriod",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val attCertValidityPeriod: ValidityPeriodType,
  @XmlElement(true)
  @XmlSerialName(
    "Attributes",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val attributes: AttributeCertificateContentTypeAttributes,
  @XmlElement(true)
  @XmlSerialName(
    "IssuerUniqueID",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val issuerUniqueId: String? = null,
  @XmlElement(true)
  @XmlSerialName(
    "Extensions",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val extensions: ExtensionsType? = null,
)

@Serializable
data class ValidityPeriodType(
  @XmlElement(true)
  @XmlSerialName(
    "NotBefore",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val notBefore: String,
  @XmlElement(true)
  @XmlSerialName(
    "NotAfter",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val notAfter: String,
)

@Serializable
data class AttributeType(
  @XmlElement(true)
  @XmlSerialName(
    "Type",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val type: VerificationResultType,
  @XmlElement(true)
  @XmlSerialName(
    "Value",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val `value`: List<AnyType> = emptyList(),
)

@Serializable
data class ExtensionsType(
  @XmlElement(true)
  @XmlSerialName(
    "Extension",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val extension: List<ExtensionType> = emptyList(),
)

@Serializable
data class ExtensionType(
  @XmlElement(true)
  @XmlSerialName(
    "ExtnId",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val extnId: ObjectIdentifierType,
  @XmlElement(true)
  @XmlSerialName(
    "Critical",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val critical: Boolean,
  @XmlElement(true)
  @XmlSerialName(
    "ExtnValue",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val extnValue: AnyType? = null,
  @XmlElement(true)
  @XmlSerialName(
    "ExtensionOK",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val extensionOk: VerificationResultType,
)

@Serializable
data class SignedDataObjectPropertiesType(
  @XmlElement(false)
  @XmlSerialName("Id")
  val id: String? = null,
  @XmlElement(true)
  @XmlSerialName(
    "DataObjectFormat",
    namespace = "http://uri.etsi.org/01903/v1.3.2#",
  )
  val dataObjectFormat: List<DataObjectFormat> = emptyList(),
  @XmlElement(true)
  @XmlSerialName(
    "CommitmentTypeIndication",
    namespace = "http://uri.etsi.org/01903/v1.3.2#",
  )
  val commitmentTypeIndication: List<CommitmentTypeIndication> = emptyList(),
  @XmlElement(true)
  @XmlSerialName(
    "Reason",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val reason: String? = null,
  @XmlElement(true)
  @XmlSerialName(
    "AllDataObjectsTimeStamp",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val allDataObjectsTimeStamp: List<TimeStampValidityType> = emptyList(),
  @XmlElement(true)
  @XmlSerialName(
    "IndividualDataObjectsTimeStamp",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val individualDataObjectsTimeStamp: List<TimeStampValidityType> = emptyList(),
)

@Serializable
data class TimeStampValidityType(
  @XmlElement(false)
  @XmlSerialName("Id")
  val id: String? = null,
  @XmlElement(true)
  @XmlSerialName(
    "FormatOK",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val formatOk: VerificationResultType,
  @XmlElement(true)
  @XmlSerialName(
    "TimeStampContent",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val timeStampContent: TstContentType? = null,
  @XmlElement(true)
  @XmlSerialName(
    "MessageHashAlgorithm",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val messageHashAlgorithm: AlgorithmValidityType? = null,
  @XmlElement(true)
  @XmlSerialName(
    "SignatureOK",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val signatureOk: SignatureValidityType,
  @XmlElement(true)
  @XmlSerialName(
    "CertificatePathValidity",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val certificatePathValidity: CertificatePathValidityType,
)

@Serializable
data class TstContentType(
  @XmlElement(true)
  @XmlSerialName(
    "TstInfo",
    namespace = "urn:oasis:names:tc:dss:1.0:core:schema",
  )
  val tstInfo: TstInfo? = null,
  @XmlElement(true)
  @XmlSerialName(
    "Other",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val other: AnyType? = null,
)

@Serializable
data class SignatureValidityType(
  @XmlElement(true)
  @XmlSerialName(
    "SigMathOK",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val sigMathOk: VerificationResultType,
  @XmlElement(true)
  @XmlSerialName(
    "SignatureAlgorithm",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val signatureAlgorithm: AlgorithmValidityType? = null,
)

@Serializable
data class AlgorithmValidityType(
  @XmlElement(true)
  @XmlSerialName(
    "Algorithm",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val algorithm: String,
  @XmlElement(true)
  @XmlSerialName(
    "Parameters",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val parameters: AnyType? = null,
  @XmlElement(true)
  @XmlSerialName(
    "Suitability",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val suitability: VerificationResultType? = null,
)

@Serializable
data class CertificatePathValidityType(
  @XmlElement(true)
  @XmlSerialName(
    "PathValiditySummary",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val pathValiditySummary: VerificationResultType,
  @XmlElement(true)
  @XmlSerialName(
    "CertificateIdentifier",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val certificateIdentifier: X509IssuerSerialType,
  @XmlElement(true)
  @XmlSerialName(
    "PathValidityDetail",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val pathValidityDetail: CertificatePathValidityVerificationDetailType? = null,
)

@Serializable
data class CertificatePathValidityVerificationDetailType(
  @XmlElement(true)
  @XmlSerialName(
    "CertificateValidity",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val certificateValidity: List<CertificateValidityType> = emptyList(),
  @XmlElement(true)
  @XmlSerialName(
    "TSLValidity",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val tslValidity: TrustStatusListValidityType? = null,
  @XmlElement(true)
  @XmlSerialName(
    "TrustAnchor",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val trustAnchor: VerificationResultType,
)

@Serializable
data class CertificateValidityType(
  @XmlElement(true)
  @XmlSerialName(
    "CertificateIdentifier",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val certificateIdentifier: X509IssuerSerialType,
  @XmlElement(true)
  @XmlSerialName(
    "Subject",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val subject: String,
  @XmlElement(true)
  @XmlSerialName(
    "ChainingOK",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val chainingOk: VerificationResultType,
  @XmlElement(true)
  @XmlSerialName(
    "ValidityPeriodOK",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val validityPeriodOk: VerificationResultType,
  @XmlElement(true)
  @XmlSerialName(
    "ExtensionsOK",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val extensionsOk: VerificationResultType,
  @XmlElement(true)
  @XmlSerialName(
    "CertificateValue",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val certificateValue: String? = null,
  @XmlElement(true)
  @XmlSerialName(
    "CertificateContent",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val certificateContent: CertificateContentType? = null,
  @XmlElement(true)
  @XmlSerialName(
    "SignatureOK",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val signatureOk: SignatureValidityType,
  @XmlElement(true)
  @XmlSerialName(
    "CertificateStatus",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val certificateStatus: CertificateStatusType,
)

@Serializable
data class CertificateContentType(
  @XmlElement(true)
  @XmlSerialName(
    "Version",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val version: Int? = null,
  @XmlElement(true)
  @XmlSerialName(
    "SerialNumber",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val serialNumber: Int,
  @XmlElement(true)
  @XmlSerialName(
    "SignatureAlgorithm",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val signatureAlgorithm: String,
  @XmlElement(true)
  @XmlSerialName(
    "Issuer",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val issuer: String,
  @XmlElement(true)
  @XmlSerialName(
    "ValidityPeriod",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val validityPeriod: ValidityPeriodType,
  @XmlElement(true)
  @XmlSerialName(
    "Subject",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val subject: String,
  @XmlElement(true)
  @XmlSerialName(
    "Extensions",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val extensions: ExtensionsType? = null,
)

@Serializable
data class CertificateStatusType(
  @XmlElement(true)
  @XmlSerialName(
    "CertStatusOK",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val certStatusOk: VerificationResultType,
  @XmlElement(true)
  @XmlSerialName(
    "RevocationInfo",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val revocationInfo: CertificateStatusTypeRevocationInfo? = null,
  @XmlElement(true)
  @XmlSerialName(
    "RevocationEvidence",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val revocationEvidence: CertificateStatusTypeRevocationEvidence? = null,
)

@Serializable
data class CRLValidityType(
  @XmlElement(false)
  @XmlSerialName("Id")
  val id: String? = null,
  @XmlElement(true)
  @XmlSerialName(
    "CRLIdentifier",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val crlIdentifier: CRLIdentifierType,
  @XmlElement(true)
  @XmlSerialName(
    "CRLValue",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val crlValue: String? = null,
  @XmlElement(true)
  @XmlSerialName(
    "CRLContent",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val crlContent: CRLContentType? = null,
  @XmlElement(true)
  @XmlSerialName(
    "SignatureOK",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val signatureOk: SignatureValidityType,
  @XmlElement(true)
  @XmlSerialName(
    "CertificatePathValidity",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val certificatePathValidity: CertificatePathValidityType,
)

@Serializable
data class CRLContentType(
  @XmlElement(true)
  @XmlSerialName(
    "Version",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val version: Int? = null,
  @XmlElement(true)
  @XmlSerialName(
    "Signature",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val signature: VerificationResultType,
  @XmlElement(true)
  @XmlSerialName(
    "Issuer",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val issuer: String,
  @XmlElement(true)
  @XmlSerialName(
    "ThisUpdate",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val thisUpdate: String,
  @XmlElement(true)
  @XmlSerialName(
    "NextUpdate",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val nextUpdate: String? = null,
  @XmlElement(true)
  @XmlSerialName(
    "RevokedCertificates",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val revokedCertificates: CRLContentTypeRevokedCertificates? = null,
  @XmlElement(true)
  @XmlSerialName(
    "CrlExtensions",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val crlExtensions: ExtensionsType? = null,
)

@Serializable
data class OCSPValidityType(
  @XmlElement(false)
  @XmlSerialName("Id")
  val id: String? = null,
  @XmlElement(true)
  @XmlSerialName(
    "OCSPIdentifier",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val ocspIdentifier: OCSPIdentifierType,
  @XmlElement(true)
  @XmlSerialName(
    "OCSPValue",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val ocspValue: String? = null,
  @XmlElement(true)
  @XmlSerialName(
    "OCSPContent",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val ocspContent: OCSPContentType? = null,
  @XmlElement(true)
  @XmlSerialName(
    "SignatureOK",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val signatureOk: SignatureValidityType,
  @XmlElement(true)
  @XmlSerialName(
    "CertificatePathValidity",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val certificatePathValidity: CertificatePathValidityType,
)

@Serializable
data class OCSPContentType(
  @XmlElement(true)
  @XmlSerialName(
    "Version",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val version: Int,
  @XmlElement(true)
  @XmlSerialName(
    "ResponderID",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val responderId: String,
  @XmlElement(true)
  @XmlSerialName(
    "producedAt",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val producedAt: String,
  @XmlElement(true)
  @XmlSerialName(
    "Responses",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val responses: OCSPContentTypeResponses,
  @XmlElement(true)
  @XmlSerialName(
    "ResponseExtensions",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val responseExtensions: ExtensionsType? = null,
)

@Serializable
data class SingleResponseType(
  @XmlElement(true)
  @XmlSerialName(
    "CertID",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val certId: SingleResponseTypeCertId,
  @XmlElement(true)
  @XmlSerialName(
    "CertStatus",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val certStatus: VerificationResultType,
  @XmlElement(true)
  @XmlSerialName(
    "ThisUpdate",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val thisUpdate: String,
  @XmlElement(true)
  @XmlSerialName(
    "NextUpdate",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val nextUpdate: String? = null,
  @XmlElement(true)
  @XmlSerialName(
    "SingleExtensions",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val singleExtensions: ExtensionsType? = null,
)

@Serializable
data class TrustStatusListValidityType(
  @XmlElement(false)
  @XmlSerialName("TSLTag")
  val tslTag: TSLTagType,
  @XmlElement(false)
  @XmlSerialName("Id")
  val id: String? = null,
  @XmlElement(true)
  @XmlSerialName(
    "SchemeInformation",
    namespace = "http://uri.etsi.org/02231/v2#",
  )
  val schemeInformation: SchemeInformation,
  @XmlElement(true)
  @XmlSerialName(
    "TrustServiceProviderList",
    namespace = "http://uri.etsi.org/02231/v2#",
  )
  val trustServiceProviderList: TrustServiceProviderList? = null,
  @XmlElement(true)
  @XmlSerialName(
    "SignatureOK",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val signatureOk: SignatureValidityType,
)

@Serializable
data class UnsignedPropertiesType(
  @XmlElement(false)
  @XmlSerialName("Id")
  val id: String? = null,
  @XmlElement(true)
  @XmlSerialName(
    "UnsignedSignatureProperties",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val unsignedSignatureProperties: UnsignedSignaturePropertiesType? = null,
  @XmlElement(true)
  @XmlSerialName(
    "UnsignedDataObjectProperties",
    namespace = "http://uri.etsi.org/01903/v1.3.2#",
  )
  val unsignedDataObjectProperties: UnsignedDataObjectProperties? = null,
  @XmlElement(true)
  @XmlSerialName(
    "Other",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val other: AnyType? = null,
)

@Serializable
data class UnsignedSignaturePropertiesType(
  @XmlElement(false)
  @XmlSerialName("Id")
  val id: String? = null,
  @XmlElement(true)
  @XmlSerialName(
    "CounterSignature",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val counterSignature: List<SignatureValidityType> = emptyList(),
  @XmlElement(true)
  @XmlSerialName(
    "SignatureTimeStamp",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val signatureTimeStamp: List<TimeStampValidityType> = emptyList(),
  @XmlElement(true)
  @XmlSerialName(
    "CompleteCertificateRefs",
    namespace = "http://uri.etsi.org/01903/v1.3.2#",
  )
  val completeCertificateRefs: List<CompleteCertificateRefs> = emptyList(),
  @XmlElement(true)
  @XmlSerialName(
    "CompleteRevocationRefs",
    namespace = "http://uri.etsi.org/01903/v1.3.2#",
  )
  val completeRevocationRefs: List<CompleteRevocationRefs> = emptyList(),
  @XmlElement(true)
  @XmlSerialName(
    "AttributeCertificateRefs",
    namespace = "http://uri.etsi.org/01903/v1.3.2#",
  )
  val attributeCertificateRefs: List<AttributeCertificateRefs> = emptyList(),
  @XmlElement(true)
  @XmlSerialName(
    "AttributeRevocationRefs",
    namespace = "http://uri.etsi.org/01903/v1.3.2#",
  )
  val attributeRevocationRefs: List<AttributeRevocationRefs> = emptyList(),
  @XmlElement(true)
  @XmlSerialName(
    "SigAndRefsTimeStamp",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val sigAndRefsTimeStamp: List<TimeStampValidityType> = emptyList(),
  @XmlElement(true)
  @XmlSerialName(
    "RefsOnlyTimeStamp",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val refsOnlyTimeStamp: List<TimeStampValidityType> = emptyList(),
  @XmlElement(true)
  @XmlSerialName(
    "CertificateValues",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val certificateValues: List<CertificateValuesType> = emptyList(),
  @XmlElement(true)
  @XmlSerialName(
    "RevocationValues",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val revocationValues: List<RevocationValuesType> = emptyList(),
  @XmlElement(true)
  @XmlSerialName(
    "AttrAuthoritiesCertValues",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val attrAuthoritiesCertValues: List<CertificateValuesType> = emptyList(),
  @XmlElement(true)
  @XmlSerialName(
    "AttributeRevocationValues",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val attributeRevocationValues: List<RevocationValuesType> = emptyList(),
  @XmlElement(true)
  @XmlSerialName(
    "ArchiveTimeStamp",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val archiveTimeStamp: List<TimeStampValidityType> = emptyList(),
)

@Serializable
data class RevocationValuesType(
  @XmlElement(false)
  @XmlSerialName("Id")
  val id: String? = null,
  @XmlElement(true)
  @XmlSerialName(
    "CRLValues",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val crlValues: RevocationValuesTypeCrlValues? = null,
  @XmlElement(true)
  @XmlSerialName(
    "OCSPValues",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val ocspValues: RevocationValuesTypeOcspValues? = null,
  @XmlElement(true)
  @XmlSerialName(
    "OtherValues",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val otherValues: AnyType? = null,
)

@Serializable
data class CertificateValuesType(
  @XmlElement(false)
  @XmlSerialName("Id")
  val id: String? = null,
  @XmlElement(true)
  @XmlSerialName(
    "EncapsulatedX509Certificate",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val encapsulatedX509Certificate: List<CertificateValidityType> = emptyList(),
  @XmlElement(true)
  @XmlSerialName(
    "OtherCertificate",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val otherCertificate: List<String> = emptyList(),
)

@Serializable
data class EvidenceRecordValidityType(
  @XmlElement(false)
  @XmlSerialName("Id")
  val id: String? = null,
  @XmlElement(true)
  @XmlSerialName(
    "FormatOK",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val formatOk: VerificationResultType,
  @XmlElement(true)
  @XmlSerialName(
    "Version",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val version: Int? = null,
  @XmlElement(true)
  @XmlSerialName(
    "DigestAlgorithm",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val digestAlgorithm: List<AlgorithmValidityType> = emptyList(),
  @XmlElement(true)
  @XmlSerialName(
    "CryptoInfos",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val cryptoInfos: EvidenceRecordValidityTypeCryptoInfos? = null,
  @XmlElement(true)
  @XmlSerialName(
    "EncryptionInfo",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val encryptionInfo: EvidenceRecordValidityTypeEncryptionInfo? = null,
  @XmlElement(true)
  @XmlSerialName(
    "ArchiveTimeStampSequence",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val archiveTimeStampSequence: EvidenceRecordValidityTypeArchiveTimeStampSequence,
)

@Serializable
data class ArchiveTimeStampValidityType(
  @XmlElement(false)
  @XmlSerialName("Id")
  val id: String? = null,
  @XmlElement(true)
  @XmlSerialName(
    "FormatOK",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val formatOk: VerificationResultType,
  @XmlElement(true)
  @XmlSerialName(
    "DigestAlgorithm",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val digestAlgorithm: AlgorithmValidityType? = null,
  @XmlElement(true)
  @XmlSerialName(
    "Attributes",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val attributes: ArchiveTimeStampValidityTypeAttributes? = null,
  @XmlElement(true)
  @XmlSerialName(
    "ReducedHashTree",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val reducedHashTree: ArchiveTimeStampValidityTypeReducedHashTree? = null,
  @XmlElement(true)
  @XmlSerialName(
    "TimeStamp",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val timeStamp: TimeStampValidityType,
)

@Serializable
data class HashValueType(
  @XmlElement(false)
  @XmlSerialName("HashedObject")
  val hashedObject: String? = null,
  @XmlElement(true)
  @XmlSerialName(
    "HashValue",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val hashValue: String,
)

@Serializable
@XmlSerialName(
  "Attributes",
  namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
)
data class AttributeCertificateContentTypeAttributes(
  @XmlElement(true)
  @XmlSerialName("Attribute")
  val attribute: List<AttributeType> = emptyList(),
)

@Serializable
@XmlSerialName(
  "RevocationInfo",
  namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
)
data class CertificateStatusTypeRevocationInfo(
  @XmlElement(true)
  @XmlSerialName("RevocationDate")
  val revocationDate: String,
  @XmlElement(true)
  @XmlSerialName("RevocationReason")
  val revocationReason: VerificationResultType,
)

@Serializable
@XmlSerialName(
  "RevocationEvidence",
  namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
)
data class CertificateStatusTypeRevocationEvidence(
  @XmlElement(true)
  @XmlSerialName("CRLValidity")
  val crlValidity: CRLValidityType? = null,
  @XmlElement(true)
  @XmlSerialName("CRLReference")
  val crlReference: CRLIdentifierType? = null,
  @XmlElement(true)
  @XmlSerialName("OCSPValidity")
  val ocspValidity: OCSPValidityType? = null,
  @XmlElement(true)
  @XmlSerialName("OCSPReference")
  val ocspReference: OCSPIdentifierType? = null,
  @XmlElement(true)
  @XmlSerialName("Other")
  val other: AnyType? = null,
)

@Serializable
@XmlSerialName(
  "RevokedCertificates",
  namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
)
data class CRLContentTypeRevokedCertificates(
  @XmlElement(true)
  @XmlSerialName("UserCertificate")
  val userCertificate: List<Int> = emptyList(),
  @XmlElement(true)
  @XmlSerialName("RevocationDate")
  val revocationDate: List<String> = emptyList(),
  @XmlElement(true)
  @XmlSerialName("CrlEntryExtensions")
  val crlEntryExtensions: List<ExtensionsType> = emptyList(),
)

@Serializable
@XmlSerialName(
  "Responses",
  namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
)
data class OCSPContentTypeResponses(
  @XmlElement(true)
  @XmlSerialName("SingleResponse")
  val singleResponse: List<SingleResponseType> = emptyList(),
)

@Serializable
@XmlSerialName(
  "CertID",
  namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
)
data class SingleResponseTypeCertId(
  @XmlElement(true)
  @XmlSerialName("HashAlgorithm")
  val hashAlgorithm: String,
  @XmlElement(true)
  @XmlSerialName("IssuerNameHash")
  val issuerNameHash: String,
  @XmlElement(true)
  @XmlSerialName("IssuerKeyHash")
  val issuerKeyHash: String,
  @XmlElement(true)
  @XmlSerialName("SerialNumber")
  val serialNumber: Int,
)

@Serializable
@XmlSerialName(
  "CRLValues",
  namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
)
data class RevocationValuesTypeCrlValues(
  @XmlElement(true)
  @XmlSerialName("VerifiedCRL")
  val verifiedCrl: List<CRLValidityType> = emptyList(),
)

@Serializable
@XmlSerialName(
  "OCSPValues",
  namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
)
data class RevocationValuesTypeOcspValues(
  @XmlElement(true)
  @XmlSerialName("VerifiedOCSPResponse")
  val verifiedOcspResponse: List<OCSPValidityType> = emptyList(),
)

@Serializable
@XmlSerialName(
  "CryptoInfos",
  namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
)
data class EvidenceRecordValidityTypeCryptoInfos(
  @XmlElement(true)
  @XmlSerialName("Attribute")
  val attribute: List<AttributeType> = emptyList(),
)

@Serializable
@XmlSerialName(
  "EncryptionInfo",
  namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
)
data class EvidenceRecordValidityTypeEncryptionInfo(
  @XmlElement(true)
  @XmlSerialName("EncryptionInfoType")
  val encryptionInfoType: AlgorithmValidityType,
  @XmlElement(true)
  @XmlSerialName("EncryptionInfoValue")
  val encryptionInfoValue: AnyType,
)

@Serializable
@XmlSerialName(
  "ArchiveTimeStampSequence",
  namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
)
data class EvidenceRecordValidityTypeArchiveTimeStampSequence(
  @XmlElement(true)
  @XmlSerialName("ArchiveTimeStampChain")
  val archiveTimeStampChain:
      List<EvidenceRecordValidityTypeArchiveTimeStampSequenceArchiveTimeStampChain> = emptyList(),
)

@Serializable
@XmlSerialName(
  "Attributes",
  namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
)
data class ArchiveTimeStampValidityTypeAttributes(
  @XmlElement(true)
  @XmlSerialName("Attribute")
  val attribute: List<AttributeType> = emptyList(),
)

@Serializable
@XmlSerialName(
  "ReducedHashTree",
  namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
)
data class ArchiveTimeStampValidityTypeReducedHashTree(
  @XmlElement(true)
  @XmlSerialName("PartialHashTree")
  val partialHashTree:
      List<ArchiveTimeStampValidityTypeReducedHashTreePartialHashTree> = emptyList(),
)

@Serializable
@XmlSerialName(
  "ArchiveTimeStampChain",
  namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
)
data class EvidenceRecordValidityTypeArchiveTimeStampSequenceArchiveTimeStampChain(
  @XmlElement(true)
  @XmlSerialName("ArchiveTimeStamp")
  val archiveTimeStamp: List<ArchiveTimeStampValidityType> = emptyList(),
)

@Serializable
@XmlSerialName(
  "PartialHashTree",
  namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
)
data class ArchiveTimeStampValidityTypeReducedHashTreePartialHashTree(
  @XmlElement(true)
  @XmlSerialName("HashValue")
  val hashValue: List<HashValueType> = emptyList(),
)
