// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.oasis.dssx10profiles.verificationreport

import de.gematik.connector.api.etsi01903132.CommitmentTypeIndication
import de.gematik.connector.api.etsi01903132.DataObjectFormat
import kotlin.String
import kotlin.collections.List
import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName

@Serializable
data class SignedDataObjectPropertiesType(
  @XmlElement(false)
  @XmlSerialName("Id")
  val id: String? = null,
  @XmlElement(true)
  @XmlSerialName(
    "DataObjectFormat",
    namespace = "http://uri.etsi.org/01903/v1.3.2#",
  )
  val dataObjectFormat: List<DataObjectFormat> = emptyList(),
  @XmlElement(true)
  @XmlSerialName(
    "CommitmentTypeIndication",
    namespace = "http://uri.etsi.org/01903/v1.3.2#",
  )
  val commitmentTypeIndication: List<CommitmentTypeIndication> = emptyList(),
  @XmlElement(true)
  @XmlSerialName(
    "Reason",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val reason: String? = null,
  @XmlElement(true)
  @XmlSerialName(
    "AllDataObjectsTimeStamp",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val allDataObjectsTimeStamp: List<TimeStampValidityType> = emptyList(),
  @XmlElement(true)
  @XmlSerialName(
    "IndividualDataObjectsTimeStamp",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val individualDataObjectsTimeStamp: List<TimeStampValidityType> = emptyList(),
)
