// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.oasis.dssx10profiles.verificationreport

import de.gematik.connector.api.oasis.dss10core.AnyType
import kotlin.String
import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName

@Serializable
data class SignedPropertiesType(
  @XmlElement(false)
  @XmlSerialName("Id")
  val id: String? = null,
  @XmlElement(true)
  @XmlSerialName(
    "SignedSignatureProperties",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val signedSignatureProperties: SignedSignaturePropertiesType? = null,
  @XmlElement(true)
  @XmlSerialName(
    "SignedDataObjectProperties",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val signedDataObjectProperties: SignedDataObjectPropertiesType? = null,
  @XmlElement(true)
  @XmlSerialName(
    "Other",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val other: AnyType? = null,
)
