// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.oasis.dssx10profiles.verificationreport

import de.gematik.connector.api.etsi01903132.SignaturePolicyIdentifier
import de.gematik.connector.api.etsi01903132.SignatureProductionPlace
import de.gematik.connector.api.etsi01903132.SigningCertificate
import kotlin.String
import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName

@Serializable
data class SignedSignaturePropertiesType(
  @XmlElement(true)
  @XmlSerialName(
    "SigningTime",
    namespace = "http://uri.etsi.org/01903/v1.3.2#",
  )
  val signingTime: String? = null,
  @XmlElement(true)
  @XmlSerialName(
    "SigningCertificate",
    namespace = "http://uri.etsi.org/01903/v1.3.2#",
  )
  val signingCertificate: SigningCertificate? = null,
  @XmlElement(true)
  @XmlSerialName(
    "SignaturePolicyIdentifier",
    namespace = "http://uri.etsi.org/01903/v1.3.2#",
  )
  val signaturePolicyIdentifier: SignaturePolicyIdentifier? = null,
  @XmlElement(true)
  @XmlSerialName(
    "SignatureProductionPlace",
    namespace = "http://uri.etsi.org/01903/v1.3.2#",
  )
  val signatureProductionPlace: SignatureProductionPlace? = null,
  @XmlElement(true)
  @XmlSerialName(
    "Location",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val location: String? = null,
  @XmlElement(true)
  @XmlSerialName(
    "SignerRole",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val signerRole: SignerRoleType? = null,
)
