// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.oasis.dssx10profiles.verificationreport

import kotlin.Int
import kotlin.String
import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName

@Serializable
@XmlSerialName(
  "CertID",
  namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
)
data class SingleResponseTypeCertId(
  @XmlElement(true)
  @XmlSerialName("HashAlgorithm")
  val hashAlgorithm: String,
  @XmlElement(true)
  @XmlSerialName("IssuerNameHash")
  val issuerNameHash: String,
  @XmlElement(true)
  @XmlSerialName("IssuerKeyHash")
  val issuerKeyHash: String,
  @XmlElement(true)
  @XmlSerialName("SerialNumber")
  val serialNumber: Int,
)
