// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.oasis.dssx10profiles.verificationreport

import kotlin.String
import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName

@Serializable
data class TimeStampValidityType(
  @XmlElement(false)
  @XmlSerialName("Id")
  val id: String? = null,
  @XmlElement(true)
  @XmlSerialName(
    "FormatOK",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val formatOk: VerificationResultType,
  @XmlElement(true)
  @XmlSerialName(
    "TimeStampContent",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val timeStampContent: TstContentType? = null,
  @XmlElement(true)
  @XmlSerialName(
    "MessageHashAlgorithm",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val messageHashAlgorithm: AlgorithmValidityType? = null,
  @XmlElement(true)
  @XmlSerialName(
    "SignatureOK",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val signatureOk: SignatureValidityType,
  @XmlElement(true)
  @XmlSerialName(
    "CertificatePathValidity",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val certificatePathValidity: CertificatePathValidityType,
)
