// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.oasis.dssx10profiles.verificationreport

import de.gematik.connector.api.etsi022312.SchemeInformation
import de.gematik.connector.api.etsi022312.TSLTagType
import de.gematik.connector.api.etsi022312.TrustServiceProviderList
import kotlin.String
import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName

@Serializable
data class TrustStatusListValidityType(
  @XmlElement(false)
  @XmlSerialName("TSLTag")
  val tslTag: TSLTagType,
  @XmlElement(false)
  @XmlSerialName("Id")
  val id: String? = null,
  @XmlElement(true)
  @XmlSerialName(
    "SchemeInformation",
    namespace = "http://uri.etsi.org/02231/v2#",
  )
  val schemeInformation: SchemeInformation,
  @XmlElement(true)
  @XmlSerialName(
    "TrustServiceProviderList",
    namespace = "http://uri.etsi.org/02231/v2#",
  )
  val trustServiceProviderList: TrustServiceProviderList? = null,
  @XmlElement(true)
  @XmlSerialName(
    "SignatureOK",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val signatureOk: SignatureValidityType,
)
