// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.oasis.dssx10profiles.verificationreport

import de.gematik.connector.api.etsi01903132.AttributeCertificateRefs
import de.gematik.connector.api.etsi01903132.AttributeRevocationRefs
import de.gematik.connector.api.etsi01903132.CompleteCertificateRefs
import de.gematik.connector.api.etsi01903132.CompleteRevocationRefs
import kotlin.String
import kotlin.collections.List
import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName

@Serializable
data class UnsignedSignaturePropertiesType(
  @XmlElement(false)
  @XmlSerialName("Id")
  val id: String? = null,
  @XmlElement(true)
  @XmlSerialName(
    "CounterSignature",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val counterSignature: List<SignatureValidityType> = emptyList(),
  @XmlElement(true)
  @XmlSerialName(
    "SignatureTimeStamp",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val signatureTimeStamp: List<TimeStampValidityType> = emptyList(),
  @XmlElement(true)
  @XmlSerialName(
    "CompleteCertificateRefs",
    namespace = "http://uri.etsi.org/01903/v1.3.2#",
  )
  val completeCertificateRefs: List<CompleteCertificateRefs> = emptyList(),
  @XmlElement(true)
  @XmlSerialName(
    "CompleteRevocationRefs",
    namespace = "http://uri.etsi.org/01903/v1.3.2#",
  )
  val completeRevocationRefs: List<CompleteRevocationRefs> = emptyList(),
  @XmlElement(true)
  @XmlSerialName(
    "AttributeCertificateRefs",
    namespace = "http://uri.etsi.org/01903/v1.3.2#",
  )
  val attributeCertificateRefs: List<AttributeCertificateRefs> = emptyList(),
  @XmlElement(true)
  @XmlSerialName(
    "AttributeRevocationRefs",
    namespace = "http://uri.etsi.org/01903/v1.3.2#",
  )
  val attributeRevocationRefs: List<AttributeRevocationRefs> = emptyList(),
  @XmlElement(true)
  @XmlSerialName(
    "SigAndRefsTimeStamp",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val sigAndRefsTimeStamp: List<TimeStampValidityType> = emptyList(),
  @XmlElement(true)
  @XmlSerialName(
    "RefsOnlyTimeStamp",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val refsOnlyTimeStamp: List<TimeStampValidityType> = emptyList(),
  @XmlElement(true)
  @XmlSerialName(
    "CertificateValues",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val certificateValues: List<CertificateValuesType> = emptyList(),
  @XmlElement(true)
  @XmlSerialName(
    "RevocationValues",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val revocationValues: List<RevocationValuesType> = emptyList(),
  @XmlElement(true)
  @XmlSerialName(
    "AttrAuthoritiesCertValues",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val attrAuthoritiesCertValues: List<CertificateValuesType> = emptyList(),
  @XmlElement(true)
  @XmlSerialName(
    "AttributeRevocationValues",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val attributeRevocationValues: List<RevocationValuesType> = emptyList(),
  @XmlElement(true)
  @XmlSerialName(
    "ArchiveTimeStamp",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val archiveTimeStamp: List<TimeStampValidityType> = emptyList(),
)
