// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.oasis.dssx10profiles.verificationreport

import de.gematik.connector.api.oasis.dss10core.VerificationTimeInfo
import kotlin.collections.List
import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName

@Serializable
data class VerificationReportType(
  @XmlElement(true)
  @XmlSerialName(
    "VerificationTimeInfo",
    namespace = "urn:oasis:names:tc:dss:1.0:core:schema",
  )
  val verificationTimeInfo: VerificationTimeInfo? = null,
  @XmlElement(true)
  @XmlSerialName(
    "VerifierIdentity",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val verifierIdentity: IdentifierType? = null,
  @XmlElement(true)
  @XmlSerialName(
    "IndividualReport",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val individualReport: List<IndividualReportType> = emptyList(),
)
