// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.gematik.conn.cardservice81

import de.gematik.connector.api.gematik.conn.cardservicecommon20.PinResult
import de.gematik.connector.api.gematik.conn.connectorcommon50.Status
import kotlin.Int
import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName

@Serializable
@XmlSerialName(
  "ChangePinResponse",
  namespace = "http://ws.gematik.de/conn/CardService/v8.1",
)
data class ChangePinResponse(
  @XmlElement(true)
  @XmlSerialName(
    "Status",
    namespace = "http://ws.gematik.de/conn/ConnectorCommon/v5.0",
  )
  val status: Status,
  @XmlElement(true)
  @XmlSerialName(
    "PinResult",
    namespace = "http://ws.gematik.de/conn/CardServiceCommon/v2.0",
  )
  val pinResult: PinResult,
  @XmlElement(true)
  @XmlSerialName(
    "LeftTries",
    namespace = "http://ws.gematik.de/conn/CardServiceCommon/v2.0",
  )
  val leftTries: Int? = null,
)
