// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.gematik.conn.cardservice81

import de.gematik.connector.api.soap.SoapEnvelope
import kotlin.Boolean
import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName

@Serializable
@XmlSerialName(
  "Envelope",
  namespace = "http://schemas.xmlsoap.org/soap/envelope/",
  prefix = "SOAP-ENV",
)
data class UnblockPinEnvelope(
  @XmlElement(true)
  @XmlSerialName(
    "Body",
    namespace = "http://schemas.xmlsoap.org/soap/envelope/",
    prefix = "SOAP-ENV",
  )
  val body: Body,
) : SoapEnvelope {
  override fun isFault(): Boolean = false

  @Serializable
  data class Body(
    @XmlElement(true)
    val unblockPin: UnblockPin? = null,
  )
}
