// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.gematik.conn.cardservice821

interface CardServicePort {
  fun verifyPin(request: VerifyPin): VerifyPinResponse

  fun changePin(request: ChangePin): ChangePinResponse

  fun unblockPin(request: UnblockPin): UnblockPinResponse

  fun getPinStatus(request: GetPinStatus): GetPinStatusResponse

  fun enablePin(request: EnablePin): EnablePinResponse

  fun disablePin(request: DisablePin): DisablePinResponse

  fun secureSendAPDU(request: SecureSendAPDU): SecureSendAPDUResponse

  fun startCardSession(request: StartCardSession): StartCardSessionResponse

  fun stopCardSession(request: StopCardSession): StopCardSessionResponse
}
