// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.gematik.conn.cardservice821

import de.gematik.connector.api.gematik.conn.cardservicecommon20.CardType
import de.gematik.connector.api.gematik.conn.cardservicecommon20.PinResult
import de.gematik.connector.api.gematik.conn.connectorcommon50.Status
import de.gematik.connector.api.gematik.conn.connectorcontext20.Context
import de.gematik.connector.api.gematik.tel.error20.Error
import kotlin.Boolean
import kotlin.Int
import kotlin.String
import kotlin.collections.List
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName

@Serializable
@XmlSerialName(
  "Cards",
  namespace = "http://ws.gematik.de/conn/CardService/v8.2",
)
data class Cards(
  @XmlElement(true)
  @XmlSerialName("Card")
  val card: List<Card> = emptyList(),
)

@Serializable
@XmlSerialName(
  "Card",
  namespace = "http://ws.gematik.de/conn/CardService/v8.2",
)
data class Card(
  @XmlElement(true)
  @XmlSerialName(
    "CardHandle",
    namespace = "http://ws.gematik.de/conn/ConnectorCommon/v5.0",
  )
  val cardHandle: String,
  @XmlElement(true)
  @XmlSerialName(
    "CardType",
    namespace = "http://ws.gematik.de/conn/CardServiceCommon/v2.0",
  )
  val cardType: CardType,
  @XmlElement(true)
  @XmlSerialName("CardVersion")
  val cardVersion: CardInfoTypeCardVersion? = null,
  @XmlElement(true)
  @XmlSerialName(
    "Iccsn",
    namespace = "http://ws.gematik.de/conn/CardServiceCommon/v2.0",
  )
  val iccsn: String? = null,
  @XmlElement(true)
  @XmlSerialName(
    "CtId",
    namespace = "http://ws.gematik.de/conn/CardServiceCommon/v2.0",
  )
  val ctId: String,
  @XmlElement(true)
  @XmlSerialName(
    "SlotId",
    namespace = "http://ws.gematik.de/conn/CardServiceCommon/v2.0",
  )
  val slotId: Int,
  @XmlElement(true)
  @XmlSerialName("InsertTime")
  val insertTime: String,
  @XmlElement(true)
  @XmlSerialName("CardHolderName")
  val cardHolderName: String? = null,
  @XmlElement(true)
  @XmlSerialName("Kvnr")
  val kvnr: String? = null,
  @XmlElement(true)
  @XmlSerialName("CertificateExpirationDate")
  val certificateExpirationDate: String? = null,
)

@Serializable
@XmlSerialName(
  "VerifyPin",
  namespace = "http://ws.gematik.de/conn/CardService/v8.2",
)
data class VerifyPin(
  @XmlElement(true)
  @XmlSerialName(
    "Context",
    namespace = "http://ws.gematik.de/conn/ConnectorContext/v2.0",
  )
  val context: Context,
  @XmlElement(true)
  @XmlSerialName(
    "CardHandle",
    namespace = "http://ws.gematik.de/conn/ConnectorCommon/v5.0",
  )
  val cardHandle: String,
  @XmlElement(true)
  @XmlSerialName(
    "PinTyp",
    namespace = "http://ws.gematik.de/conn/CardServiceCommon/v2.0",
  )
  val pinTyp: String,
)

@Serializable
@XmlSerialName(
  "VerifyPinResponse",
  namespace = "http://ws.gematik.de/conn/CardService/v8.2",
)
data class VerifyPinResponse(
  @XmlElement(true)
  @XmlSerialName(
    "Status",
    namespace = "http://ws.gematik.de/conn/ConnectorCommon/v5.0",
  )
  val status: Status,
  @XmlElement(true)
  @XmlSerialName(
    "PinResult",
    namespace = "http://ws.gematik.de/conn/CardServiceCommon/v2.0",
  )
  val pinResult: PinResult,
  @XmlElement(true)
  @XmlSerialName(
    "LeftTries",
    namespace = "http://ws.gematik.de/conn/CardServiceCommon/v2.0",
  )
  val leftTries: Int? = null,
)

@Serializable
@XmlSerialName(
  "ChangePin",
  namespace = "http://ws.gematik.de/conn/CardService/v8.2",
)
data class ChangePin(
  @XmlElement(true)
  @XmlSerialName(
    "Context",
    namespace = "http://ws.gematik.de/conn/ConnectorContext/v2.0",
  )
  val context: Context,
  @XmlElement(true)
  @XmlSerialName(
    "CardHandle",
    namespace = "http://ws.gematik.de/conn/ConnectorCommon/v5.0",
  )
  val cardHandle: String,
  @XmlElement(true)
  @XmlSerialName(
    "PinTyp",
    namespace = "http://ws.gematik.de/conn/CardServiceCommon/v2.0",
  )
  val pinTyp: String,
)

@Serializable
@XmlSerialName(
  "ChangePinResponse",
  namespace = "http://ws.gematik.de/conn/CardService/v8.2",
)
data class ChangePinResponse(
  @XmlElement(true)
  @XmlSerialName(
    "Status",
    namespace = "http://ws.gematik.de/conn/ConnectorCommon/v5.0",
  )
  val status: Status,
  @XmlElement(true)
  @XmlSerialName(
    "PinResult",
    namespace = "http://ws.gematik.de/conn/CardServiceCommon/v2.0",
  )
  val pinResult: PinResult,
  @XmlElement(true)
  @XmlSerialName(
    "LeftTries",
    namespace = "http://ws.gematik.de/conn/CardServiceCommon/v2.0",
  )
  val leftTries: Int? = null,
)

@Serializable
@XmlSerialName(
  "GetPinStatus",
  namespace = "http://ws.gematik.de/conn/CardService/v8.2",
)
data class GetPinStatus(
  @XmlElement(true)
  @XmlSerialName(
    "Context",
    namespace = "http://ws.gematik.de/conn/ConnectorContext/v2.0",
  )
  val context: Context,
  @XmlElement(true)
  @XmlSerialName(
    "CardHandle",
    namespace = "http://ws.gematik.de/conn/ConnectorCommon/v5.0",
  )
  val cardHandle: String,
  @XmlElement(true)
  @XmlSerialName(
    "PinTyp",
    namespace = "http://ws.gematik.de/conn/CardServiceCommon/v2.0",
  )
  val pinTyp: String,
)

@Serializable
@XmlSerialName(
  "GetPinStatusResponse",
  namespace = "http://ws.gematik.de/conn/CardService/v8.2",
)
data class GetPinStatusResponse(
  @XmlElement(true)
  @XmlSerialName(
    "Status",
    namespace = "http://ws.gematik.de/conn/ConnectorCommon/v5.0",
  )
  val status: Status,
  @XmlElement(true)
  @XmlSerialName("PinStatus")
  val pinStatus: PinStatusEnum? = null,
  @XmlElement(true)
  @XmlSerialName("LeftTries")
  val leftTries: Int? = null,
)

@Serializable
@XmlSerialName(
  "UnblockPin",
  namespace = "http://ws.gematik.de/conn/CardService/v8.2",
)
data class UnblockPin(
  @XmlElement(true)
  @XmlSerialName(
    "Context",
    namespace = "http://ws.gematik.de/conn/ConnectorContext/v2.0",
  )
  val context: Context,
  @XmlElement(true)
  @XmlSerialName(
    "CardHandle",
    namespace = "http://ws.gematik.de/conn/ConnectorCommon/v5.0",
  )
  val cardHandle: String,
  @XmlElement(true)
  @XmlSerialName(
    "PinTyp",
    namespace = "http://ws.gematik.de/conn/CardServiceCommon/v2.0",
  )
  val pinTyp: String,
  @XmlElement(true)
  @XmlSerialName("SetNewPin")
  val setNewPin: Boolean? = null,
)

@Serializable
@XmlSerialName(
  "UnblockPinResponse",
  namespace = "http://ws.gematik.de/conn/CardService/v8.2",
)
data class UnblockPinResponse(
  @XmlElement(true)
  @XmlSerialName(
    "Status",
    namespace = "http://ws.gematik.de/conn/ConnectorCommon/v5.0",
  )
  val status: Status,
  @XmlElement(true)
  @XmlSerialName(
    "PinResult",
    namespace = "http://ws.gematik.de/conn/CardServiceCommon/v2.0",
  )
  val pinResult: PinResult,
  @XmlElement(true)
  @XmlSerialName(
    "LeftTries",
    namespace = "http://ws.gematik.de/conn/CardServiceCommon/v2.0",
  )
  val leftTries: Int? = null,
)

@Serializable
@XmlSerialName(
  "EnablePin",
  namespace = "http://ws.gematik.de/conn/CardService/v8.2",
)
data class EnablePin(
  @XmlElement(true)
  @XmlSerialName(
    "Context",
    namespace = "http://ws.gematik.de/conn/ConnectorContext/v2.0",
  )
  val context: Context,
  @XmlElement(true)
  @XmlSerialName(
    "CardHandle",
    namespace = "http://ws.gematik.de/conn/ConnectorCommon/v5.0",
  )
  val cardHandle: String,
  @XmlElement(true)
  @XmlSerialName(
    "PinTyp",
    namespace = "http://ws.gematik.de/conn/CardServiceCommon/v2.0",
  )
  val pinTyp: String,
)

@Serializable
@XmlSerialName(
  "EnablePinResponse",
  namespace = "http://ws.gematik.de/conn/CardService/v8.2",
)
data class EnablePinResponse(
  @XmlElement(true)
  @XmlSerialName(
    "Status",
    namespace = "http://ws.gematik.de/conn/ConnectorCommon/v5.0",
  )
  val status: Status,
  @XmlElement(true)
  @XmlSerialName(
    "PinResult",
    namespace = "http://ws.gematik.de/conn/CardServiceCommon/v2.0",
  )
  val pinResult: PinResult,
  @XmlElement(true)
  @XmlSerialName(
    "LeftTries",
    namespace = "http://ws.gematik.de/conn/CardServiceCommon/v2.0",
  )
  val leftTries: Int? = null,
)

@Serializable
@XmlSerialName(
  "DisablePin",
  namespace = "http://ws.gematik.de/conn/CardService/v8.2",
)
data class DisablePin(
  @XmlElement(true)
  @XmlSerialName(
    "Context",
    namespace = "http://ws.gematik.de/conn/ConnectorContext/v2.0",
  )
  val context: Context,
  @XmlElement(true)
  @XmlSerialName(
    "CardHandle",
    namespace = "http://ws.gematik.de/conn/ConnectorCommon/v5.0",
  )
  val cardHandle: String,
  @XmlElement(true)
  @XmlSerialName(
    "PinTyp",
    namespace = "http://ws.gematik.de/conn/CardServiceCommon/v2.0",
  )
  val pinTyp: String,
)

@Serializable
@XmlSerialName(
  "DisablePinResponse",
  namespace = "http://ws.gematik.de/conn/CardService/v8.2",
)
data class DisablePinResponse(
  @XmlElement(true)
  @XmlSerialName(
    "Status",
    namespace = "http://ws.gematik.de/conn/ConnectorCommon/v5.0",
  )
  val status: Status,
  @XmlElement(true)
  @XmlSerialName(
    "PinResult",
    namespace = "http://ws.gematik.de/conn/CardServiceCommon/v2.0",
  )
  val pinResult: PinResult,
  @XmlElement(true)
  @XmlSerialName(
    "LeftTries",
    namespace = "http://ws.gematik.de/conn/CardServiceCommon/v2.0",
  )
  val leftTries: Int? = null,
)

@Serializable
@XmlSerialName(
  "StartCardSession",
  namespace = "http://ws.gematik.de/conn/CardService/v8.2",
)
data class StartCardSession(
  @XmlElement(true)
  @XmlSerialName(
    "Context",
    namespace = "http://ws.gematik.de/conn/ConnectorContext/v2.0",
  )
  val context: Context,
  @XmlElement(true)
  @XmlSerialName(
    "CardHandle",
    namespace = "http://ws.gematik.de/conn/ConnectorCommon/v5.0",
  )
  val cardHandle: String,
)

@Serializable
@XmlSerialName(
  "StartCardSessionResponse",
  namespace = "http://ws.gematik.de/conn/CardService/v8.2",
)
data class StartCardSessionResponse(
  @XmlElement(true)
  @XmlSerialName(
    "Status",
    namespace = "http://ws.gematik.de/conn/ConnectorCommon/v5.0",
  )
  val status: Status,
  @XmlElement(true)
  @XmlSerialName("SessionId")
  val sessionId: String,
)

@Serializable
@XmlSerialName(
  "SecureSendAPDU",
  namespace = "http://ws.gematik.de/conn/CardService/v8.2",
)
data class SecureSendAPDU(
  @XmlElement(true)
  @XmlSerialName("SignedScenario")
  val signedScenario: String? = null,
)

@Serializable
@XmlSerialName(
  "SecureSendAPDUResponse",
  namespace = "http://ws.gematik.de/conn/CardService/v8.2",
)
data class SecureSendAPDUResponse(
  @XmlElement(true)
  @XmlSerialName(
    "Status",
    namespace = "http://ws.gematik.de/conn/ConnectorCommon/v5.0",
  )
  val status: Status,
  @XmlElement(true)
  @XmlSerialName("SignedScenarioResponse")
  val signedScenarioResponse: SignedScenarioResponseType? = null,
)

@Serializable
@XmlSerialName(
  "StopCardSession",
  namespace = "http://ws.gematik.de/conn/CardService/v8.2",
)
data class StopCardSession(
  @XmlElement(true)
  @XmlSerialName("SessionId")
  val sessionId: String,
)

@Serializable
@XmlSerialName(
  "StopCardSessionResponse",
  namespace = "http://ws.gematik.de/conn/CardService/v8.2",
)
data class StopCardSessionResponse(
  @XmlElement(true)
  @XmlSerialName(
    "Status",
    namespace = "http://ws.gematik.de/conn/ConnectorCommon/v5.0",
  )
  val status: Status,
)

@Serializable
enum class RequestCardResultEnum {
  @SerialName("ERROR")
  Error,
  @SerialName("OK")
  Ok,
  @SerialName("ALREADY_INSERTED")
  AlreadyInserted,
}

@Serializable
enum class PinStatusEnum {
  @SerialName("VERIFIED")
  Verified,
  @SerialName("TRANSPORT_PIN")
  TransportPin,
  @SerialName("EMPTY_PIN")
  EmptyPin,
  @SerialName("BLOCKED")
  Blocked,
  @SerialName("VERIFIABLE")
  Verifiable,
  @SerialName("DISABLED")
  Disabled,
}

@Serializable
enum class CommonStepsEnum {
  @SerialName("CheckCardHandle")
  CheckCardHandle,
  @SerialName("VerifyPin")
  VerifyPin,
  @SerialName("VerifyEhcPin")
  VerifyEhcPin,
  @SerialName("VerifyHpcPin")
  VerifyHpcPin,
  @SerialName("VerifySmcPin")
  VerifySmcPin,
  @SerialName("WriteToEhc")
  WriteToEhc,
  @SerialName("ReadFromEhc")
  ReadFromEhc,
  @SerialName("Logging")
  Logging,
  @SerialName("CheckEhcBlocking")
  CheckEhcBlocking,
  @SerialName("FullfillAccessConditions")
  FullfillAccessConditions,
  @SerialName("CardToCard")
  CardToCard,
}

@Serializable
data class VersionInfoType(
  @XmlElement(true)
  @XmlSerialName(
    "Major",
    namespace = "http://ws.gematik.de/conn/CardService/v8.2",
  )
  val major: Int,
  @XmlElement(true)
  @XmlSerialName(
    "Minor",
    namespace = "http://ws.gematik.de/conn/CardService/v8.2",
  )
  val minor: Int,
  @XmlElement(true)
  @XmlSerialName(
    "Revision",
    namespace = "http://ws.gematik.de/conn/CardService/v8.2",
  )
  val revision: Int,
)

@Serializable
data class CardInfoType(
  @XmlElement(true)
  @XmlSerialName(
    "CardHandle",
    namespace = "http://ws.gematik.de/conn/ConnectorCommon/v5.0",
  )
  val cardHandle: String,
  @XmlElement(true)
  @XmlSerialName(
    "CardType",
    namespace = "http://ws.gematik.de/conn/CardServiceCommon/v2.0",
  )
  val cardType: CardType,
  @XmlElement(true)
  @XmlSerialName(
    "CardVersion",
    namespace = "http://ws.gematik.de/conn/CardService/v8.2",
  )
  val cardVersion: CardInfoTypeCardVersion? = null,
  @XmlElement(true)
  @XmlSerialName(
    "Iccsn",
    namespace = "http://ws.gematik.de/conn/CardServiceCommon/v2.0",
  )
  val iccsn: String? = null,
  @XmlElement(true)
  @XmlSerialName(
    "CtId",
    namespace = "http://ws.gematik.de/conn/CardServiceCommon/v2.0",
  )
  val ctId: String,
  @XmlElement(true)
  @XmlSerialName(
    "SlotId",
    namespace = "http://ws.gematik.de/conn/CardServiceCommon/v2.0",
  )
  val slotId: Int,
  @XmlElement(true)
  @XmlSerialName(
    "InsertTime",
    namespace = "http://ws.gematik.de/conn/CardService/v8.2",
  )
  val insertTime: String,
  @XmlElement(true)
  @XmlSerialName(
    "CardHolderName",
    namespace = "http://ws.gematik.de/conn/CardService/v8.2",
  )
  val cardHolderName: String? = null,
  @XmlElement(true)
  @XmlSerialName(
    "Kvnr",
    namespace = "http://ws.gematik.de/conn/CardService/v8.2",
  )
  val kvnr: String? = null,
  @XmlElement(true)
  @XmlSerialName(
    "CertificateExpirationDate",
    namespace = "http://ws.gematik.de/conn/CardService/v8.2",
  )
  val certificateExpirationDate: String? = null,
)

@Serializable
data class CardInfoErrType(
  @XmlElement(true)
  @XmlSerialName(
    "CardHandle",
    namespace = "http://ws.gematik.de/conn/ConnectorCommon/v5.0",
  )
  val cardHandle: String,
  @XmlElement(true)
  @XmlSerialName(
    "CardType",
    namespace = "http://ws.gematik.de/conn/CardServiceCommon/v2.0",
  )
  val cardType: CardType,
  @XmlElement(true)
  @XmlSerialName(
    "CardVersion",
    namespace = "http://ws.gematik.de/conn/CardService/v8.2",
  )
  val cardVersion: CardInfoErrTypeCardVersion? = null,
  @XmlElement(true)
  @XmlSerialName(
    "Iccsn",
    namespace = "http://ws.gematik.de/conn/CardServiceCommon/v2.0",
  )
  val iccsn: String? = null,
  @XmlElement(true)
  @XmlSerialName(
    "CtId",
    namespace = "http://ws.gematik.de/conn/CardServiceCommon/v2.0",
  )
  val ctId: String,
  @XmlElement(true)
  @XmlSerialName(
    "SlotId",
    namespace = "http://ws.gematik.de/conn/CardServiceCommon/v2.0",
  )
  val slotId: Int,
  @XmlElement(true)
  @XmlSerialName(
    "InsertTime",
    namespace = "http://ws.gematik.de/conn/CardService/v8.2",
  )
  val insertTime: String,
  @XmlElement(true)
  @XmlSerialName(
    "CardHolderName",
    namespace = "http://ws.gematik.de/conn/CardService/v8.2",
  )
  val cardHolderName: String? = null,
  @XmlElement(true)
  @XmlSerialName(
    "Kvnr",
    namespace = "http://ws.gematik.de/conn/CardService/v8.2",
  )
  val kvnr: String? = null,
  @XmlElement(true)
  @XmlSerialName(
    "CertificateExpirationDate",
    namespace = "http://ws.gematik.de/conn/CardService/v8.2",
  )
  val certificateExpirationDate: String? = null,
  @XmlElement(true)
  @XmlSerialName(
    "Error",
    namespace = "http://ws.gematik.de/tel/error/v2.0",
  )
  val error: Error? = null,
)

@Serializable
data class SignedScenarioResponseType(
  @XmlElement(true)
  @XmlSerialName(
    "ResponseApduList",
    namespace = "http://ws.gematik.de/conn/CardService/v8.2",
  )
  val responseApduList: SignedScenarioResponseTypeResponseApduList,
  @XmlElement(true)
  @XmlSerialName(
    "TimeSpan",
    namespace = "http://ws.gematik.de/conn/CardService/v8.2",
  )
  val timeSpan: Int,
)

@Serializable
@XmlSerialName(
  "CardVersion",
  namespace = "http://ws.gematik.de/conn/CardService/v8.2",
)
data class CardInfoTypeCardVersion(
  @XmlElement(true)
  @XmlSerialName("COSVersion")
  val cosVersion: VersionInfoType,
  @XmlElement(true)
  @XmlSerialName("ObjectSystemVersion")
  val objectSystemVersion: VersionInfoType,
  @XmlElement(true)
  @XmlSerialName("CardPTPersVersion")
  val cardPtPersVersion: VersionInfoType? = null,
  @XmlElement(true)
  @XmlSerialName("DataStructureVersion")
  val dataStructureVersion: VersionInfoType? = null,
  @XmlElement(true)
  @XmlSerialName("LoggingVersion")
  val loggingVersion: VersionInfoType? = null,
  @XmlElement(true)
  @XmlSerialName("ATRVersion")
  val atrVersion: VersionInfoType? = null,
  @XmlElement(true)
  @XmlSerialName("GDOVersion")
  val gdoVersion: VersionInfoType? = null,
  @XmlElement(true)
  @XmlSerialName("KeyInfoVersion")
  val keyInfoVersion: VersionInfoType? = null,
)

@Serializable
@XmlSerialName(
  "CardVersion",
  namespace = "http://ws.gematik.de/conn/CardService/v8.2",
)
data class CardInfoErrTypeCardVersion(
  @XmlElement(true)
  @XmlSerialName("COSVersion")
  val cosVersion: VersionInfoType,
  @XmlElement(true)
  @XmlSerialName("ObjectSystemVersion")
  val objectSystemVersion: VersionInfoType,
  @XmlElement(true)
  @XmlSerialName("CardPTPersVersion")
  val cardPtPersVersion: VersionInfoType? = null,
  @XmlElement(true)
  @XmlSerialName("DataStructureVersion")
  val dataStructureVersion: VersionInfoType? = null,
  @XmlElement(true)
  @XmlSerialName("LoggingVersion")
  val loggingVersion: VersionInfoType? = null,
  @XmlElement(true)
  @XmlSerialName("ATRVersion")
  val atrVersion: VersionInfoType? = null,
  @XmlElement(true)
  @XmlSerialName("GDOVersion")
  val gdoVersion: VersionInfoType? = null,
  @XmlElement(true)
  @XmlSerialName("KeyInfoVersion")
  val keyInfoVersion: VersionInfoType? = null,
)

@Serializable
@XmlSerialName(
  "ResponseApduList",
  namespace = "http://ws.gematik.de/conn/CardService/v8.2",
)
data class SignedScenarioResponseTypeResponseApduList(
  @XmlElement(true)
  @XmlSerialName("ResponseApdu")
  val responseApdu: List<String> = emptyList(),
)
