// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.gematik.conn.encryptionservice611

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
enum class CommonStepsEnum {
  @SerialName("EncryptXMLData")
  EncryptXMLData,
  @SerialName("DecryptXMLData")
  DecryptXMLData,
}
