// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.gematik.conn.encryptionservice611

import kotlin.String
import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName
import nl.adaptivity.xmlutil.serialization.XmlValue

@Serializable
@XmlSerialName(
  "Element",
  namespace = "http://ws.gematik.de/conn/EncryptionService/v6.1",
)
data class Element(
  @XmlElement(false)
  @XmlSerialName("Type")
  val type: String,
  @XmlValue(true)
  val charData: String,
)
