// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.gematik.conn.encryptionservice611

import de.gematik.connector.api.gematik.conn.connectorcommon50.Document
import de.gematik.connector.api.gematik.conn.connectorcommon50.Status
import kotlin.String
import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName

@Serializable
@XmlSerialName(
  "EncryptDocumentResponse",
  namespace = "http://ws.gematik.de/conn/EncryptionService/v6.1",
)
data class EncryptDocumentResponse(
  @XmlElement(true)
  @XmlSerialName(
    "Status",
    namespace = "http://ws.gematik.de/conn/ConnectorCommon/v5.0",
  )
  val status: Status,
  @XmlElement(true)
  @XmlSerialName("OptionalOutputs")
  val optionalOutputs: String? = null,
  @XmlElement(true)
  @XmlSerialName(
    "Document",
    namespace = "http://ws.gematik.de/conn/ConnectorCommon/v5.0",
  )
  val document: Document? = null,
)
