// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.gematik.conn.encryptionservice611

import de.gematik.connector.api.soap.SoapOperation

object Operations {
  val EncryptDocument: SoapOperation =
      SoapOperation("EncryptDocument", "http://ws.gematik.de/conn/EncryptionService/v6.1#EncryptDocument", "soap11")

  val DecryptDocument: SoapOperation =
      SoapOperation("DecryptDocument", "http://ws.gematik.de/conn/crypt/EncryptionService/v6.1#DecryptDocument", "soap11")
}
