// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.gematik.conn.cardterminalservice11

import de.gematik.connector.api.soap.SoapOperation

object Operations {
  val RequestCard: SoapOperation =
      SoapOperation("RequestCard", "http://ws.gematik.de/conn/CardTerminalService/v1.1#RequestCard", "soap11")

  val EjectCard: SoapOperation =
      SoapOperation("EjectCard", "http://ws.gematik.de/conn/CardTerminalService/v1.1#EjectCard", "soap11")
}
