// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.gematik.conn.cardterminalservice11

import de.gematik.connector.api.gematik.conn.cardservicecommon20.CardType
import de.gematik.connector.api.gematik.conn.connectorcontext20.Context
import kotlin.Int
import kotlin.String
import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName

@Serializable
@XmlSerialName(
  "RequestCard",
  namespace = "http://ws.gematik.de/conn/CardTerminalService/v1.1",
)
data class RequestCard(
  @XmlElement(true)
  @XmlSerialName(
    "Context",
    namespace = "http://ws.gematik.de/conn/ConnectorContext/v2.0",
  )
  val context: Context,
  @XmlElement(true)
  @XmlSerialName("Slot")
  val slot: Slot,
  @XmlElement(true)
  @XmlSerialName(
    "CardType",
    namespace = "http://ws.gematik.de/conn/CardServiceCommon/v2.0",
  )
  val cardType: CardType? = null,
  @XmlElement(true)
  @XmlSerialName("DisplayMsg")
  val displayMsg: String? = null,
  @XmlElement(true)
  @XmlSerialName("TimeOut")
  val timeOut: Int? = null,
)
