// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.gematik.conn.cardterminalservice11

import de.gematik.connector.api.gematik.conn.cardservice81.Card
import de.gematik.connector.api.gematik.conn.connectorcommon50.Status
import kotlin.Boolean
import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName

@Serializable
@XmlSerialName(
  "RequestCardResponse",
  namespace = "http://ws.gematik.de/conn/CardTerminalService/v1.1",
)
data class RequestCardResponse(
  @XmlElement(true)
  @XmlSerialName(
    "Status",
    namespace = "http://ws.gematik.de/conn/ConnectorCommon/v5.0",
  )
  val status: Status,
  @XmlElement(true)
  @XmlSerialName("AlreadyInserted")
  val alreadyInserted: Boolean? = null,
  @XmlElement(true)
  @XmlSerialName(
    "Card",
    namespace = "http://ws.gematik.de/conn/CardService/v8.1",
  )
  val card: Card? = null,
)
