// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.gematik.conn.cardservice820

import de.gematik.connector.api.gematik.conn.cardservicecommon20.CardType
import kotlin.Int
import kotlin.String
import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName

@Serializable
@XmlSerialName(
  "Card",
  namespace = "http://ws.gematik.de/conn/CardService/v8.2",
)
data class Card(
  @XmlElement(true)
  @XmlSerialName(
    "CardHandle",
    namespace = "http://ws.gematik.de/conn/ConnectorCommon/v5.0",
  )
  val cardHandle: String,
  @XmlElement(true)
  @XmlSerialName(
    "CardType",
    namespace = "http://ws.gematik.de/conn/CardServiceCommon/v2.0",
  )
  val cardType: CardType,
  @XmlElement(true)
  @XmlSerialName("CardVersion")
  val cardVersion: CardInfoTypeCardVersion? = null,
  @XmlElement(true)
  @XmlSerialName(
    "Iccsn",
    namespace = "http://ws.gematik.de/conn/CardServiceCommon/v2.0",
  )
  val iccsn: String? = null,
  @XmlElement(true)
  @XmlSerialName(
    "CtId",
    namespace = "http://ws.gematik.de/conn/CardServiceCommon/v2.0",
  )
  val ctId: String,
  @XmlElement(true)
  @XmlSerialName(
    "SlotId",
    namespace = "http://ws.gematik.de/conn/CardServiceCommon/v2.0",
  )
  val slotId: Int,
  @XmlElement(true)
  @XmlSerialName("InsertTime")
  val insertTime: String,
  @XmlElement(true)
  @XmlSerialName("CardHolderName")
  val cardHolderName: String? = null,
  @XmlElement(true)
  @XmlSerialName("Kvnr")
  val kvnr: String? = null,
  @XmlElement(true)
  @XmlSerialName("CertificateExpirationDate")
  val certificateExpirationDate: String? = null,
)
