// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.gematik.conn.cardservice820

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
enum class PinStatusEnum {
  @SerialName("VERIFIED")
  Verified,
  @SerialName("TRANSPORT_PIN")
  TransportPin,
  @SerialName("EMPTY_PIN")
  EmptyPin,
  @SerialName("BLOCKED")
  Blocked,
  @SerialName("VERIFIABLE")
  Verifiable,
  @SerialName("DISABLED")
  Disabled,
}
