// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.gematik.conn.cardservice820

import de.gematik.connector.api.gematik.conn.connectorcommon50.Status
import kotlin.Int
import kotlin.String
import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName

@Serializable
@XmlSerialName(
  "SecureSendAPDUResponse",
  namespace = "http://ws.gematik.de/conn/CardService/v8.2",
)
data class SecureSendAPDUResponse(
  @XmlElement(true)
  @XmlSerialName(
    "Status",
    namespace = "http://ws.gematik.de/conn/ConnectorCommon/v5.0",
  )
  val status: Status,
  @XmlElement(true)
  @XmlSerialName("TransactionResult")
  val transactionResult: String,
  @XmlElement(true)
  @XmlSerialName("TimeSpan")
  val timeSpan: Int,
)
