// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.gematik.conn.cardservice820

import de.gematik.connector.api.oasis.dss10core.SignatureObject
import kotlin.String
import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName

@Serializable
@XmlSerialName(
  "SecureSendAPDU",
  namespace = "http://ws.gematik.de/conn/CardService/v8.2",
)
data class SecureSendAPDU(
  @XmlElement(true)
  @XmlSerialName("TransactionData")
  val transactionData: String,
  @XmlElement(true)
  @XmlSerialName(
    "SignatureObject",
    namespace = "urn:oasis:names:tc:dss:1.0:core:schema",
  )
  val signatureObject: SignatureObject,
  @XmlElement(true)
  @XmlSerialName(
    "X509Certificate",
    namespace = "http://ws.gematik.de/conn/CertificateServiceCommon/v2.0",
  )
  val x509Certificate: String,
)
