// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.gematik.conn.cardservice820

import kotlin.String
import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName

@Serializable
@XmlSerialName(
  "StopCardSession",
  namespace = "http://ws.gematik.de/conn/CardService/v8.2",
)
data class StopCardSession(
  @XmlElement(true)
  @XmlSerialName("SessionId")
  val sessionId: String,
)
