// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.gematik.consumer.signatureservice30

import de.gematik.connector.api.gematik.consumer.consumercommon20.Status
import de.gematik.connector.api.gematik.consumer.encryptionservice30.PrivateKeyOnCard
import de.gematik.connector.api.oasis.dss10core.AdditionalKeyInfo
import de.gematik.connector.api.oasis.dss10core.Base64Data
import de.gematik.connector.api.oasis.dss10core.Properties
import de.gematik.connector.api.oasis.dss10core.Schemas
import de.gematik.connector.api.oasis.dss10core.SignatureObject
import de.gematik.connector.api.oasis.dss10core.VerifyManifestResults
import de.gematik.connector.api.oasis.dssx10profiles.verificationreport.ReturnVerificationReport
import de.gematik.connector.api.oasis.dssx10profiles.verificationreport.VerificationReport
import kotlin.Boolean
import kotlin.String
import kotlin.collections.List
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName

@Serializable
@XmlSerialName(
  "SignDocument",
  namespace = "http://ws.gematik.de/consumer/SignatureService/v3.0",
)
data class SignDocument(
  @XmlElement(true)
  @XmlSerialName(
    "PrivateKeyOnCard",
    namespace = "http://ws.gematik.de/consumer/EncryptionService/v3.0",
  )
  val privateKeyOnCard: PrivateKeyOnCard,
  @XmlElement(true)
  @XmlSerialName("SignRequest")
  val signRequest: List<SignRequest> = emptyList(),
)

@Serializable
@XmlSerialName(
  "SignRequest",
  namespace = "http://ws.gematik.de/consumer/SignatureService/v3.0",
)
data class SignRequest(
  @XmlElement(false)
  @XmlSerialName("RequestID")
  val requestId: String,
  @XmlElement(true)
  @XmlSerialName("OptionalInputs")
  val optionalInputs: SignRequestOptionalInputs? = null,
  @XmlElement(true)
  @XmlSerialName("Document")
  val document: Document,
)

@Serializable
enum class SignatureSchemes {
  @SerialName("RSASSA-PSS")
  RsassaPss,
  @SerialName("RSASSA-PKCS1-v1_5")
  RSASSAPKCS1V15,
}

@Serializable
@XmlSerialName(
  "DocumentWithSignature",
  namespace = "http://ws.gematik.de/consumer/SignatureService/v3.0",
)
data class DocumentWithSignature(
  @XmlElement(false)
  @XmlSerialName("ID")
  val id: String? = null,
  @XmlElement(false)
  @XmlSerialName("RefURI")
  val refUri: String? = null,
  @XmlElement(false)
  @XmlSerialName("RefType")
  val refType: String? = null,
  @XmlElement(false)
  @XmlSerialName("SchemaRefs")
  val schemaRefs: String? = null,
  @XmlElement(false)
  @XmlSerialName("ShortText")
  val shortText: String? = null,
  @XmlElement(true)
  @XmlSerialName(
    "Base64XML",
    namespace = "http://ws.gematik.de/consumer/ConsumerCommon/v2.0",
  )
  val base64Xml: String? = null,
  @XmlElement(true)
  @XmlSerialName(
    "Base64Data",
    namespace = "urn:oasis:names:tc:dss:1.0:core:schema",
  )
  val base64Data: Base64Data? = null,
)

@Serializable
@XmlSerialName(
  "SignDocumentResponse",
  namespace = "http://ws.gematik.de/consumer/SignatureService/v3.0",
)
data class SignDocumentResponse(
  @XmlElement(true)
  @XmlSerialName("SignResponse")
  val signResponse: List<SignResponse> = emptyList(),
)

@Serializable
@XmlSerialName(
  "SignResponse",
  namespace = "http://ws.gematik.de/consumer/SignatureService/v3.0",
)
data class SignResponse(
  @XmlElement(false)
  @XmlSerialName("RequestID")
  val requestId: String,
  @XmlElement(true)
  @XmlSerialName(
    "Status",
    namespace = "http://ws.gematik.de/consumer/ConsumerCommon/v2.0",
  )
  val status: Status,
  @XmlElement(true)
  @XmlSerialName("OptionalOutputs")
  val optionalOutputs: SignResponseOptionalOutputs? = null,
  @XmlElement(true)
  @XmlSerialName(
    "SignatureObject",
    namespace = "urn:oasis:names:tc:dss:1.0:core:schema",
  )
  val signatureObject: SignatureObject? = null,
)

@Serializable
@XmlSerialName(
  "VerifyDocument",
  namespace = "http://ws.gematik.de/consumer/SignatureService/v3.0",
)
data class VerifyDocument(
  @XmlElement(true)
  @XmlSerialName("OptionalInputs")
  val optionalInputs: VerifyDocumentOptionalInputs? = null,
  @XmlElement(true)
  @XmlSerialName("Document")
  val document: Document? = null,
  @XmlElement(true)
  @XmlSerialName(
    "SignatureObject",
    namespace = "urn:oasis:names:tc:dss:1.0:core:schema",
  )
  val signatureObject: SignatureObject? = null,
)

@Serializable
@XmlSerialName(
  "UseVerificationTime",
  namespace = "http://ws.gematik.de/consumer/SignatureService/v3.0",
)
data class UseVerificationTime(
  @XmlElement(true)
  @XmlSerialName(
    "CurrentTime",
    namespace = "urn:oasis:names:tc:dss:1.0:core:schema",
  )
  val currentTime: String? = null,
  @XmlElement(true)
  @XmlSerialName(
    "SpecificTime",
    namespace = "urn:oasis:names:tc:dss:1.0:core:schema",
  )
  val specificTime: String? = null,
  @XmlElement(true)
  val unknownContent: String? = null,
)

@Serializable
@XmlSerialName(
  "VerifyDocumentResponse",
  namespace = "http://ws.gematik.de/consumer/SignatureService/v3.0",
)
data class VerifyDocumentResponse(
  @XmlElement(true)
  @XmlSerialName(
    "Status",
    namespace = "http://ws.gematik.de/consumer/ConsumerCommon/v2.0",
  )
  val status: Status,
  @XmlElement(true)
  @XmlSerialName("VerificationResult")
  val verificationResult: VerificationResultType,
  @XmlElement(true)
  @XmlSerialName("OptionalOutputs")
  val optionalOutputs: VerifyDocumentResponseOptionalOutputs? = null,
)

@Serializable
@XmlSerialName(
  "ExternalAuthenticate",
  namespace = "http://ws.gematik.de/consumer/SignatureService/v3.0",
)
data class ExternalAuthenticate(
  @XmlElement(true)
  @XmlSerialName(
    "CardHandle",
    namespace = "http://ws.gematik.de/consumer/ConsumerCommon/v2.0",
  )
  val cardHandle: String,
  @XmlElement(true)
  @XmlSerialName("OptionalInputs")
  val optionalInputs: ExternalAuthenticateOptionalInputs? = null,
  @XmlElement(true)
  @XmlSerialName("BinaryString")
  val binaryString: BinaryString,
)

@Serializable
@XmlSerialName(
  "ExternalAuthenticateResponse",
  namespace = "http://ws.gematik.de/consumer/SignatureService/v3.0",
)
data class ExternalAuthenticateResponse(
  @XmlElement(true)
  @XmlSerialName(
    "Status",
    namespace = "http://ws.gematik.de/consumer/ConsumerCommon/v2.0",
  )
  val status: Status,
  @XmlElement(true)
  @XmlSerialName(
    "SignatureObject",
    namespace = "urn:oasis:names:tc:dss:1.0:core:schema",
  )
  val signatureObject: SignatureObject? = null,
)

@Serializable
enum class SignatureForm {
  @SerialName("urn:oasis:names:tc:dss:1.0:profiles:AdES:forms:BES")
  UrnOasisNamesTcDss10ProfilesAdESFormsBES,
  @SerialName("urn:oasis:names:tc:dss:1.0:profiles:AdES:forms:ES-T")
  UrnOasisNamesTcDss10ProfilesAdESFormsEST,
  @SerialName("urn:oasis:names:tc:dss:1.0:profiles:AdES:forms:ES-C")
  UrnOasisNamesTcDss10ProfilesAdESFormsESC,
  @SerialName("urn:oasis:names:tc:dss:1.0:profiles:AdES:forms:ES-X")
  UrnOasisNamesTcDss10ProfilesAdESFormsESX,
  @SerialName("urn:oasis:names:tc:dss:1.0:profiles:AdES:forms:ES-X-L")
  UrnOasisNamesTcDss10ProfilesAdESFormsESXL,
}

@Serializable
@XmlSerialName(
  "Document",
  namespace = "http://ws.gematik.de/consumer/SignatureService/v3.0",
)
data class Document(
  @XmlElement(false)
  @XmlSerialName("ID")
  val id: String? = null,
  @XmlElement(false)
  @XmlSerialName("RefURI")
  val refUri: String? = null,
  @XmlElement(false)
  @XmlSerialName("RefType")
  val refType: String? = null,
  @XmlElement(false)
  @XmlSerialName("SchemaRefs")
  val schemaRefs: String? = null,
  @XmlElement(false)
  @XmlSerialName("ShortText")
  val shortText: String? = null,
  @XmlElement(true)
  @XmlSerialName(
    "Base64XML",
    namespace = "http://ws.gematik.de/consumer/ConsumerCommon/v2.0",
  )
  val base64Xml: String? = null,
  @XmlElement(true)
  @XmlSerialName(
    "Base64Data",
    namespace = "urn:oasis:names:tc:dss:1.0:core:schema",
  )
  val base64Data: Base64Data? = null,
)

@Serializable
@XmlSerialName(
  "BinaryString",
  namespace = "http://ws.gematik.de/consumer/SignatureService/v3.0",
)
data class BinaryString(
  @XmlElement(false)
  @XmlSerialName("ID")
  val id: String? = null,
  @XmlElement(false)
  @XmlSerialName("RefURI")
  val refUri: String? = null,
  @XmlElement(false)
  @XmlSerialName("RefType")
  val refType: String? = null,
  @XmlElement(false)
  @XmlSerialName("SchemaRefs")
  val schemaRefs: String? = null,
  @XmlElement(true)
  @XmlSerialName(
    "Base64Data",
    namespace = "urn:oasis:names:tc:dss:1.0:core:schema",
  )
  val base64Data: Base64Data,
)

@Serializable
@XmlSerialName(
  "CounterSignatureMarker",
  namespace = "http://ws.gematik.de/consumer/SignatureService/v3.0",
)
data class CounterSignatureMarker(
  @XmlElement(true)
  @XmlSerialName("SignatureValueReference")
  val signatureValueReference:
      List<CounterSignatureMarkerSignatureValueReference> = emptyList(),
)

@Serializable
@XmlSerialName(
  "DisplayableAttributes",
  namespace = "http://ws.gematik.de/consumer/SignatureService/v3.0",
)
data class DisplayableAttributes(
  @XmlElement(true)
  @XmlSerialName("DisplayableAttribute")
  val displayableAttribute: List<DisplayableAttributesDisplayableAttribute> = emptyList(),
)

@Serializable
data class DocumentType(
  @XmlElement(false)
  @XmlSerialName("ID")
  val id: String? = null,
  @XmlElement(false)
  @XmlSerialName("RefURI")
  val refUri: String? = null,
  @XmlElement(false)
  @XmlSerialName("RefType")
  val refType: String? = null,
  @XmlElement(false)
  @XmlSerialName("SchemaRefs")
  val schemaRefs: String? = null,
  @XmlElement(false)
  @XmlSerialName("ShortText")
  val shortText: String? = null,
  @XmlElement(true)
  @XmlSerialName(
    "Base64XML",
    namespace = "http://ws.gematik.de/consumer/ConsumerCommon/v2.0",
  )
  val base64Xml: String? = null,
  @XmlElement(true)
  @XmlSerialName(
    "Base64Data",
    namespace = "urn:oasis:names:tc:dss:1.0:core:schema",
  )
  val base64Data: Base64Data? = null,
)

@Serializable
data class BinaryDocumentType(
  @XmlElement(false)
  @XmlSerialName("ID")
  val id: String? = null,
  @XmlElement(false)
  @XmlSerialName("RefURI")
  val refUri: String? = null,
  @XmlElement(false)
  @XmlSerialName("RefType")
  val refType: String? = null,
  @XmlElement(false)
  @XmlSerialName("SchemaRefs")
  val schemaRefs: String? = null,
  @XmlElement(true)
  @XmlSerialName(
    "Base64Data",
    namespace = "urn:oasis:names:tc:dss:1.0:core:schema",
  )
  val base64Data: Base64Data,
)

@Serializable
data class VerificationResultType(
  @XmlElement(true)
  @XmlSerialName(
    "HighLevelResult",
    namespace = "http://ws.gematik.de/consumer/SignatureService/v3.0",
  )
  val highLevelResult: String,
  @XmlElement(true)
  @XmlSerialName(
    "TimestampType",
    namespace = "http://ws.gematik.de/consumer/SignatureService/v3.0",
  )
  val timestampType: String,
  @XmlElement(true)
  @XmlSerialName(
    "Timestamp",
    namespace = "http://ws.gematik.de/consumer/SignatureService/v3.0",
  )
  val timestamp: String,
)

@Serializable
@XmlSerialName(
  "OptionalInputs",
  namespace = "http://ws.gematik.de/consumer/SignatureService/v3.0",
)
data class SignRequestOptionalInputs(
  @XmlElement(true)
  @XmlSerialName(
    "SignatureType",
    namespace = "urn:oasis:names:tc:dss:1.0:core:schema",
  )
  val signatureType: String? = null,
  @XmlElement(true)
  @XmlSerialName(
    "Properties",
    namespace = "urn:oasis:names:tc:dss:1.0:core:schema",
  )
  val properties: Properties? = null,
  @XmlElement(true)
  @XmlSerialName("IncludeEContent")
  val includeEnvelopedContent: Boolean? = null,
)

@Serializable
@XmlSerialName(
  "OptionalOutputs",
  namespace = "http://ws.gematik.de/consumer/SignatureService/v3.0",
)
data class SignResponseOptionalOutputs(
  @XmlElement(true)
  @XmlSerialName("DocumentWithSignature")
  val documentWithSignature: DocumentWithSignature? = null,
  @XmlElement(true)
  @XmlSerialName(
    "VerificationReport",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val verificationReport: VerificationReport? = null,
)

@Serializable
@XmlSerialName(
  "OptionalInputs",
  namespace = "http://ws.gematik.de/consumer/SignatureService/v3.0",
)
data class VerifyDocumentOptionalInputs(
  @XmlElement(true)
  @XmlSerialName("VerifyManifests")
  val verifyManifests: String? = null,
  @XmlElement(true)
  @XmlSerialName("UseVerificationTime")
  val useVerificationTime: UseVerificationTime? = null,
  @XmlElement(true)
  @XmlSerialName(
    "AdditionalKeyInfo",
    namespace = "urn:oasis:names:tc:dss:1.0:core:schema",
  )
  val additionalKeyInfo: AdditionalKeyInfo? = null,
  @XmlElement(true)
  @XmlSerialName(
    "ReturnVerificationReport",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val returnVerificationReport: ReturnVerificationReport? = null,
  @XmlElement(true)
  @XmlSerialName(
    "Schemas",
    namespace = "urn:oasis:names:tc:dss:1.0:core:schema",
  )
  val schemas: Schemas? = null,
)

@Serializable
@XmlSerialName(
  "OptionalOutputs",
  namespace = "http://ws.gematik.de/consumer/SignatureService/v3.0",
)
data class VerifyDocumentResponseOptionalOutputs(
  @XmlElement(true)
  @XmlSerialName(
    "VerifyManifestResults",
    namespace = "urn:oasis:names:tc:dss:1.0:core:schema",
  )
  val verifyManifestResults: VerifyManifestResults? = null,
  @XmlElement(true)
  @XmlSerialName(
    "VerificationReport",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val verificationReport: VerificationReport? = null,
)

@Serializable
@XmlSerialName(
  "OptionalInputs",
  namespace = "http://ws.gematik.de/consumer/SignatureService/v3.0",
)
data class ExternalAuthenticateOptionalInputs(
  @XmlElement(true)
  @XmlSerialName(
    "SignatureType",
    namespace = "urn:oasis:names:tc:dss:1.0:core:schema",
  )
  val signatureType: String? = null,
  @XmlElement(true)
  @XmlSerialName("SignatureSchemes")
  val signatureSchemes: SignatureSchemes? = null,
)

@Serializable
@XmlSerialName(
  "SignatureValueReference",
  namespace = "http://ws.gematik.de/consumer/SignatureService/v3.0",
)
data class CounterSignatureMarkerSignatureValueReference(
  @XmlElement(false)
  @XmlSerialName("IdRef")
  val idRef: String? = null,
)

@Serializable
@XmlSerialName(
  "DisplayableAttribute",
  namespace = "http://ws.gematik.de/consumer/SignatureService/v3.0",
)
data class DisplayableAttributesDisplayableAttribute(
  @XmlElement(true)
  @XmlSerialName("Key")
  val key: String,
  @XmlElement(true)
  @XmlSerialName("Value")
  val `value`: String,
)
