// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.gematik.conn.cardservicecommon20

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
enum class CardTypeType {
  @SerialName("EGK")
  Egk,
  @SerialName("HBA-qSig")
  HBAQSig,
  @SerialName("HBA")
  Hba,
  @SerialName("SMC-B")
  SmcB,
  @SerialName("HSM-B")
  HsmB,
  @SerialName("SMC-KT")
  SmcKt,
  @SerialName("KVK")
  Kvk,
  @SerialName("ZOD_2.0")
  Zod20,
  @SerialName("UNKNOWN")
  Unknown,
  @SerialName("HBAx")
  HBAx,
  @SerialName("SM-B")
  SmB,
}
