// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.gematik.conn.cardservicecommon20

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
enum class PinResultEnum {
  @SerialName("ERROR")
  Error,
  @SerialName("OK")
  Ok,
  @SerialName("REJECTED")
  Rejected,
  @SerialName("WASBLOCKED")
  Wasblocked,
  @SerialName("NOWBLOCKED")
  Nowblocked,
  @SerialName("TRANSPORT_PIN")
  TransportPin,
}
