// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.gematik.conn.signatureservice75

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
enum class ComfortSignatureStatusEnum {
  @SerialName("ENABLED")
  Enabled,
  @SerialName("DISABLED")
  Disabled,
}
