// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.gematik.conn.signatureservice75

import kotlin.String
import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName

@Serializable
@XmlSerialName(
  "SignatureValueReference",
  namespace = "http://ws.gematik.de/conn/SignatureService/v7.5",
)
data class CounterSignatureMarkerSignatureValueReference(
  @XmlElement(false)
  @XmlSerialName("IdRef")
  val idRef: String? = null,
)
