// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.gematik.conn.signatureservice75

import de.gematik.connector.api.gematik.conn.connectorcommon50.Status
import kotlin.Int
import kotlin.String
import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName

@Serializable
@XmlSerialName(
  "GetSignatureModeResponse",
  namespace = "http://ws.gematik.de/conn/SignatureService/v7.5",
)
data class GetSignatureModeResponse(
  @XmlElement(true)
  @XmlSerialName(
    "Status",
    namespace = "http://ws.gematik.de/conn/ConnectorCommon/v5.0",
  )
  val status: Status,
  @XmlElement(true)
  @XmlSerialName("ComfortSignatureStatus")
  val comfortSignatureStatus: ComfortSignatureStatusEnum,
  @XmlElement(true)
  @XmlSerialName("ComfortSignatureMax")
  val comfortSignatureMax: Int,
  @XmlElement(true)
  @XmlSerialName("ComfortSignatureTimer")
  val comfortSignatureTimer: String,
  @XmlElement(true)
  @XmlSerialName("SessionInfo")
  val sessionInfo: SessionInfo? = null,
)
