// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.gematik.conn.signatureservice75

import kotlin.Int
import kotlin.String
import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName

@Serializable
@XmlSerialName(
  "SessionInfo",
  namespace = "http://ws.gematik.de/conn/SignatureService/v7.5",
)
data class SessionInfo(
  @XmlElement(true)
  @XmlSerialName("SignatureMode")
  val signatureMode: SignatureMode,
  @XmlElement(true)
  @XmlSerialName("CountRemaining")
  val countRemaining: Int,
  @XmlElement(true)
  @XmlSerialName("TimeRemaining")
  val timeRemaining: String,
)
