// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.gematik.conn.signatureservice75

import de.gematik.connector.api.oasis.dss10core.IncludeObject
import kotlin.collections.List
import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName

@Serializable
@XmlSerialName(
  "IncludeObjects",
  namespace = "http://ws.gematik.de/conn/SignatureService/v7.5",
)
data class SignRequestOptionalInputsIncludeObjects(
  @XmlElement(true)
  @XmlSerialName(
    "IncludeObject",
    namespace = "urn:oasis:names:tc:dss:1.0:core:schema",
  )
  val includeObject: List<IncludeObject> = emptyList(),
)
