// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.gematik.conn.signatureservice75

import kotlin.collections.List
import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName

@Serializable
@XmlSerialName(
  "SignDocumentResponse",
  namespace = "http://ws.gematik.de/conn/SignatureService/v7.5",
)
data class SignDocumentResponse(
  @XmlElement(true)
  @XmlSerialName("SignResponse")
  val signResponse: List<SignResponse> = emptyList(),
)
