// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.gematik.conn.signatureservice75

interface SignatureServicePort {
  fun verifyDocument(request: VerifyDocument): VerifyDocumentResponse

  fun signDocument(request: SignDocument): SignDocumentResponse

  fun getJobNumber(request: GetJobNumber): GetJobNumberResponse

  fun stopSignature(request: StopSignature): StopSignatureResponse

  fun activateComfortSignature(request: ActivateComfortSignature): ActivateComfortSignatureResponse

  fun deactivateComfortSignature(request: DeactivateComfortSignature): DeactivateComfortSignatureResponse

  fun getSignatureMode(request: GetSignatureMode): GetSignatureModeResponse
}
