// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.gematik.conn.signatureservice75

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
enum class SignatureSchemes {
  @SerialName("RSASSA-PSS")
  RsassaPss,
  @SerialName("RSASSA-PKCS1-v1_5")
  RSASSAPKCS1V15,
}
