// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.gematik.conn.signatureservice75

import de.gematik.connector.api.gematik.conn.connectorcontext20.Context
import kotlin.String
import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName

@Serializable
@XmlSerialName(
  "StopSignature",
  namespace = "http://ws.gematik.de/conn/SignatureService/v7.5",
)
data class StopSignature(
  @XmlElement(true)
  @XmlSerialName(
    "Context",
    namespace = "http://ws.gematik.de/conn/ConnectorContext/v2.0",
  )
  val context: Context,
  @XmlElement(true)
  @XmlSerialName("JobNumber")
  val jobNumber: String,
)
