// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.gematik.conn.signatureservice75

import de.gematik.connector.api.gematik.conn.connectorcommon50.Status
import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName

@Serializable
@XmlSerialName(
  "VerifyDocumentResponse",
  namespace = "http://ws.gematik.de/conn/SignatureService/v7.5",
)
data class VerifyDocumentResponse(
  @XmlElement(true)
  @XmlSerialName(
    "Status",
    namespace = "http://ws.gematik.de/conn/ConnectorCommon/v5.0",
  )
  val status: Status,
  @XmlElement(true)
  @XmlSerialName("VerificationResult")
  val verificationResult: VerificationResultType,
  @XmlElement(true)
  @XmlSerialName("OptionalOutputs")
  val optionalOutputs: VerifyDocumentResponseOptionalOutputs? = null,
)
