// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.gematik.conn.connectorcommon50

import kotlin.collections.List
import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName

@Serializable
@XmlSerialName(
  "OperatingState",
  namespace = "http://ws.gematik.de/conn/ConnectorCommon/v5.0",
)
data class OperatingState(
  @XmlElement(true)
  @XmlSerialName("ErrorState")
  val errorState: List<ErrorState> = emptyList(),
)
