// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.gematik.conn.connectorcommon50

import de.gematik.connector.api.gematik.tel.error20.Error
import de.gematik.connector.api.oasis.dss10core.Base64Data
import kotlin.Boolean
import kotlin.String
import kotlin.collections.List
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName

@Serializable
@XmlSerialName(
  "Status",
  namespace = "http://ws.gematik.de/conn/ConnectorCommon/v5.0",
)
data class Status(
  @XmlElement(true)
  @XmlSerialName("Result")
  val result: Result,
  @XmlElement(true)
  @XmlSerialName(
    "Error",
    namespace = "http://ws.gematik.de/tel/error/v2.0",
  )
  val error: Error? = null,
)

@Serializable
enum class Result {
  @SerialName("OK")
  Ok,
  @SerialName("Warning")
  Warning,
}

@Serializable
@XmlSerialName(
  "WorkplaceIds",
  namespace = "http://ws.gematik.de/conn/ConnectorCommon/v5.0",
)
data class WorkplaceIds(
  @XmlElement(true)
  @XmlSerialName("WorkplaceId")
  val workplaceId: List<String> = emptyList(),
)

@Serializable
@XmlSerialName(
  "Connector",
  namespace = "http://ws.gematik.de/conn/ConnectorCommon/v5.0",
)
data class Connector(
  @XmlElement(true)
  @XmlSerialName("VPNTIStatus")
  val vpnTiStatus: ConnectorVpnTiStatus,
  @XmlElement(true)
  @XmlSerialName("VPNSISStatus")
  val vpnSisStatus: ConnectorVpnSisStatus,
  @XmlElement(true)
  @XmlSerialName("OperatingState")
  val operatingState: OperatingState,
)

@Serializable
@XmlSerialName(
  "ErrorState",
  namespace = "http://ws.gematik.de/conn/ConnectorCommon/v5.0",
)
data class ErrorState(
  @XmlElement(true)
  @XmlSerialName("ErrorCondition")
  val errorCondition: String,
  @XmlElement(true)
  @XmlSerialName("Severity")
  val severity: String,
  @XmlElement(true)
  @XmlSerialName("Type")
  val type: String,
  @XmlElement(true)
  @XmlSerialName("Value")
  val `value`: Boolean,
  @XmlElement(true)
  @XmlSerialName("ValidFrom")
  val validFrom: String,
)

@Serializable
@XmlSerialName(
  "Document",
  namespace = "http://ws.gematik.de/conn/ConnectorCommon/v5.0",
)
data class Document(
  @XmlElement(false)
  @XmlSerialName("ID")
  val id: String? = null,
  @XmlElement(false)
  @XmlSerialName("RefURI")
  val refUri: String? = null,
  @XmlElement(false)
  @XmlSerialName("RefType")
  val refType: String? = null,
  @XmlElement(false)
  @XmlSerialName("SchemaRefs")
  val schemaRefs: String? = null,
  @XmlElement(true)
  @XmlSerialName("Base64XML")
  val base64Xml: String? = null,
  @XmlElement(true)
  @XmlSerialName(
    "Base64Data",
    namespace = "urn:oasis:names:tc:dss:1.0:core:schema",
  )
  val base64Data: Base64Data? = null,
)

@Serializable
@XmlSerialName(
  "OperatingState",
  namespace = "http://ws.gematik.de/conn/ConnectorCommon/v5.0",
)
data class OperatingState(
  @XmlElement(true)
  @XmlSerialName("ErrorState")
  val errorState: List<ErrorState> = emptyList(),
)

@Serializable
@XmlSerialName(
  "XmlSchema",
  namespace = "http://ws.gematik.de/conn/ConnectorCommon/v5.0",
)
data class XmlSchema(
  @XmlElement(true)
  @XmlSerialName("Data")
  val `data`: String,
  @XmlElement(true)
  @XmlSerialName("RefURI")
  val refUri: String,
)

@Serializable
@XmlSerialName(
  "XslStylesheet",
  namespace = "http://ws.gematik.de/conn/ConnectorCommon/v5.0",
)
data class XslStylesheet(
  @XmlElement(true)
  @XmlSerialName("Data")
  val `data`: String,
  @XmlElement(true)
  @XmlSerialName("RefURI")
  val refUri: String,
)

@Serializable
enum class ResultEnum {
  @SerialName("ERROR")
  Error,
  @SerialName("OK")
  Ok,
  @SerialName("WARNING")
  Warning,
}

@Serializable
data class AttachmentType(
  @XmlElement(true)
  @XmlSerialName(
    "Data",
    namespace = "http://ws.gematik.de/conn/ConnectorCommon/v5.0",
  )
  val `data`: String,
  @XmlElement(true)
  @XmlSerialName(
    "RefURI",
    namespace = "http://ws.gematik.de/conn/ConnectorCommon/v5.0",
  )
  val refUri: String,
)

@Serializable
data class DocumentType(
  @XmlElement(false)
  @XmlSerialName("ID")
  val id: String? = null,
  @XmlElement(false)
  @XmlSerialName("RefURI")
  val refUri: String? = null,
  @XmlElement(false)
  @XmlSerialName("RefType")
  val refType: String? = null,
  @XmlElement(false)
  @XmlSerialName("SchemaRefs")
  val schemaRefs: String? = null,
  @XmlElement(true)
  @XmlSerialName(
    "Base64XML",
    namespace = "http://ws.gematik.de/conn/ConnectorCommon/v5.0",
  )
  val base64Xml: String? = null,
  @XmlElement(true)
  @XmlSerialName(
    "Base64Data",
    namespace = "urn:oasis:names:tc:dss:1.0:core:schema",
  )
  val base64Data: Base64Data? = null,
)

@Serializable
@XmlSerialName(
  "VPNTIStatus",
  namespace = "http://ws.gematik.de/conn/ConnectorCommon/v5.0",
)
data class ConnectorVpnTiStatus(
  @XmlElement(true)
  @XmlSerialName("ConnectionStatus")
  val connectionStatus: String,
  @XmlElement(true)
  @XmlSerialName("Timestamp")
  val timestamp: String,
)

@Serializable
@XmlSerialName(
  "VPNSISStatus",
  namespace = "http://ws.gematik.de/conn/ConnectorCommon/v5.0",
)
data class ConnectorVpnSisStatus(
  @XmlElement(true)
  @XmlSerialName("ConnectionStatus")
  val connectionStatus: String,
  @XmlElement(true)
  @XmlSerialName("Timestamp")
  val timestamp: String,
)
