// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.gematik.conn.connectorcommon50

import de.gematik.connector.api.gematik.tel.error20.Error
import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName

@Serializable
@XmlSerialName(
  "Status",
  namespace = "http://ws.gematik.de/conn/ConnectorCommon/v5.0",
)
data class Status(
  @XmlElement(true)
  @XmlSerialName("Result")
  val result: Result,
  @XmlElement(true)
  @XmlSerialName(
    "Error",
    namespace = "http://ws.gematik.de/tel/error/v2.0",
  )
  val error: Error? = null,
)
