// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.gematik.conn.connectorcommon50

import kotlin.String
import kotlin.collections.List
import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName

@Serializable
@XmlSerialName(
  "WorkplaceIds",
  namespace = "http://ws.gematik.de/conn/ConnectorCommon/v5.0",
)
data class WorkplaceIds(
  @XmlElement(true)
  @XmlSerialName("WorkplaceId")
  val workplaceId: List<String> = emptyList(),
)
