// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.gematik.conn.connectorcommon50

import kotlin.String
import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName

@Serializable
@XmlSerialName(
  "XmlSchema",
  namespace = "http://ws.gematik.de/conn/ConnectorCommon/v5.0",
)
data class XmlSchema(
  @XmlElement(true)
  @XmlSerialName("Data")
  val `data`: String,
  @XmlElement(true)
  @XmlSerialName("RefURI")
  val refUri: String,
)
