// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.oasis.dssx10profiles.signaturepolicy

import kotlin.collections.List
import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName

@Serializable
data class PolicySignaturePairsType(
  @XmlElement(true)
  @XmlSerialName(
    "PolicySignaturePair",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:SignaturePolicy:schema#",
  )
  val policySignaturePair: List<PolicySignaturePair> = emptyList(),
)
