// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.oasis.dssx10profiles.signaturepolicy

import de.gematik.connector.api.etsi01903132.DigestAlgAndValueType
import de.gematik.connector.api.oasis.dss10core.AnyType
import de.gematik.connector.api.oasis.dssx10profiles.verificationreport.SignedPropertiesType
import de.gematik.connector.api.w3200009.xmldsig.CanonicalizationMethod
import de.gematik.connector.api.w3200009.xmldsig.SignatureValue
import kotlin.Int
import kotlin.String
import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName

@Serializable
@XmlSerialName(
  "SignatureIdentifier",
  namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:SignaturePolicy:schema#",
)
data class SignatureIdentifier(
  @XmlElement(false)
  @XmlSerialName("WhichDocument")
  val whichDocument: String? = null,
  @XmlElement(false)
  @XmlSerialName("XPath")
  val xPath: String? = null,
  @XmlElement(false)
  @XmlSerialName("Offset")
  val offset: Int? = null,
  @XmlElement(false)
  @XmlSerialName("FieldName")
  val fieldName: String? = null,
  @XmlElement(true)
  @XmlSerialName(
    "DigestAlgAndValue",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val digestAlgAndValue: DigestAlgAndValueType? = null,
  @XmlElement(true)
  @XmlSerialName(
    "CanonicalizationMethod",
    namespace = "http://www.w3.org/2000/09/xmldsig#",
  )
  val canonicalizationMethod: CanonicalizationMethod? = null,
  @XmlElement(true)
  @XmlSerialName(
    "SignedProperties",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val signedProperties: SignedPropertiesType? = null,
  @XmlElement(true)
  @XmlSerialName(
    "SignatureValue",
    namespace = "http://www.w3.org/2000/09/xmldsig#",
  )
  val signatureValue: SignatureValue? = null,
  @XmlElement(true)
  @XmlSerialName(
    "Other",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema#",
  )
  val other: AnyType? = null,
)
