// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.oasis.dssx10profiles.signaturepolicy

import kotlin.collections.List
import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName

@Serializable
@XmlSerialName(
  "SupportedSignaturePolicies",
  namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:SignaturePolicy:schema#",
)
data class SupportedSignaturePolicies(
  @XmlElement(true)
  @XmlSerialName("SupportedSignaturePolicy")
  val supportedSignaturePolicy: List<SignaturePolicyDetailsType> = emptyList(),
)
