// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.oasis.dssx10profiles.signaturepolicy

import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName

@Serializable
data class VerifyUnderSignaturePolicyType(
  @XmlElement(true)
  @XmlSerialName(
    "DefaultPolicy",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:SignaturePolicy:schema#",
  )
  val defaultPolicy: SignaturePolicyDetailsType? = null,
  @XmlElement(true)
  @XmlSerialName(
    "ExplicitPolicies",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:SignaturePolicy:schema#",
  )
  val explicitPolicies: ExplicitPolicies? = null,
)
