// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.oasis.dssx10profiles.signaturepolicy

import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName

@Serializable
data class VerifiedUnderSignaturePolicyType(
  @XmlElement(true)
  @XmlSerialName(
    "SignaturePolicy",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:SignaturePolicy:schema#",
  )
  val signaturePolicy: SignaturePolicy,
  @XmlElement(true)
  @XmlSerialName(
    "SignatureIdentifier",
    namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:SignaturePolicy:schema#",
  )
  val signatureIdentifier: SignatureIdentifier? = null,
)
