// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.oasis.dssx10profiles.signaturepolicy

import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName

@Serializable
@XmlSerialName(
  "VerifyUnderSignaturePolicy",
  namespace = "urn:oasis:names:tc:dss-x:1.0:profiles:SignaturePolicy:schema#",
)
data class VerifyUnderSignaturePolicy(
  @XmlElement(true)
  @XmlSerialName("DefaultPolicy")
  val defaultPolicy: SignaturePolicyDetailsType? = null,
  @XmlElement(true)
  @XmlSerialName("ExplicitPolicies")
  val explicitPolicies: ExplicitPolicies? = null,
)
