// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.gematik.conn.encryptionservice61

import de.gematik.connector.api.gematik.conn.connectorcommon50.Document
import de.gematik.connector.api.gematik.conn.connectorcontext20.Context
import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName

@Serializable
@XmlSerialName(
  "EncryptDocument",
  namespace = "http://ws.gematik.de/conn/EncryptionService/v6.1",
)
data class EncryptDocument(
  @XmlElement(true)
  @XmlSerialName(
    "Context",
    namespace = "http://ws.gematik.de/conn/ConnectorContext/v2.0",
  )
  val context: Context,
  @XmlElement(true)
  @XmlSerialName("RecipientKeys")
  val recipientKeys: EncryptDocumentRecipientKeys,
  @XmlElement(true)
  @XmlSerialName(
    "Document",
    namespace = "http://ws.gematik.de/conn/ConnectorCommon/v5.0",
  )
  val document: Document,
  @XmlElement(true)
  @XmlSerialName("OptionalInputs")
  val optionalInputs: EncryptDocumentOptionalInputs? = null,
)
