// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.gematik.conn.encryptionservice61

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
enum class EncryptionStepResultEnum {
  @SerialName("ERROR")
  Error,
  @SerialName("OK")
  Ok,
}
