// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.gematik.conn.encryptionservice61

import de.gematik.connector.api.gematik.tel.error20.Error
import de.gematik.connector.api.soap.SoapEnvelope
import kotlin.Boolean
import kotlin.String
import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName

@Serializable
@XmlSerialName(
  "Envelope",
  namespace = "http://schemas.xmlsoap.org/soap/envelope/",
  prefix = "SOAP-ENV",
)
data class EncryptDocumentEnvelope(
  @XmlElement(true)
  @XmlSerialName(
    "Body",
    namespace = "http://schemas.xmlsoap.org/soap/envelope/",
    prefix = "SOAP-ENV",
  )
  val body: Body,
) : SoapEnvelope {
  override fun isFault(): Boolean = false

  @Serializable
  data class Body(
    @XmlElement(true)
    val encryptDocument: EncryptDocument? = null,
  )
}

@Serializable
@XmlSerialName(
  "Envelope",
  namespace = "http://schemas.xmlsoap.org/soap/envelope/",
  prefix = "SOAP-ENV",
)
data class EncryptDocumentResponseEnvelope(
  @XmlElement(true)
  @XmlSerialName(
    "Body",
    namespace = "http://schemas.xmlsoap.org/soap/envelope/",
    prefix = "SOAP-ENV",
  )
  val body: Body,
) : SoapEnvelope {
  override fun isFault(): Boolean = body.fault != null

  @Serializable
  data class Body(
    @XmlElement(true)
    val encryptDocumentResponse: EncryptDocumentResponse? = null,
    @XmlElement(true)
    @XmlSerialName(
      "Fault",
      namespace = "http://schemas.xmlsoap.org/soap/envelope/",
      prefix = "SOAP-ENV",
    )
    val fault: Fault? = null,
  )

  @Serializable
  data class Fault(
    @XmlElement(true)
    val faultcode: String = "",
    @XmlElement(true)
    val faultstring: String = "",
    @XmlElement(true)
    val faultactor: String? = null,
    @XmlElement(true)
    val detail: Error? = null,
  )
}

@Serializable
@XmlSerialName(
  "Envelope",
  namespace = "http://schemas.xmlsoap.org/soap/envelope/",
  prefix = "SOAP-ENV",
)
data class DecryptDocumentEnvelope(
  @XmlElement(true)
  @XmlSerialName(
    "Body",
    namespace = "http://schemas.xmlsoap.org/soap/envelope/",
    prefix = "SOAP-ENV",
  )
  val body: Body,
) : SoapEnvelope {
  override fun isFault(): Boolean = false

  @Serializable
  data class Body(
    @XmlElement(true)
    val decryptDocument: DecryptDocument? = null,
  )
}

@Serializable
@XmlSerialName(
  "Envelope",
  namespace = "http://schemas.xmlsoap.org/soap/envelope/",
  prefix = "SOAP-ENV",
)
data class DecryptDocumentResponseEnvelope(
  @XmlElement(true)
  @XmlSerialName(
    "Body",
    namespace = "http://schemas.xmlsoap.org/soap/envelope/",
    prefix = "SOAP-ENV",
  )
  val body: Body,
) : SoapEnvelope {
  override fun isFault(): Boolean = body.fault != null

  @Serializable
  data class Body(
    @XmlElement(true)
    val decryptDocumentResponse: DecryptDocumentResponse? = null,
    @XmlElement(true)
    @XmlSerialName(
      "Fault",
      namespace = "http://schemas.xmlsoap.org/soap/envelope/",
      prefix = "SOAP-ENV",
    )
    val fault: Fault? = null,
  )

  @Serializable
  data class Fault(
    @XmlElement(true)
    val faultcode: String = "",
    @XmlElement(true)
    val faultstring: String = "",
    @XmlElement(true)
    val faultactor: String? = null,
    @XmlElement(true)
    val detail: Error? = null,
  )
}
