// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.gematik.conn.encryptionservice61

import de.gematik.connector.api.gematik.conn.connectorcommon50.Document
import de.gematik.connector.api.gematik.conn.connectorcommon50.Status
import de.gematik.connector.api.gematik.conn.connectorcontext20.Context
import de.gematik.connector.api.oasis.dss10core.Property
import kotlin.String
import kotlin.collections.List
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName
import nl.adaptivity.xmlutil.serialization.XmlValue

@Serializable
@XmlSerialName(
  "EncryptDocument",
  namespace = "http://ws.gematik.de/conn/EncryptionService/v6.1",
)
data class EncryptDocument(
  @XmlElement(true)
  @XmlSerialName(
    "Context",
    namespace = "http://ws.gematik.de/conn/ConnectorContext/v2.0",
  )
  val context: Context,
  @XmlElement(true)
  @XmlSerialName("RecipientKeys")
  val recipientKeys: EncryptDocumentRecipientKeys,
  @XmlElement(true)
  @XmlSerialName(
    "Document",
    namespace = "http://ws.gematik.de/conn/ConnectorCommon/v5.0",
  )
  val document: Document,
  @XmlElement(true)
  @XmlSerialName("OptionalInputs")
  val optionalInputs: EncryptDocumentOptionalInputs? = null,
)

@Serializable
@XmlSerialName(
  "EncryptDocumentResponse",
  namespace = "http://ws.gematik.de/conn/EncryptionService/v6.1",
)
data class EncryptDocumentResponse(
  @XmlElement(true)
  @XmlSerialName(
    "Status",
    namespace = "http://ws.gematik.de/conn/ConnectorCommon/v5.0",
  )
  val status: Status,
  @XmlElement(true)
  @XmlSerialName("OptionalOutputs")
  val optionalOutputs: String? = null,
  @XmlElement(true)
  @XmlSerialName(
    "Document",
    namespace = "http://ws.gematik.de/conn/ConnectorCommon/v5.0",
  )
  val document: Document? = null,
)

@Serializable
@XmlSerialName(
  "CertificateOnCard",
  namespace = "http://ws.gematik.de/conn/EncryptionService/v6.1",
)
data class CertificateOnCard(
  @XmlElement(true)
  @XmlSerialName(
    "CardHandle",
    namespace = "http://ws.gematik.de/conn/ConnectorCommon/v5.0",
  )
  val cardHandle: String,
  @XmlElement(true)
  @XmlSerialName("KeyReference")
  val keyReference: String? = null,
)

@Serializable
@XmlSerialName(
  "PrivateKeyOnCard",
  namespace = "http://ws.gematik.de/conn/EncryptionService/v6.1",
)
data class PrivateKeyOnCard(
  @XmlElement(true)
  @XmlSerialName(
    "CardHandle",
    namespace = "http://ws.gematik.de/conn/ConnectorCommon/v5.0",
  )
  val cardHandle: String,
  @XmlElement(true)
  @XmlSerialName("KeyReference")
  val keyReference: String? = null,
)

@Serializable
enum class EncryptionType {
  @SerialName("http://www.w3.org/TR/xmlenc-core/")
  HttpWwwW3OrgTRXmlencCore,
  @SerialName("urn:ietf:rfc:5652")
  UrnIetfRfc5652,
  @SerialName("urn:ietf:rfc:5751")
  UrnIetfRfc5751,
}

@Serializable
@XmlSerialName(
  "Element",
  namespace = "http://ws.gematik.de/conn/EncryptionService/v6.1",
)
data class Element(
  @XmlElement(false)
  @XmlSerialName("Type")
  val type: String,
  @XmlValue(true)
  val charData: String,
)

@Serializable
@XmlSerialName(
  "DecryptDocument",
  namespace = "http://ws.gematik.de/conn/EncryptionService/v6.1",
)
data class DecryptDocument(
  @XmlElement(true)
  @XmlSerialName(
    "Context",
    namespace = "http://ws.gematik.de/conn/ConnectorContext/v2.0",
  )
  val context: Context,
  @XmlElement(true)
  @XmlSerialName("PrivateKeyOnCard")
  val privateKeyOnCard: PrivateKeyOnCard,
  @XmlElement(true)
  @XmlSerialName(
    "Document",
    namespace = "http://ws.gematik.de/conn/ConnectorCommon/v5.0",
  )
  val document: Document,
  @XmlElement(true)
  @XmlSerialName("OptionalInputs")
  val optionalInputs: String? = null,
)

@Serializable
@XmlSerialName(
  "DecryptDocumentResponse",
  namespace = "http://ws.gematik.de/conn/EncryptionService/v6.1",
)
data class DecryptDocumentResponse(
  @XmlElement(true)
  @XmlSerialName(
    "Status",
    namespace = "http://ws.gematik.de/conn/ConnectorCommon/v5.0",
  )
  val status: Status,
  @XmlElement(true)
  @XmlSerialName(
    "Document",
    namespace = "http://ws.gematik.de/conn/ConnectorCommon/v5.0",
  )
  val document: Document? = null,
  @XmlElement(true)
  @XmlSerialName("OptionalOutputs")
  val optionalOutputs: String? = null,
)

@Serializable
@XmlSerialName(
  "UnprotectedProperties",
  namespace = "http://ws.gematik.de/conn/EncryptionService/v6.1",
)
data class UnprotectedProperties(
  @XmlElement(true)
  @XmlSerialName(
    "Property",
    namespace = "urn:oasis:names:tc:dss:1.0:core:schema",
  )
  val `property`: List<Property> = emptyList(),
)

@Serializable
enum class CommonStepsEnum {
  @SerialName("EncryptXMLData")
  EncryptXMLData,
  @SerialName("DecryptXMLData")
  DecryptXMLData,
}

@Serializable
enum class EncryptionStepResultEnum {
  @SerialName("ERROR")
  Error,
  @SerialName("OK")
  Ok,
}

@Serializable
data class KeyOnCardType(
  @XmlElement(true)
  @XmlSerialName(
    "CardHandle",
    namespace = "http://ws.gematik.de/conn/ConnectorCommon/v5.0",
  )
  val cardHandle: String,
  @XmlElement(true)
  @XmlSerialName(
    "KeyReference",
    namespace = "http://ws.gematik.de/conn/EncryptionService/v6.1",
  )
  val keyReference: String? = null,
)

@Serializable
@XmlSerialName(
  "RecipientKeys",
  namespace = "http://ws.gematik.de/conn/EncryptionService/v6.1",
)
data class EncryptDocumentRecipientKeys(
  @XmlElement(true)
  @XmlSerialName("CertificateOnCard")
  val certificateOnCard: CertificateOnCard? = null,
  @XmlElement(true)
  @XmlSerialName("Certificate")
  val certificate: List<String> = emptyList(),
)

@Serializable
@XmlSerialName(
  "OptionalInputs",
  namespace = "http://ws.gematik.de/conn/EncryptionService/v6.1",
)
data class EncryptDocumentOptionalInputs(
  @XmlElement(true)
  @XmlSerialName("EncryptionType")
  val encryptionType: EncryptionType? = null,
  @XmlElement(true)
  @XmlSerialName("Element")
  val element: List<Element> = emptyList(),
  @XmlElement(true)
  @XmlSerialName("UnprotectedProperties")
  val unprotectedProperties: UnprotectedProperties? = null,
)
