// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.gematik.conn.encryptionservice61

import de.gematik.connector.api.oasis.dss10core.Property
import kotlin.collections.List
import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName

@Serializable
@XmlSerialName(
  "UnprotectedProperties",
  namespace = "http://ws.gematik.de/conn/EncryptionService/v6.1",
)
data class UnprotectedProperties(
  @XmlElement(true)
  @XmlSerialName(
    "Property",
    namespace = "urn:oasis:names:tc:dss:1.0:core:schema",
  )
  val `property`: List<Property> = emptyList(),
)
