// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.gematik.conn.authsignatureservice74

import de.gematik.connector.api.gematik.conn.signatureservice74.ExternalAuthenticate
import de.gematik.connector.api.gematik.conn.signatureservice74.ExternalAuthenticateResponse
import de.gematik.connector.api.gematik.tel.error20.Error
import de.gematik.connector.api.soap.SoapEnvelope
import kotlin.Boolean
import kotlin.String
import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName

@Serializable
@XmlSerialName(
  "Envelope",
  namespace = "http://schemas.xmlsoap.org/soap/envelope/",
  prefix = "SOAP-ENV",
)
data class ExternalAuthenticateEnvelope(
  @XmlElement(true)
  @XmlSerialName(
    "Body",
    namespace = "http://schemas.xmlsoap.org/soap/envelope/",
    prefix = "SOAP-ENV",
  )
  val body: Body,
) : SoapEnvelope {
  override fun isFault(): Boolean = false

  @Serializable
  data class Body(
    @XmlElement(true)
    val externalAuthenticate: ExternalAuthenticate? = null,
  )
}

@Serializable
@XmlSerialName(
  "Envelope",
  namespace = "http://schemas.xmlsoap.org/soap/envelope/",
  prefix = "SOAP-ENV",
)
data class ExternalAuthenticateResponseEnvelope(
  @XmlElement(true)
  @XmlSerialName(
    "Body",
    namespace = "http://schemas.xmlsoap.org/soap/envelope/",
    prefix = "SOAP-ENV",
  )
  val body: Body,
) : SoapEnvelope {
  override fun isFault(): Boolean = body.fault != null

  @Serializable
  data class Body(
    @XmlElement(true)
    val externalAuthenticateResponse: ExternalAuthenticateResponse? = null,
    @XmlElement(true)
    @XmlSerialName(
      "Fault",
      namespace = "http://schemas.xmlsoap.org/soap/envelope/",
      prefix = "SOAP-ENV",
    )
    val fault: Fault? = null,
  )

  @Serializable
  data class Fault(
    @XmlElement(true)
    @XmlSerialName(
      "faultcode",
      namespace = "",
    )
    val faultcode: String = "",
    @XmlElement(true)
    @XmlSerialName(
      "faultstring",
      namespace = "",
    )
    val faultstring: String = "",
    @XmlElement(true)
    @XmlSerialName(
      "faultactor",
      namespace = "",
    )
    val faultactor: String? = null,
    @XmlElement(true)
    @XmlSerialName(
      "detail",
      namespace = "",
    )
    val detail: Detail? = null,
  )

  @Serializable
  data class Detail(
    @XmlElement(true)
    @XmlSerialName(
      "Error",
      namespace = "http://ws.gematik.de/tel/error/v2.0",
    )
    val error: Error? = null,
  )
}
