// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.gematik.conn.authsignatureservice74

import de.gematik.connector.api.soap.SoapOperation

object Operations {
  val ExternalAuthenticate: SoapOperation =
      SoapOperation("ExternalAuthenticate", "http://ws.gematik.de/conn/SignatureService/v7.4#ExternalAuthenticate", "soap11")
}
