// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.etsi01903132

import kotlin.String
import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName

@Serializable
data class AnyType(
  @XmlElement(false)
  @XmlSerialName("anyAttribute")
  val unknownAttributes: String? = null,
  @XmlElement(true)
  val unknownContent: String? = null,
)
