// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.etsi01903132

import kotlin.String
import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName

@Serializable
@XmlSerialName(
  "AttributeRevocationValues",
  namespace = "http://uri.etsi.org/01903/v1.3.2#",
)
data class AttributeRevocationValues(
  @XmlElement(false)
  @XmlSerialName("Id")
  val id: String? = null,
  @XmlElement(true)
  @XmlSerialName("CRLValues")
  val crlValues: CRLValuesType? = null,
  @XmlElement(true)
  @XmlSerialName("OCSPValues")
  val ocspValues: OCSPValuesType? = null,
  @XmlElement(true)
  @XmlSerialName("OtherValues")
  val otherValues: OtherCertStatusValuesType? = null,
)
