// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.etsi01903132

import kotlin.String
import kotlin.collections.List
import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName

@Serializable
data class CommitmentTypeIndicationType(
  @XmlElement(true)
  @XmlSerialName(
    "CommitmentTypeId",
    namespace = "http://uri.etsi.org/01903/v1.3.2#",
  )
  val commitmentTypeId: ObjectIdentifierType,
  @XmlElement(true)
  @XmlSerialName(
    "ObjectReference",
    namespace = "http://uri.etsi.org/01903/v1.3.2#",
  )
  val objectReference: List<String> = emptyList(),
  @XmlElement(true)
  @XmlSerialName(
    "AllSignedDataObjects",
    namespace = "http://uri.etsi.org/01903/v1.3.2#",
  )
  val allSignedDataObjects: String? = null,
  @XmlElement(true)
  @XmlSerialName(
    "CommitmentTypeQualifiers",
    namespace = "http://uri.etsi.org/01903/v1.3.2#",
  )
  val commitmentTypeQualifiers: CommitmentTypeQualifiersListType? = null,
)
