// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.etsi01903132

import kotlin.String
import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName

@Serializable
data class CompleteRevocationRefsType(
  @XmlElement(false)
  @XmlSerialName("Id")
  val id: String? = null,
  @XmlElement(true)
  @XmlSerialName(
    "CRLRefs",
    namespace = "http://uri.etsi.org/01903/v1.3.2#",
  )
  val crlRefs: CRLRefsType? = null,
  @XmlElement(true)
  @XmlSerialName(
    "OCSPRefs",
    namespace = "http://uri.etsi.org/01903/v1.3.2#",
  )
  val ocspRefs: OCSPRefsType? = null,
  @XmlElement(true)
  @XmlSerialName(
    "OtherRefs",
    namespace = "http://uri.etsi.org/01903/v1.3.2#",
  )
  val otherRefs: OtherCertStatusRefsType? = null,
)
