// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.etsi01903132

import de.gematik.connector.api.w3200009.xmldsig.Signature
import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName

@Serializable
@XmlSerialName(
  "CounterSignature",
  namespace = "http://uri.etsi.org/01903/v1.3.2#",
)
data class CounterSignature(
  @XmlElement(true)
  @XmlSerialName(
    "Signature",
    namespace = "http://www.w3.org/2000/09/xmldsig#",
  )
  val signature: Signature,
)
