// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.etsi01903132

import kotlin.String
import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName

@Serializable
data class DataObjectFormatType(
  @XmlElement(false)
  @XmlSerialName("ObjectReference")
  val objectReference: String,
  @XmlElement(true)
  @XmlSerialName(
    "Description",
    namespace = "http://uri.etsi.org/01903/v1.3.2#",
  )
  val description: String? = null,
  @XmlElement(true)
  @XmlSerialName(
    "ObjectIdentifier",
    namespace = "http://uri.etsi.org/01903/v1.3.2#",
  )
  val objectIdentifier: ObjectIdentifierType? = null,
  @XmlElement(true)
  @XmlSerialName(
    "MimeType",
    namespace = "http://uri.etsi.org/01903/v1.3.2#",
  )
  val mimeType: String? = null,
  @XmlElement(true)
  @XmlSerialName(
    "Encoding",
    namespace = "http://uri.etsi.org/01903/v1.3.2#",
  )
  val encoding: String? = null,
)
