// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.etsi01903132

import kotlin.String
import kotlin.collections.List
import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName

@Serializable
data class DocumentationReferencesType(
  @XmlElement(true)
  @XmlSerialName(
    "DocumentationReference",
    namespace = "http://uri.etsi.org/01903/v1.3.2#",
  )
  val documentationReference: List<String> = emptyList(),
)
