// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.etsi01903132

import kotlin.String
import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName
import nl.adaptivity.xmlutil.serialization.XmlValue

@Serializable
data class IdentifierType(
  @XmlElement(false)
  @XmlSerialName("Qualifier")
  val qualifier: QualifierType? = null,
  @XmlValue(true)
  val charData: String,
)
