// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.etsi01903132

import kotlin.String
import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName

@Serializable
@XmlSerialName(
  "ObjectIdentifier",
  namespace = "http://uri.etsi.org/01903/v1.3.2#",
)
data class ObjectIdentifier(
  @XmlElement(true)
  @XmlSerialName("Identifier")
  val identifier: IdentifierType,
  @XmlElement(true)
  @XmlSerialName("Description")
  val description: String? = null,
  @XmlElement(true)
  @XmlSerialName("DocumentationReferences")
  val documentationReferences: DocumentationReferencesType? = null,
)
