// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.etsi01903132

import kotlin.String
import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName

@Serializable
data class QualifyingPropertiesReferenceType(
  @XmlElement(false)
  @XmlSerialName("URI")
  val uri: String,
  @XmlElement(false)
  @XmlSerialName("Id")
  val id: String? = null,
)
