// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.etsi01903132

import kotlin.String
import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName

@Serializable
@XmlSerialName(
  "QualifyingProperties",
  namespace = "http://uri.etsi.org/01903/v1.3.2#",
)
data class QualifyingProperties(
  @XmlElement(false)
  @XmlSerialName("Target")
  val target: String,
  @XmlElement(false)
  @XmlSerialName("Id")
  val id: String? = null,
  @XmlElement(true)
  @XmlSerialName("SignedProperties")
  val signedProperties: SignedPropertiesType? = null,
  @XmlElement(true)
  @XmlSerialName("UnsignedProperties")
  val unsignedProperties: UnsignedPropertiesType? = null,
)
