// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.etsi01903132

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
enum class QualifierType {
  @SerialName("OIDAsURI")
  OIDAsURI,
  @SerialName("OIDAsURN")
  OIDAsURN,
}
