// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.etsi01903132

import de.gematik.connector.api.w3200009.xmldsig.DigestMethod
import kotlin.String
import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName

@Serializable
@XmlSerialName(
  "ReferenceInfo",
  namespace = "http://uri.etsi.org/01903/v1.3.2#",
)
data class ReferenceInfo(
  @XmlElement(false)
  @XmlSerialName("Id")
  val id: String? = null,
  @XmlElement(false)
  @XmlSerialName("URI")
  val uri: String? = null,
  @XmlElement(true)
  @XmlSerialName(
    "DigestMethod",
    namespace = "http://www.w3.org/2000/09/xmldsig#",
  )
  val digestMethod: DigestMethod,
  @XmlElement(true)
  @XmlSerialName(
    "DigestValue",
    namespace = "http://www.w3.org/2000/09/xmldsig#",
  )
  val digestValue: String,
)
