// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.etsi01903132

import de.gematik.connector.api.w3200009.xmldsig.CanonicalizationMethod
import de.gematik.connector.api.w3200009.xmldsig.DigestMethod
import de.gematik.connector.api.w3200009.xmldsig.Signature
import de.gematik.connector.api.w3200009.xmldsig.Transforms
import de.gematik.connector.api.w3200009.xmldsig.X509IssuerSerialType
import kotlin.Boolean
import kotlin.Int
import kotlin.String
import kotlin.collections.List
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName
import nl.adaptivity.xmlutil.serialization.XmlValue

@Serializable
@XmlSerialName(
  "Any",
  namespace = "http://uri.etsi.org/01903/v1.3.2#",
)
data class Any(
  @XmlElement(false)
  @XmlSerialName("anyAttribute")
  val unknownAttributes: String? = null,
  @XmlElement(true)
  val unknownContent: String? = null,
)

@Serializable
@XmlSerialName(
  "ObjectIdentifier",
  namespace = "http://uri.etsi.org/01903/v1.3.2#",
)
data class ObjectIdentifier(
  @XmlElement(true)
  @XmlSerialName("Identifier")
  val identifier: IdentifierType,
  @XmlElement(true)
  @XmlSerialName("Description")
  val description: String? = null,
  @XmlElement(true)
  @XmlSerialName("DocumentationReferences")
  val documentationReferences: DocumentationReferencesType? = null,
)

@Serializable
@XmlSerialName(
  "EncapsulatedPKIData",
  namespace = "http://uri.etsi.org/01903/v1.3.2#",
)
data class EncapsulatedPKIData(
  @XmlElement(false)
  @XmlSerialName("Id")
  val id: String? = null,
  @XmlElement(false)
  @XmlSerialName("Encoding")
  val encoding: String? = null,
  @XmlValue(true)
  val charData: String,
)

@Serializable
@XmlSerialName(
  "Include",
  namespace = "http://uri.etsi.org/01903/v1.3.2#",
)
data class Include(
  @XmlElement(false)
  @XmlSerialName("URI")
  val uri: String,
  @XmlElement(false)
  @XmlSerialName("referencedData")
  val referencedData: Boolean? = null,
)

@Serializable
@XmlSerialName(
  "ReferenceInfo",
  namespace = "http://uri.etsi.org/01903/v1.3.2#",
)
data class ReferenceInfo(
  @XmlElement(false)
  @XmlSerialName("Id")
  val id: String? = null,
  @XmlElement(false)
  @XmlSerialName("URI")
  val uri: String? = null,
  @XmlElement(true)
  @XmlSerialName(
    "DigestMethod",
    namespace = "http://www.w3.org/2000/09/xmldsig#",
  )
  val digestMethod: DigestMethod,
  @XmlElement(true)
  @XmlSerialName(
    "DigestValue",
    namespace = "http://www.w3.org/2000/09/xmldsig#",
  )
  val digestValue: String,
)

@Serializable
@XmlSerialName(
  "XAdESTimeStamp",
  namespace = "http://uri.etsi.org/01903/v1.3.2#",
)
data class XAdESTimeStamp(
  @XmlElement(false)
  @XmlSerialName("Id")
  val id: String? = null,
  @XmlElement(true)
  @XmlSerialName("Include")
  val include: List<Include> = emptyList(),
  @XmlElement(true)
  @XmlSerialName(
    "CanonicalizationMethod",
    namespace = "http://www.w3.org/2000/09/xmldsig#",
  )
  val canonicalizationMethod: CanonicalizationMethod? = null,
  @XmlElement(true)
  @XmlSerialName("EncapsulatedTimeStamp")
  val encapsulatedTimeStamp: List<EncapsulatedPKIDataType> = emptyList(),
  @XmlElement(true)
  @XmlSerialName("XMLTimeStamp")
  val xmlTimeStamp: List<AnyType> = emptyList(),
)

@Serializable
@XmlSerialName(
  "OtherTimeStamp",
  namespace = "http://uri.etsi.org/01903/v1.3.2#",
)
data class OtherTimeStamp(
  @XmlElement(false)
  @XmlSerialName("Id")
  val id: String? = null,
  @XmlElement(true)
  @XmlSerialName("ReferenceInfo")
  val referenceInfo: List<ReferenceInfo> = emptyList(),
  @XmlElement(true)
  @XmlSerialName(
    "CanonicalizationMethod",
    namespace = "http://www.w3.org/2000/09/xmldsig#",
  )
  val canonicalizationMethod: CanonicalizationMethod? = null,
  @XmlElement(true)
  @XmlSerialName("EncapsulatedTimeStamp")
  val encapsulatedTimeStamp: EncapsulatedPKIDataType? = null,
  @XmlElement(true)
  @XmlSerialName("XMLTimeStamp")
  val xmlTimeStamp: AnyType? = null,
)

@Serializable
@XmlSerialName(
  "QualifyingProperties",
  namespace = "http://uri.etsi.org/01903/v1.3.2#",
)
data class QualifyingProperties(
  @XmlElement(false)
  @XmlSerialName("Target")
  val target: String,
  @XmlElement(false)
  @XmlSerialName("Id")
  val id: String? = null,
  @XmlElement(true)
  @XmlSerialName("SignedProperties")
  val signedProperties: SignedPropertiesType? = null,
  @XmlElement(true)
  @XmlSerialName("UnsignedProperties")
  val unsignedProperties: UnsignedPropertiesType? = null,
)

@Serializable
@XmlSerialName(
  "SignedProperties",
  namespace = "http://uri.etsi.org/01903/v1.3.2#",
)
data class SignedProperties(
  @XmlElement(false)
  @XmlSerialName("Id")
  val id: String? = null,
  @XmlElement(true)
  @XmlSerialName("SignedSignatureProperties")
  val signedSignatureProperties: SignedSignaturePropertiesType? = null,
  @XmlElement(true)
  @XmlSerialName("SignedDataObjectProperties")
  val signedDataObjectProperties: SignedDataObjectPropertiesType? = null,
)

@Serializable
@XmlSerialName(
  "UnsignedProperties",
  namespace = "http://uri.etsi.org/01903/v1.3.2#",
)
data class UnsignedProperties(
  @XmlElement(false)
  @XmlSerialName("Id")
  val id: String? = null,
  @XmlElement(true)
  @XmlSerialName("UnsignedSignatureProperties")
  val unsignedSignatureProperties: UnsignedSignaturePropertiesType? = null,
  @XmlElement(true)
  @XmlSerialName("UnsignedDataObjectProperties")
  val unsignedDataObjectProperties: UnsignedDataObjectPropertiesType? = null,
)

@Serializable
@XmlSerialName(
  "SignedSignatureProperties",
  namespace = "http://uri.etsi.org/01903/v1.3.2#",
)
data class SignedSignatureProperties(
  @XmlElement(false)
  @XmlSerialName("Id")
  val id: String? = null,
  @XmlElement(true)
  @XmlSerialName("SigningTime")
  val signingTime: String? = null,
  @XmlElement(true)
  @XmlSerialName("SigningCertificate")
  val signingCertificate: CertIDListType? = null,
  @XmlElement(true)
  @XmlSerialName("SignaturePolicyIdentifier")
  val signaturePolicyIdentifier: SignaturePolicyIdentifierType? = null,
  @XmlElement(true)
  @XmlSerialName("SignatureProductionPlace")
  val signatureProductionPlace: SignatureProductionPlaceType? = null,
  @XmlElement(true)
  @XmlSerialName("SignerRole")
  val signerRole: SignerRoleType? = null,
)

@Serializable
@XmlSerialName(
  "SignedDataObjectProperties",
  namespace = "http://uri.etsi.org/01903/v1.3.2#",
)
data class SignedDataObjectProperties(
  @XmlElement(false)
  @XmlSerialName("Id")
  val id: String? = null,
  @XmlElement(true)
  @XmlSerialName("DataObjectFormat")
  val dataObjectFormat: List<DataObjectFormatType> = emptyList(),
  @XmlElement(true)
  @XmlSerialName("CommitmentTypeIndication")
  val commitmentTypeIndication: List<CommitmentTypeIndicationType> = emptyList(),
  @XmlElement(true)
  @XmlSerialName("AllDataObjectsTimeStamp")
  val allDataObjectsTimeStamp: List<XAdESTimeStampType> = emptyList(),
  @XmlElement(true)
  @XmlSerialName("IndividualDataObjectsTimeStamp")
  val individualDataObjectsTimeStamp: List<XAdESTimeStampType> = emptyList(),
)

@Serializable
@XmlSerialName(
  "UnsignedSignatureProperties",
  namespace = "http://uri.etsi.org/01903/v1.3.2#",
)
data class UnsignedSignatureProperties(
  @XmlElement(false)
  @XmlSerialName("Id")
  val id: String? = null,
  @XmlElement(true)
  @XmlSerialName("CounterSignature")
  val counterSignature: List<CounterSignatureType> = emptyList(),
  @XmlElement(true)
  @XmlSerialName("SignatureTimeStamp")
  val signatureTimeStamp: List<XAdESTimeStampType> = emptyList(),
  @XmlElement(true)
  @XmlSerialName("CompleteCertificateRefs")
  val completeCertificateRefs: List<CompleteCertificateRefsType> = emptyList(),
  @XmlElement(true)
  @XmlSerialName("CompleteRevocationRefs")
  val completeRevocationRefs: List<CompleteRevocationRefsType> = emptyList(),
  @XmlElement(true)
  @XmlSerialName("AttributeCertificateRefs")
  val attributeCertificateRefs: List<CompleteCertificateRefsType> = emptyList(),
  @XmlElement(true)
  @XmlSerialName("AttributeRevocationRefs")
  val attributeRevocationRefs: List<CompleteRevocationRefsType> = emptyList(),
  @XmlElement(true)
  @XmlSerialName("SigAndRefsTimeStamp")
  val sigAndRefsTimeStamp: List<XAdESTimeStampType> = emptyList(),
  @XmlElement(true)
  @XmlSerialName("RefsOnlyTimeStamp")
  val refsOnlyTimeStamp: List<XAdESTimeStampType> = emptyList(),
  @XmlElement(true)
  @XmlSerialName("CertificateValues")
  val certificateValues: List<CertificateValuesType> = emptyList(),
  @XmlElement(true)
  @XmlSerialName("RevocationValues")
  val revocationValues: List<RevocationValuesType> = emptyList(),
  @XmlElement(true)
  @XmlSerialName("AttrAuthoritiesCertValues")
  val attrAuthoritiesCertValues: List<CertificateValuesType> = emptyList(),
  @XmlElement(true)
  @XmlSerialName("AttributeRevocationValues")
  val attributeRevocationValues: List<RevocationValuesType> = emptyList(),
  @XmlElement(true)
  @XmlSerialName("ArchiveTimeStamp")
  val archiveTimeStamp: List<XAdESTimeStampType> = emptyList(),
  @XmlElement(true)
  val unknownContent: String? = null,
)

@Serializable
@XmlSerialName(
  "UnsignedDataObjectProperties",
  namespace = "http://uri.etsi.org/01903/v1.3.2#",
)
data class UnsignedDataObjectProperties(
  @XmlElement(false)
  @XmlSerialName("Id")
  val id: String? = null,
  @XmlElement(true)
  @XmlSerialName("UnsignedDataObjectProperty")
  val unsignedDataObjectProperty: List<AnyType> = emptyList(),
)

@Serializable
@XmlSerialName(
  "QualifyingPropertiesReference",
  namespace = "http://uri.etsi.org/01903/v1.3.2#",
)
data class QualifyingPropertiesReference(
  @XmlElement(false)
  @XmlSerialName("URI")
  val uri: String,
  @XmlElement(false)
  @XmlSerialName("Id")
  val id: String? = null,
)

@Serializable
@XmlSerialName(
  "SigningCertificate",
  namespace = "http://uri.etsi.org/01903/v1.3.2#",
)
data class SigningCertificate(
  @XmlElement(true)
  @XmlSerialName("Cert")
  val cert: List<CertIDType> = emptyList(),
)

@Serializable
@XmlSerialName(
  "SignaturePolicyIdentifier",
  namespace = "http://uri.etsi.org/01903/v1.3.2#",
)
data class SignaturePolicyIdentifier(
  @XmlElement(true)
  @XmlSerialName("SignaturePolicyId")
  val signaturePolicyId: SignaturePolicyIdType? = null,
  @XmlElement(true)
  @XmlSerialName("SignaturePolicyImplied")
  val signaturePolicyImplied: String? = null,
)

@Serializable
@XmlSerialName(
  "SPUserNotice",
  namespace = "http://uri.etsi.org/01903/v1.3.2#",
)
data class SPUserNotice(
  @XmlElement(true)
  @XmlSerialName("NoticeRef")
  val noticeRef: NoticeReferenceType? = null,
  @XmlElement(true)
  @XmlSerialName("ExplicitText")
  val explicitText: String? = null,
)

@Serializable
@XmlSerialName(
  "CounterSignature",
  namespace = "http://uri.etsi.org/01903/v1.3.2#",
)
data class CounterSignature(
  @XmlElement(true)
  @XmlSerialName(
    "Signature",
    namespace = "http://www.w3.org/2000/09/xmldsig#",
  )
  val signature: Signature,
)

@Serializable
@XmlSerialName(
  "DataObjectFormat",
  namespace = "http://uri.etsi.org/01903/v1.3.2#",
)
data class DataObjectFormat(
  @XmlElement(false)
  @XmlSerialName("ObjectReference")
  val objectReference: String,
  @XmlElement(true)
  @XmlSerialName("Description")
  val description: String? = null,
  @XmlElement(true)
  @XmlSerialName("ObjectIdentifier")
  val objectIdentifier: ObjectIdentifierType? = null,
  @XmlElement(true)
  @XmlSerialName("MimeType")
  val mimeType: String? = null,
  @XmlElement(true)
  @XmlSerialName("Encoding")
  val encoding: String? = null,
)

@Serializable
@XmlSerialName(
  "CommitmentTypeIndication",
  namespace = "http://uri.etsi.org/01903/v1.3.2#",
)
data class CommitmentTypeIndication(
  @XmlElement(true)
  @XmlSerialName("CommitmentTypeId")
  val commitmentTypeId: ObjectIdentifierType,
  @XmlElement(true)
  @XmlSerialName("ObjectReference")
  val objectReference: List<String> = emptyList(),
  @XmlElement(true)
  @XmlSerialName("AllSignedDataObjects")
  val allSignedDataObjects: String? = null,
  @XmlElement(true)
  @XmlSerialName("CommitmentTypeQualifiers")
  val commitmentTypeQualifiers: CommitmentTypeQualifiersListType? = null,
)

@Serializable
@XmlSerialName(
  "SignatureProductionPlace",
  namespace = "http://uri.etsi.org/01903/v1.3.2#",
)
data class SignatureProductionPlace(
  @XmlElement(true)
  @XmlSerialName("City")
  val city: String? = null,
  @XmlElement(true)
  @XmlSerialName("StateOrProvince")
  val stateOrProvince: String? = null,
  @XmlElement(true)
  @XmlSerialName("PostalCode")
  val postalCode: String? = null,
  @XmlElement(true)
  @XmlSerialName("CountryName")
  val countryName: String? = null,
)

@Serializable
@XmlSerialName(
  "SignerRole",
  namespace = "http://uri.etsi.org/01903/v1.3.2#",
)
data class SignerRole(
  @XmlElement(true)
  @XmlSerialName("ClaimedRoles")
  val claimedRoles: ClaimedRolesListType? = null,
  @XmlElement(true)
  @XmlSerialName("CertifiedRoles")
  val certifiedRoles: CertifiedRolesListType? = null,
)

@Serializable
@XmlSerialName(
  "AllDataObjectsTimeStamp",
  namespace = "http://uri.etsi.org/01903/v1.3.2#",
)
data class AllDataObjectsTimeStamp(
  @XmlElement(false)
  @XmlSerialName("Id")
  val id: String? = null,
  @XmlElement(true)
  @XmlSerialName("Include")
  val include: List<Include> = emptyList(),
  @XmlElement(true)
  @XmlSerialName(
    "CanonicalizationMethod",
    namespace = "http://www.w3.org/2000/09/xmldsig#",
  )
  val canonicalizationMethod: CanonicalizationMethod? = null,
  @XmlElement(true)
  @XmlSerialName("EncapsulatedTimeStamp")
  val encapsulatedTimeStamp: List<EncapsulatedPKIDataType> = emptyList(),
  @XmlElement(true)
  @XmlSerialName("XMLTimeStamp")
  val xmlTimeStamp: List<AnyType> = emptyList(),
)

@Serializable
@XmlSerialName(
  "IndividualDataObjectsTimeStamp",
  namespace = "http://uri.etsi.org/01903/v1.3.2#",
)
data class IndividualDataObjectsTimeStamp(
  @XmlElement(false)
  @XmlSerialName("Id")
  val id: String? = null,
  @XmlElement(true)
  @XmlSerialName("Include")
  val include: List<Include> = emptyList(),
  @XmlElement(true)
  @XmlSerialName(
    "CanonicalizationMethod",
    namespace = "http://www.w3.org/2000/09/xmldsig#",
  )
  val canonicalizationMethod: CanonicalizationMethod? = null,
  @XmlElement(true)
  @XmlSerialName("EncapsulatedTimeStamp")
  val encapsulatedTimeStamp: List<EncapsulatedPKIDataType> = emptyList(),
  @XmlElement(true)
  @XmlSerialName("XMLTimeStamp")
  val xmlTimeStamp: List<AnyType> = emptyList(),
)

@Serializable
@XmlSerialName(
  "SignatureTimeStamp",
  namespace = "http://uri.etsi.org/01903/v1.3.2#",
)
data class SignatureTimeStamp(
  @XmlElement(false)
  @XmlSerialName("Id")
  val id: String? = null,
  @XmlElement(true)
  @XmlSerialName("Include")
  val include: List<Include> = emptyList(),
  @XmlElement(true)
  @XmlSerialName(
    "CanonicalizationMethod",
    namespace = "http://www.w3.org/2000/09/xmldsig#",
  )
  val canonicalizationMethod: CanonicalizationMethod? = null,
  @XmlElement(true)
  @XmlSerialName("EncapsulatedTimeStamp")
  val encapsulatedTimeStamp: List<EncapsulatedPKIDataType> = emptyList(),
  @XmlElement(true)
  @XmlSerialName("XMLTimeStamp")
  val xmlTimeStamp: List<AnyType> = emptyList(),
)

@Serializable
@XmlSerialName(
  "CompleteCertificateRefs",
  namespace = "http://uri.etsi.org/01903/v1.3.2#",
)
data class CompleteCertificateRefs(
  @XmlElement(false)
  @XmlSerialName("Id")
  val id: String? = null,
  @XmlElement(true)
  @XmlSerialName("CertRefs")
  val certRefs: CertIDListType,
)

@Serializable
@XmlSerialName(
  "CompleteRevocationRefs",
  namespace = "http://uri.etsi.org/01903/v1.3.2#",
)
data class CompleteRevocationRefs(
  @XmlElement(false)
  @XmlSerialName("Id")
  val id: String? = null,
  @XmlElement(true)
  @XmlSerialName("CRLRefs")
  val crlRefs: CRLRefsType? = null,
  @XmlElement(true)
  @XmlSerialName("OCSPRefs")
  val ocspRefs: OCSPRefsType? = null,
  @XmlElement(true)
  @XmlSerialName("OtherRefs")
  val otherRefs: OtherCertStatusRefsType? = null,
)

@Serializable
@XmlSerialName(
  "AttributeCertificateRefs",
  namespace = "http://uri.etsi.org/01903/v1.3.2#",
)
data class AttributeCertificateRefs(
  @XmlElement(false)
  @XmlSerialName("Id")
  val id: String? = null,
  @XmlElement(true)
  @XmlSerialName("CertRefs")
  val certRefs: CertIDListType,
)

@Serializable
@XmlSerialName(
  "AttributeRevocationRefs",
  namespace = "http://uri.etsi.org/01903/v1.3.2#",
)
data class AttributeRevocationRefs(
  @XmlElement(false)
  @XmlSerialName("Id")
  val id: String? = null,
  @XmlElement(true)
  @XmlSerialName("CRLRefs")
  val crlRefs: CRLRefsType? = null,
  @XmlElement(true)
  @XmlSerialName("OCSPRefs")
  val ocspRefs: OCSPRefsType? = null,
  @XmlElement(true)
  @XmlSerialName("OtherRefs")
  val otherRefs: OtherCertStatusRefsType? = null,
)

@Serializable
@XmlSerialName(
  "SigAndRefsTimeStamp",
  namespace = "http://uri.etsi.org/01903/v1.3.2#",
)
data class SigAndRefsTimeStamp(
  @XmlElement(false)
  @XmlSerialName("Id")
  val id: String? = null,
  @XmlElement(true)
  @XmlSerialName("Include")
  val include: List<Include> = emptyList(),
  @XmlElement(true)
  @XmlSerialName(
    "CanonicalizationMethod",
    namespace = "http://www.w3.org/2000/09/xmldsig#",
  )
  val canonicalizationMethod: CanonicalizationMethod? = null,
  @XmlElement(true)
  @XmlSerialName("EncapsulatedTimeStamp")
  val encapsulatedTimeStamp: List<EncapsulatedPKIDataType> = emptyList(),
  @XmlElement(true)
  @XmlSerialName("XMLTimeStamp")
  val xmlTimeStamp: List<AnyType> = emptyList(),
)

@Serializable
@XmlSerialName(
  "RefsOnlyTimeStamp",
  namespace = "http://uri.etsi.org/01903/v1.3.2#",
)
data class RefsOnlyTimeStamp(
  @XmlElement(false)
  @XmlSerialName("Id")
  val id: String? = null,
  @XmlElement(true)
  @XmlSerialName("Include")
  val include: List<Include> = emptyList(),
  @XmlElement(true)
  @XmlSerialName(
    "CanonicalizationMethod",
    namespace = "http://www.w3.org/2000/09/xmldsig#",
  )
  val canonicalizationMethod: CanonicalizationMethod? = null,
  @XmlElement(true)
  @XmlSerialName("EncapsulatedTimeStamp")
  val encapsulatedTimeStamp: List<EncapsulatedPKIDataType> = emptyList(),
  @XmlElement(true)
  @XmlSerialName("XMLTimeStamp")
  val xmlTimeStamp: List<AnyType> = emptyList(),
)

@Serializable
@XmlSerialName(
  "CertificateValues",
  namespace = "http://uri.etsi.org/01903/v1.3.2#",
)
data class CertificateValues(
  @XmlElement(false)
  @XmlSerialName("Id")
  val id: String? = null,
  @XmlElement(true)
  @XmlSerialName("EncapsulatedX509Certificate")
  val encapsulatedX509Certificate: List<EncapsulatedPKIDataType> = emptyList(),
  @XmlElement(true)
  @XmlSerialName("OtherCertificate")
  val otherCertificate: List<AnyType> = emptyList(),
)

@Serializable
@XmlSerialName(
  "RevocationValues",
  namespace = "http://uri.etsi.org/01903/v1.3.2#",
)
data class RevocationValues(
  @XmlElement(false)
  @XmlSerialName("Id")
  val id: String? = null,
  @XmlElement(true)
  @XmlSerialName("CRLValues")
  val crlValues: CRLValuesType? = null,
  @XmlElement(true)
  @XmlSerialName("OCSPValues")
  val ocspValues: OCSPValuesType? = null,
  @XmlElement(true)
  @XmlSerialName("OtherValues")
  val otherValues: OtherCertStatusValuesType? = null,
)

@Serializable
@XmlSerialName(
  "AttrAuthoritiesCertValues",
  namespace = "http://uri.etsi.org/01903/v1.3.2#",
)
data class AttrAuthoritiesCertValues(
  @XmlElement(false)
  @XmlSerialName("Id")
  val id: String? = null,
  @XmlElement(true)
  @XmlSerialName("EncapsulatedX509Certificate")
  val encapsulatedX509Certificate: List<EncapsulatedPKIDataType> = emptyList(),
  @XmlElement(true)
  @XmlSerialName("OtherCertificate")
  val otherCertificate: List<AnyType> = emptyList(),
)

@Serializable
@XmlSerialName(
  "AttributeRevocationValues",
  namespace = "http://uri.etsi.org/01903/v1.3.2#",
)
data class AttributeRevocationValues(
  @XmlElement(false)
  @XmlSerialName("Id")
  val id: String? = null,
  @XmlElement(true)
  @XmlSerialName("CRLValues")
  val crlValues: CRLValuesType? = null,
  @XmlElement(true)
  @XmlSerialName("OCSPValues")
  val ocspValues: OCSPValuesType? = null,
  @XmlElement(true)
  @XmlSerialName("OtherValues")
  val otherValues: OtherCertStatusValuesType? = null,
)

@Serializable
@XmlSerialName(
  "ArchiveTimeStamp",
  namespace = "http://uri.etsi.org/01903/v1.3.2#",
)
data class ArchiveTimeStamp(
  @XmlElement(false)
  @XmlSerialName("Id")
  val id: String? = null,
  @XmlElement(true)
  @XmlSerialName("Include")
  val include: List<Include> = emptyList(),
  @XmlElement(true)
  @XmlSerialName(
    "CanonicalizationMethod",
    namespace = "http://www.w3.org/2000/09/xmldsig#",
  )
  val canonicalizationMethod: CanonicalizationMethod? = null,
  @XmlElement(true)
  @XmlSerialName("EncapsulatedTimeStamp")
  val encapsulatedTimeStamp: List<EncapsulatedPKIDataType> = emptyList(),
  @XmlElement(true)
  @XmlSerialName("XMLTimeStamp")
  val xmlTimeStamp: List<AnyType> = emptyList(),
)

@Serializable
data class AnyType(
  @XmlElement(false)
  @XmlSerialName("anyAttribute")
  val unknownAttributes: String? = null,
  @XmlElement(true)
  val unknownContent: String? = null,
)

@Serializable
data class ObjectIdentifierType(
  @XmlElement(true)
  @XmlSerialName(
    "Identifier",
    namespace = "http://uri.etsi.org/01903/v1.3.2#",
  )
  val identifier: IdentifierType,
  @XmlElement(true)
  @XmlSerialName(
    "Description",
    namespace = "http://uri.etsi.org/01903/v1.3.2#",
  )
  val description: String? = null,
  @XmlElement(true)
  @XmlSerialName(
    "DocumentationReferences",
    namespace = "http://uri.etsi.org/01903/v1.3.2#",
  )
  val documentationReferences: DocumentationReferencesType? = null,
)

@Serializable
data class IdentifierType(
  @XmlElement(false)
  @XmlSerialName("Qualifier")
  val qualifier: QualifierType? = null,
  @XmlValue(true)
  val charData: String,
)

@Serializable
enum class QualifierType {
  @SerialName("OIDAsURI")
  OIDAsURI,
  @SerialName("OIDAsURN")
  OIDAsURN,
}

@Serializable
data class DocumentationReferencesType(
  @XmlElement(true)
  @XmlSerialName(
    "DocumentationReference",
    namespace = "http://uri.etsi.org/01903/v1.3.2#",
  )
  val documentationReference: List<String> = emptyList(),
)

@Serializable
data class EncapsulatedPKIDataType(
  @XmlElement(false)
  @XmlSerialName("Id")
  val id: String? = null,
  @XmlElement(false)
  @XmlSerialName("Encoding")
  val encoding: String? = null,
  @XmlValue(true)
  val charData: String,
)

@Serializable
data class IncludeType(
  @XmlElement(false)
  @XmlSerialName("URI")
  val uri: String,
  @XmlElement(false)
  @XmlSerialName("referencedData")
  val referencedData: Boolean? = null,
)

@Serializable
data class ReferenceInfoType(
  @XmlElement(false)
  @XmlSerialName("Id")
  val id: String? = null,
  @XmlElement(false)
  @XmlSerialName("URI")
  val uri: String? = null,
  @XmlElement(true)
  @XmlSerialName(
    "DigestMethod",
    namespace = "http://www.w3.org/2000/09/xmldsig#",
  )
  val digestMethod: DigestMethod,
  @XmlElement(true)
  @XmlSerialName(
    "DigestValue",
    namespace = "http://www.w3.org/2000/09/xmldsig#",
  )
  val digestValue: String,
)

@Serializable
data class GenericTimeStampType(
  @XmlElement(false)
  @XmlSerialName("Id")
  val id: String? = null,
  @XmlElement(true)
  @XmlSerialName(
    "Include",
    namespace = "http://uri.etsi.org/01903/v1.3.2#",
  )
  val include: List<Include> = emptyList(),
  @XmlElement(true)
  @XmlSerialName(
    "ReferenceInfo",
    namespace = "http://uri.etsi.org/01903/v1.3.2#",
  )
  val referenceInfo: List<ReferenceInfo> = emptyList(),
  @XmlElement(true)
  @XmlSerialName(
    "CanonicalizationMethod",
    namespace = "http://www.w3.org/2000/09/xmldsig#",
  )
  val canonicalizationMethod: CanonicalizationMethod? = null,
  @XmlElement(true)
  @XmlSerialName(
    "EncapsulatedTimeStamp",
    namespace = "http://uri.etsi.org/01903/v1.3.2#",
  )
  val encapsulatedTimeStamp: List<EncapsulatedPKIDataType> = emptyList(),
  @XmlElement(true)
  @XmlSerialName(
    "XMLTimeStamp",
    namespace = "http://uri.etsi.org/01903/v1.3.2#",
  )
  val xmlTimeStamp: List<AnyType> = emptyList(),
)

@Serializable
data class XAdESTimeStampType(
  @XmlElement(false)
  @XmlSerialName("Id")
  val id: String? = null,
  @XmlElement(true)
  @XmlSerialName(
    "Include",
    namespace = "http://uri.etsi.org/01903/v1.3.2#",
  )
  val include: List<Include> = emptyList(),
  @XmlElement(true)
  @XmlSerialName(
    "CanonicalizationMethod",
    namespace = "http://www.w3.org/2000/09/xmldsig#",
  )
  val canonicalizationMethod: CanonicalizationMethod? = null,
  @XmlElement(true)
  @XmlSerialName(
    "EncapsulatedTimeStamp",
    namespace = "http://uri.etsi.org/01903/v1.3.2#",
  )
  val encapsulatedTimeStamp: List<EncapsulatedPKIDataType> = emptyList(),
  @XmlElement(true)
  @XmlSerialName(
    "XMLTimeStamp",
    namespace = "http://uri.etsi.org/01903/v1.3.2#",
  )
  val xmlTimeStamp: List<AnyType> = emptyList(),
)

@Serializable
data class OtherTimeStampType(
  @XmlElement(false)
  @XmlSerialName("Id")
  val id: String? = null,
  @XmlElement(true)
  @XmlSerialName(
    "ReferenceInfo",
    namespace = "http://uri.etsi.org/01903/v1.3.2#",
  )
  val referenceInfo: List<ReferenceInfo> = emptyList(),
  @XmlElement(true)
  @XmlSerialName(
    "CanonicalizationMethod",
    namespace = "http://www.w3.org/2000/09/xmldsig#",
  )
  val canonicalizationMethod: CanonicalizationMethod? = null,
  @XmlElement(true)
  @XmlSerialName(
    "EncapsulatedTimeStamp",
    namespace = "http://uri.etsi.org/01903/v1.3.2#",
  )
  val encapsulatedTimeStamp: EncapsulatedPKIDataType? = null,
  @XmlElement(true)
  @XmlSerialName(
    "XMLTimeStamp",
    namespace = "http://uri.etsi.org/01903/v1.3.2#",
  )
  val xmlTimeStamp: AnyType? = null,
)

@Serializable
data class QualifyingPropertiesType(
  @XmlElement(false)
  @XmlSerialName("Target")
  val target: String,
  @XmlElement(false)
  @XmlSerialName("Id")
  val id: String? = null,
  @XmlElement(true)
  @XmlSerialName(
    "SignedProperties",
    namespace = "http://uri.etsi.org/01903/v1.3.2#",
  )
  val signedProperties: SignedPropertiesType? = null,
  @XmlElement(true)
  @XmlSerialName(
    "UnsignedProperties",
    namespace = "http://uri.etsi.org/01903/v1.3.2#",
  )
  val unsignedProperties: UnsignedPropertiesType? = null,
)

@Serializable
data class SignedPropertiesType(
  @XmlElement(false)
  @XmlSerialName("Id")
  val id: String? = null,
  @XmlElement(true)
  @XmlSerialName(
    "SignedSignatureProperties",
    namespace = "http://uri.etsi.org/01903/v1.3.2#",
  )
  val signedSignatureProperties: SignedSignaturePropertiesType? = null,
  @XmlElement(true)
  @XmlSerialName(
    "SignedDataObjectProperties",
    namespace = "http://uri.etsi.org/01903/v1.3.2#",
  )
  val signedDataObjectProperties: SignedDataObjectPropertiesType? = null,
)

@Serializable
data class UnsignedPropertiesType(
  @XmlElement(false)
  @XmlSerialName("Id")
  val id: String? = null,
  @XmlElement(true)
  @XmlSerialName(
    "UnsignedSignatureProperties",
    namespace = "http://uri.etsi.org/01903/v1.3.2#",
  )
  val unsignedSignatureProperties: UnsignedSignaturePropertiesType? = null,
  @XmlElement(true)
  @XmlSerialName(
    "UnsignedDataObjectProperties",
    namespace = "http://uri.etsi.org/01903/v1.3.2#",
  )
  val unsignedDataObjectProperties: UnsignedDataObjectPropertiesType? = null,
)

@Serializable
data class SignedSignaturePropertiesType(
  @XmlElement(false)
  @XmlSerialName("Id")
  val id: String? = null,
  @XmlElement(true)
  @XmlSerialName(
    "SigningTime",
    namespace = "http://uri.etsi.org/01903/v1.3.2#",
  )
  val signingTime: String? = null,
  @XmlElement(true)
  @XmlSerialName(
    "SigningCertificate",
    namespace = "http://uri.etsi.org/01903/v1.3.2#",
  )
  val signingCertificate: CertIDListType? = null,
  @XmlElement(true)
  @XmlSerialName(
    "SignaturePolicyIdentifier",
    namespace = "http://uri.etsi.org/01903/v1.3.2#",
  )
  val signaturePolicyIdentifier: SignaturePolicyIdentifierType? = null,
  @XmlElement(true)
  @XmlSerialName(
    "SignatureProductionPlace",
    namespace = "http://uri.etsi.org/01903/v1.3.2#",
  )
  val signatureProductionPlace: SignatureProductionPlaceType? = null,
  @XmlElement(true)
  @XmlSerialName(
    "SignerRole",
    namespace = "http://uri.etsi.org/01903/v1.3.2#",
  )
  val signerRole: SignerRoleType? = null,
)

@Serializable
data class SignedDataObjectPropertiesType(
  @XmlElement(false)
  @XmlSerialName("Id")
  val id: String? = null,
  @XmlElement(true)
  @XmlSerialName(
    "DataObjectFormat",
    namespace = "http://uri.etsi.org/01903/v1.3.2#",
  )
  val dataObjectFormat: List<DataObjectFormatType> = emptyList(),
  @XmlElement(true)
  @XmlSerialName(
    "CommitmentTypeIndication",
    namespace = "http://uri.etsi.org/01903/v1.3.2#",
  )
  val commitmentTypeIndication: List<CommitmentTypeIndicationType> = emptyList(),
  @XmlElement(true)
  @XmlSerialName(
    "AllDataObjectsTimeStamp",
    namespace = "http://uri.etsi.org/01903/v1.3.2#",
  )
  val allDataObjectsTimeStamp: List<XAdESTimeStampType> = emptyList(),
  @XmlElement(true)
  @XmlSerialName(
    "IndividualDataObjectsTimeStamp",
    namespace = "http://uri.etsi.org/01903/v1.3.2#",
  )
  val individualDataObjectsTimeStamp: List<XAdESTimeStampType> = emptyList(),
)

@Serializable
data class UnsignedSignaturePropertiesType(
  @XmlElement(false)
  @XmlSerialName("Id")
  val id: String? = null,
  @XmlElement(true)
  @XmlSerialName(
    "CounterSignature",
    namespace = "http://uri.etsi.org/01903/v1.3.2#",
  )
  val counterSignature: List<CounterSignatureType> = emptyList(),
  @XmlElement(true)
  @XmlSerialName(
    "SignatureTimeStamp",
    namespace = "http://uri.etsi.org/01903/v1.3.2#",
  )
  val signatureTimeStamp: List<XAdESTimeStampType> = emptyList(),
  @XmlElement(true)
  @XmlSerialName(
    "CompleteCertificateRefs",
    namespace = "http://uri.etsi.org/01903/v1.3.2#",
  )
  val completeCertificateRefs: List<CompleteCertificateRefsType> = emptyList(),
  @XmlElement(true)
  @XmlSerialName(
    "CompleteRevocationRefs",
    namespace = "http://uri.etsi.org/01903/v1.3.2#",
  )
  val completeRevocationRefs: List<CompleteRevocationRefsType> = emptyList(),
  @XmlElement(true)
  @XmlSerialName(
    "AttributeCertificateRefs",
    namespace = "http://uri.etsi.org/01903/v1.3.2#",
  )
  val attributeCertificateRefs: List<CompleteCertificateRefsType> = emptyList(),
  @XmlElement(true)
  @XmlSerialName(
    "AttributeRevocationRefs",
    namespace = "http://uri.etsi.org/01903/v1.3.2#",
  )
  val attributeRevocationRefs: List<CompleteRevocationRefsType> = emptyList(),
  @XmlElement(true)
  @XmlSerialName(
    "SigAndRefsTimeStamp",
    namespace = "http://uri.etsi.org/01903/v1.3.2#",
  )
  val sigAndRefsTimeStamp: List<XAdESTimeStampType> = emptyList(),
  @XmlElement(true)
  @XmlSerialName(
    "RefsOnlyTimeStamp",
    namespace = "http://uri.etsi.org/01903/v1.3.2#",
  )
  val refsOnlyTimeStamp: List<XAdESTimeStampType> = emptyList(),
  @XmlElement(true)
  @XmlSerialName(
    "CertificateValues",
    namespace = "http://uri.etsi.org/01903/v1.3.2#",
  )
  val certificateValues: List<CertificateValuesType> = emptyList(),
  @XmlElement(true)
  @XmlSerialName(
    "RevocationValues",
    namespace = "http://uri.etsi.org/01903/v1.3.2#",
  )
  val revocationValues: List<RevocationValuesType> = emptyList(),
  @XmlElement(true)
  @XmlSerialName(
    "AttrAuthoritiesCertValues",
    namespace = "http://uri.etsi.org/01903/v1.3.2#",
  )
  val attrAuthoritiesCertValues: List<CertificateValuesType> = emptyList(),
  @XmlElement(true)
  @XmlSerialName(
    "AttributeRevocationValues",
    namespace = "http://uri.etsi.org/01903/v1.3.2#",
  )
  val attributeRevocationValues: List<RevocationValuesType> = emptyList(),
  @XmlElement(true)
  @XmlSerialName(
    "ArchiveTimeStamp",
    namespace = "http://uri.etsi.org/01903/v1.3.2#",
  )
  val archiveTimeStamp: List<XAdESTimeStampType> = emptyList(),
  @XmlElement(true)
  val unknownContent: String? = null,
)

@Serializable
data class UnsignedDataObjectPropertiesType(
  @XmlElement(false)
  @XmlSerialName("Id")
  val id: String? = null,
  @XmlElement(true)
  @XmlSerialName(
    "UnsignedDataObjectProperty",
    namespace = "http://uri.etsi.org/01903/v1.3.2#",
  )
  val unsignedDataObjectProperty: List<AnyType> = emptyList(),
)

@Serializable
data class QualifyingPropertiesReferenceType(
  @XmlElement(false)
  @XmlSerialName("URI")
  val uri: String,
  @XmlElement(false)
  @XmlSerialName("Id")
  val id: String? = null,
)

@Serializable
data class CertIDListType(
  @XmlElement(true)
  @XmlSerialName(
    "Cert",
    namespace = "http://uri.etsi.org/01903/v1.3.2#",
  )
  val cert: List<CertIDType> = emptyList(),
)

@Serializable
data class CertIDType(
  @XmlElement(false)
  @XmlSerialName("URI")
  val uri: String? = null,
  @XmlElement(true)
  @XmlSerialName(
    "CertDigest",
    namespace = "http://uri.etsi.org/01903/v1.3.2#",
  )
  val certDigest: DigestAlgAndValueType,
  @XmlElement(true)
  @XmlSerialName(
    "IssuerSerial",
    namespace = "http://uri.etsi.org/01903/v1.3.2#",
  )
  val issuerSerial: X509IssuerSerialType,
)

@Serializable
data class DigestAlgAndValueType(
  @XmlElement(true)
  @XmlSerialName(
    "DigestMethod",
    namespace = "http://www.w3.org/2000/09/xmldsig#",
  )
  val digestMethod: DigestMethod,
  @XmlElement(true)
  @XmlSerialName(
    "DigestValue",
    namespace = "http://www.w3.org/2000/09/xmldsig#",
  )
  val digestValue: String,
)

@Serializable
data class SignaturePolicyIdentifierType(
  @XmlElement(true)
  @XmlSerialName(
    "SignaturePolicyId",
    namespace = "http://uri.etsi.org/01903/v1.3.2#",
  )
  val signaturePolicyId: SignaturePolicyIdType? = null,
  @XmlElement(true)
  @XmlSerialName(
    "SignaturePolicyImplied",
    namespace = "http://uri.etsi.org/01903/v1.3.2#",
  )
  val signaturePolicyImplied: String? = null,
)

@Serializable
data class SignaturePolicyIdType(
  @XmlElement(true)
  @XmlSerialName(
    "SigPolicyId",
    namespace = "http://uri.etsi.org/01903/v1.3.2#",
  )
  val sigPolicyId: ObjectIdentifierType,
  @XmlElement(true)
  @XmlSerialName(
    "Transforms",
    namespace = "http://www.w3.org/2000/09/xmldsig#",
  )
  val transforms: Transforms? = null,
  @XmlElement(true)
  @XmlSerialName(
    "SigPolicyHash",
    namespace = "http://uri.etsi.org/01903/v1.3.2#",
  )
  val sigPolicyHash: DigestAlgAndValueType,
  @XmlElement(true)
  @XmlSerialName(
    "SigPolicyQualifiers",
    namespace = "http://uri.etsi.org/01903/v1.3.2#",
  )
  val sigPolicyQualifiers: SigPolicyQualifiersListType? = null,
)

@Serializable
data class SigPolicyQualifiersListType(
  @XmlElement(true)
  @XmlSerialName(
    "SigPolicyQualifier",
    namespace = "http://uri.etsi.org/01903/v1.3.2#",
  )
  val sigPolicyQualifier: List<AnyType> = emptyList(),
)

@Serializable
data class SPUserNoticeType(
  @XmlElement(true)
  @XmlSerialName(
    "NoticeRef",
    namespace = "http://uri.etsi.org/01903/v1.3.2#",
  )
  val noticeRef: NoticeReferenceType? = null,
  @XmlElement(true)
  @XmlSerialName(
    "ExplicitText",
    namespace = "http://uri.etsi.org/01903/v1.3.2#",
  )
  val explicitText: String? = null,
)

@Serializable
data class NoticeReferenceType(
  @XmlElement(true)
  @XmlSerialName(
    "Organization",
    namespace = "http://uri.etsi.org/01903/v1.3.2#",
  )
  val organization: String,
  @XmlElement(true)
  @XmlSerialName(
    "NoticeNumbers",
    namespace = "http://uri.etsi.org/01903/v1.3.2#",
  )
  val noticeNumbers: IntegerListType,
)

@Serializable
data class IntegerListType(
  @XmlElement(true)
  @XmlSerialName(
    "int",
    namespace = "http://uri.etsi.org/01903/v1.3.2#",
  )
  val int: List<Int> = emptyList(),
)

@Serializable
data class CounterSignatureType(
  @XmlElement(true)
  @XmlSerialName(
    "Signature",
    namespace = "http://www.w3.org/2000/09/xmldsig#",
  )
  val signature: Signature,
)

@Serializable
data class DataObjectFormatType(
  @XmlElement(false)
  @XmlSerialName("ObjectReference")
  val objectReference: String,
  @XmlElement(true)
  @XmlSerialName(
    "Description",
    namespace = "http://uri.etsi.org/01903/v1.3.2#",
  )
  val description: String? = null,
  @XmlElement(true)
  @XmlSerialName(
    "ObjectIdentifier",
    namespace = "http://uri.etsi.org/01903/v1.3.2#",
  )
  val objectIdentifier: ObjectIdentifierType? = null,
  @XmlElement(true)
  @XmlSerialName(
    "MimeType",
    namespace = "http://uri.etsi.org/01903/v1.3.2#",
  )
  val mimeType: String? = null,
  @XmlElement(true)
  @XmlSerialName(
    "Encoding",
    namespace = "http://uri.etsi.org/01903/v1.3.2#",
  )
  val encoding: String? = null,
)

@Serializable
data class CommitmentTypeIndicationType(
  @XmlElement(true)
  @XmlSerialName(
    "CommitmentTypeId",
    namespace = "http://uri.etsi.org/01903/v1.3.2#",
  )
  val commitmentTypeId: ObjectIdentifierType,
  @XmlElement(true)
  @XmlSerialName(
    "ObjectReference",
    namespace = "http://uri.etsi.org/01903/v1.3.2#",
  )
  val objectReference: List<String> = emptyList(),
  @XmlElement(true)
  @XmlSerialName(
    "AllSignedDataObjects",
    namespace = "http://uri.etsi.org/01903/v1.3.2#",
  )
  val allSignedDataObjects: String? = null,
  @XmlElement(true)
  @XmlSerialName(
    "CommitmentTypeQualifiers",
    namespace = "http://uri.etsi.org/01903/v1.3.2#",
  )
  val commitmentTypeQualifiers: CommitmentTypeQualifiersListType? = null,
)

@Serializable
data class CommitmentTypeQualifiersListType(
  @XmlElement(true)
  @XmlSerialName(
    "CommitmentTypeQualifier",
    namespace = "http://uri.etsi.org/01903/v1.3.2#",
  )
  val commitmentTypeQualifier: List<AnyType> = emptyList(),
)

@Serializable
data class SignatureProductionPlaceType(
  @XmlElement(true)
  @XmlSerialName(
    "City",
    namespace = "http://uri.etsi.org/01903/v1.3.2#",
  )
  val city: String? = null,
  @XmlElement(true)
  @XmlSerialName(
    "StateOrProvince",
    namespace = "http://uri.etsi.org/01903/v1.3.2#",
  )
  val stateOrProvince: String? = null,
  @XmlElement(true)
  @XmlSerialName(
    "PostalCode",
    namespace = "http://uri.etsi.org/01903/v1.3.2#",
  )
  val postalCode: String? = null,
  @XmlElement(true)
  @XmlSerialName(
    "CountryName",
    namespace = "http://uri.etsi.org/01903/v1.3.2#",
  )
  val countryName: String? = null,
)

@Serializable
data class SignerRoleType(
  @XmlElement(true)
  @XmlSerialName(
    "ClaimedRoles",
    namespace = "http://uri.etsi.org/01903/v1.3.2#",
  )
  val claimedRoles: ClaimedRolesListType? = null,
  @XmlElement(true)
  @XmlSerialName(
    "CertifiedRoles",
    namespace = "http://uri.etsi.org/01903/v1.3.2#",
  )
  val certifiedRoles: CertifiedRolesListType? = null,
)

@Serializable
data class ClaimedRolesListType(
  @XmlElement(true)
  @XmlSerialName(
    "ClaimedRole",
    namespace = "http://uri.etsi.org/01903/v1.3.2#",
  )
  val claimedRole: List<AnyType> = emptyList(),
)

@Serializable
data class CertifiedRolesListType(
  @XmlElement(true)
  @XmlSerialName(
    "CertifiedRole",
    namespace = "http://uri.etsi.org/01903/v1.3.2#",
  )
  val certifiedRole: List<EncapsulatedPKIDataType> = emptyList(),
)

@Serializable
data class CompleteCertificateRefsType(
  @XmlElement(false)
  @XmlSerialName("Id")
  val id: String? = null,
  @XmlElement(true)
  @XmlSerialName(
    "CertRefs",
    namespace = "http://uri.etsi.org/01903/v1.3.2#",
  )
  val certRefs: CertIDListType,
)

@Serializable
data class CompleteRevocationRefsType(
  @XmlElement(false)
  @XmlSerialName("Id")
  val id: String? = null,
  @XmlElement(true)
  @XmlSerialName(
    "CRLRefs",
    namespace = "http://uri.etsi.org/01903/v1.3.2#",
  )
  val crlRefs: CRLRefsType? = null,
  @XmlElement(true)
  @XmlSerialName(
    "OCSPRefs",
    namespace = "http://uri.etsi.org/01903/v1.3.2#",
  )
  val ocspRefs: OCSPRefsType? = null,
  @XmlElement(true)
  @XmlSerialName(
    "OtherRefs",
    namespace = "http://uri.etsi.org/01903/v1.3.2#",
  )
  val otherRefs: OtherCertStatusRefsType? = null,
)

@Serializable
data class CRLRefsType(
  @XmlElement(true)
  @XmlSerialName(
    "CRLRef",
    namespace = "http://uri.etsi.org/01903/v1.3.2#",
  )
  val crlRef: List<CRLRefType> = emptyList(),
)

@Serializable
data class CRLRefType(
  @XmlElement(true)
  @XmlSerialName(
    "DigestAlgAndValue",
    namespace = "http://uri.etsi.org/01903/v1.3.2#",
  )
  val digestAlgAndValue: DigestAlgAndValueType,
  @XmlElement(true)
  @XmlSerialName(
    "CRLIdentifier",
    namespace = "http://uri.etsi.org/01903/v1.3.2#",
  )
  val crlIdentifier: CRLIdentifierType? = null,
)

@Serializable
data class CRLIdentifierType(
  @XmlElement(false)
  @XmlSerialName("URI")
  val uri: String? = null,
  @XmlElement(true)
  @XmlSerialName(
    "Issuer",
    namespace = "http://uri.etsi.org/01903/v1.3.2#",
  )
  val issuer: String,
  @XmlElement(true)
  @XmlSerialName(
    "IssueTime",
    namespace = "http://uri.etsi.org/01903/v1.3.2#",
  )
  val issueTime: String,
  @XmlElement(true)
  @XmlSerialName(
    "Number",
    namespace = "http://uri.etsi.org/01903/v1.3.2#",
  )
  val number: Int? = null,
)

@Serializable
data class OCSPRefsType(
  @XmlElement(true)
  @XmlSerialName(
    "OCSPRef",
    namespace = "http://uri.etsi.org/01903/v1.3.2#",
  )
  val ocspRef: List<OCSPRefType> = emptyList(),
)

@Serializable
data class OCSPRefType(
  @XmlElement(true)
  @XmlSerialName(
    "OCSPIdentifier",
    namespace = "http://uri.etsi.org/01903/v1.3.2#",
  )
  val ocspIdentifier: OCSPIdentifierType,
  @XmlElement(true)
  @XmlSerialName(
    "DigestAlgAndValue",
    namespace = "http://uri.etsi.org/01903/v1.3.2#",
  )
  val digestAlgAndValue: DigestAlgAndValueType? = null,
)

@Serializable
data class ResponderIDType(
  @XmlElement(true)
  @XmlSerialName(
    "ByName",
    namespace = "http://uri.etsi.org/01903/v1.3.2#",
  )
  val byName: String? = null,
  @XmlElement(true)
  @XmlSerialName(
    "ByKey",
    namespace = "http://uri.etsi.org/01903/v1.3.2#",
  )
  val byKey: String? = null,
)

@Serializable
data class OCSPIdentifierType(
  @XmlElement(false)
  @XmlSerialName("URI")
  val uri: String? = null,
  @XmlElement(true)
  @XmlSerialName(
    "ResponderID",
    namespace = "http://uri.etsi.org/01903/v1.3.2#",
  )
  val responderId: ResponderIDType,
  @XmlElement(true)
  @XmlSerialName(
    "ProducedAt",
    namespace = "http://uri.etsi.org/01903/v1.3.2#",
  )
  val producedAt: String,
)

@Serializable
data class OtherCertStatusRefsType(
  @XmlElement(true)
  @XmlSerialName(
    "OtherRef",
    namespace = "http://uri.etsi.org/01903/v1.3.2#",
  )
  val otherRef: List<AnyType> = emptyList(),
)

@Serializable
data class CertificateValuesType(
  @XmlElement(false)
  @XmlSerialName("Id")
  val id: String? = null,
  @XmlElement(true)
  @XmlSerialName(
    "EncapsulatedX509Certificate",
    namespace = "http://uri.etsi.org/01903/v1.3.2#",
  )
  val encapsulatedX509Certificate: List<EncapsulatedPKIDataType> = emptyList(),
  @XmlElement(true)
  @XmlSerialName(
    "OtherCertificate",
    namespace = "http://uri.etsi.org/01903/v1.3.2#",
  )
  val otherCertificate: List<AnyType> = emptyList(),
)

@Serializable
data class RevocationValuesType(
  @XmlElement(false)
  @XmlSerialName("Id")
  val id: String? = null,
  @XmlElement(true)
  @XmlSerialName(
    "CRLValues",
    namespace = "http://uri.etsi.org/01903/v1.3.2#",
  )
  val crlValues: CRLValuesType? = null,
  @XmlElement(true)
  @XmlSerialName(
    "OCSPValues",
    namespace = "http://uri.etsi.org/01903/v1.3.2#",
  )
  val ocspValues: OCSPValuesType? = null,
  @XmlElement(true)
  @XmlSerialName(
    "OtherValues",
    namespace = "http://uri.etsi.org/01903/v1.3.2#",
  )
  val otherValues: OtherCertStatusValuesType? = null,
)

@Serializable
data class CRLValuesType(
  @XmlElement(true)
  @XmlSerialName(
    "EncapsulatedCRLValue",
    namespace = "http://uri.etsi.org/01903/v1.3.2#",
  )
  val encapsulatedCrlValue: List<EncapsulatedPKIDataType> = emptyList(),
)

@Serializable
data class OCSPValuesType(
  @XmlElement(true)
  @XmlSerialName(
    "EncapsulatedOCSPValue",
    namespace = "http://uri.etsi.org/01903/v1.3.2#",
  )
  val encapsulatedOcspValue: List<EncapsulatedPKIDataType> = emptyList(),
)

@Serializable
data class OtherCertStatusValuesType(
  @XmlElement(true)
  @XmlSerialName(
    "OtherValue",
    namespace = "http://uri.etsi.org/01903/v1.3.2#",
  )
  val otherValue: List<AnyType> = emptyList(),
)
