// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.etsi01903132

import kotlin.String
import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName

@Serializable
@XmlSerialName(
  "SignedSignatureProperties",
  namespace = "http://uri.etsi.org/01903/v1.3.2#",
)
data class SignedSignatureProperties(
  @XmlElement(false)
  @XmlSerialName("Id")
  val id: String? = null,
  @XmlElement(true)
  @XmlSerialName("SigningTime")
  val signingTime: String? = null,
  @XmlElement(true)
  @XmlSerialName("SigningCertificate")
  val signingCertificate: CertIDListType? = null,
  @XmlElement(true)
  @XmlSerialName("SignaturePolicyIdentifier")
  val signaturePolicyIdentifier: SignaturePolicyIdentifierType? = null,
  @XmlElement(true)
  @XmlSerialName("SignatureProductionPlace")
  val signatureProductionPlace: SignatureProductionPlaceType? = null,
  @XmlElement(true)
  @XmlSerialName("SignerRole")
  val signerRole: SignerRoleType? = null,
)
