// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.etsi01903132

import kotlin.String
import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName

@Serializable
data class SignedSignaturePropertiesType(
  @XmlElement(false)
  @XmlSerialName("Id")
  val id: String? = null,
  @XmlElement(true)
  @XmlSerialName(
    "SigningTime",
    namespace = "http://uri.etsi.org/01903/v1.3.2#",
  )
  val signingTime: String? = null,
  @XmlElement(true)
  @XmlSerialName(
    "SigningCertificate",
    namespace = "http://uri.etsi.org/01903/v1.3.2#",
  )
  val signingCertificate: CertIDListType? = null,
  @XmlElement(true)
  @XmlSerialName(
    "SignaturePolicyIdentifier",
    namespace = "http://uri.etsi.org/01903/v1.3.2#",
  )
  val signaturePolicyIdentifier: SignaturePolicyIdentifierType? = null,
  @XmlElement(true)
  @XmlSerialName(
    "SignatureProductionPlace",
    namespace = "http://uri.etsi.org/01903/v1.3.2#",
  )
  val signatureProductionPlace: SignatureProductionPlaceType? = null,
  @XmlElement(true)
  @XmlSerialName(
    "SignerRole",
    namespace = "http://uri.etsi.org/01903/v1.3.2#",
  )
  val signerRole: SignerRoleType? = null,
)
