// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.etsi01903132

import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName

@Serializable
@XmlSerialName(
  "SignerRole",
  namespace = "http://uri.etsi.org/01903/v1.3.2#",
)
data class SignerRole(
  @XmlElement(true)
  @XmlSerialName("ClaimedRoles")
  val claimedRoles: ClaimedRolesListType? = null,
  @XmlElement(true)
  @XmlSerialName("CertifiedRoles")
  val certifiedRoles: CertifiedRolesListType? = null,
)
