// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.etsi01903132

import kotlin.String
import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName

@Serializable
data class SignaturePolicyIdentifierType(
  @XmlElement(true)
  @XmlSerialName(
    "SignaturePolicyId",
    namespace = "http://uri.etsi.org/01903/v1.3.2#",
  )
  val signaturePolicyId: SignaturePolicyIdType? = null,
  @XmlElement(true)
  @XmlSerialName(
    "SignaturePolicyImplied",
    namespace = "http://uri.etsi.org/01903/v1.3.2#",
  )
  val signaturePolicyImplied: String? = null,
)
