// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.etsi01903132

import kotlin.String
import kotlin.collections.List
import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName

@Serializable
data class SignedDataObjectPropertiesType(
  @XmlElement(false)
  @XmlSerialName("Id")
  val id: String? = null,
  @XmlElement(true)
  @XmlSerialName(
    "DataObjectFormat",
    namespace = "http://uri.etsi.org/01903/v1.3.2#",
  )
  val dataObjectFormat: List<DataObjectFormatType> = emptyList(),
  @XmlElement(true)
  @XmlSerialName(
    "CommitmentTypeIndication",
    namespace = "http://uri.etsi.org/01903/v1.3.2#",
  )
  val commitmentTypeIndication: List<CommitmentTypeIndicationType> = emptyList(),
  @XmlElement(true)
  @XmlSerialName(
    "AllDataObjectsTimeStamp",
    namespace = "http://uri.etsi.org/01903/v1.3.2#",
  )
  val allDataObjectsTimeStamp: List<XAdESTimeStampType> = emptyList(),
  @XmlElement(true)
  @XmlSerialName(
    "IndividualDataObjectsTimeStamp",
    namespace = "http://uri.etsi.org/01903/v1.3.2#",
  )
  val individualDataObjectsTimeStamp: List<XAdESTimeStampType> = emptyList(),
)
