// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.etsi01903132

import kotlin.String
import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName

@Serializable
data class SPUserNoticeType(
  @XmlElement(true)
  @XmlSerialName(
    "NoticeRef",
    namespace = "http://uri.etsi.org/01903/v1.3.2#",
  )
  val noticeRef: NoticeReferenceType? = null,
  @XmlElement(true)
  @XmlSerialName(
    "ExplicitText",
    namespace = "http://uri.etsi.org/01903/v1.3.2#",
  )
  val explicitText: String? = null,
)
