// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.etsi01903132

import kotlin.String
import kotlin.collections.List
import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName

@Serializable
data class UnsignedSignaturePropertiesType(
  @XmlElement(false)
  @XmlSerialName("Id")
  val id: String? = null,
  @XmlElement(true)
  @XmlSerialName(
    "CounterSignature",
    namespace = "http://uri.etsi.org/01903/v1.3.2#",
  )
  val counterSignature: List<CounterSignatureType> = emptyList(),
  @XmlElement(true)
  @XmlSerialName(
    "SignatureTimeStamp",
    namespace = "http://uri.etsi.org/01903/v1.3.2#",
  )
  val signatureTimeStamp: List<XAdESTimeStampType> = emptyList(),
  @XmlElement(true)
  @XmlSerialName(
    "CompleteCertificateRefs",
    namespace = "http://uri.etsi.org/01903/v1.3.2#",
  )
  val completeCertificateRefs: List<CompleteCertificateRefsType> = emptyList(),
  @XmlElement(true)
  @XmlSerialName(
    "CompleteRevocationRefs",
    namespace = "http://uri.etsi.org/01903/v1.3.2#",
  )
  val completeRevocationRefs: List<CompleteRevocationRefsType> = emptyList(),
  @XmlElement(true)
  @XmlSerialName(
    "AttributeCertificateRefs",
    namespace = "http://uri.etsi.org/01903/v1.3.2#",
  )
  val attributeCertificateRefs: List<CompleteCertificateRefsType> = emptyList(),
  @XmlElement(true)
  @XmlSerialName(
    "AttributeRevocationRefs",
    namespace = "http://uri.etsi.org/01903/v1.3.2#",
  )
  val attributeRevocationRefs: List<CompleteRevocationRefsType> = emptyList(),
  @XmlElement(true)
  @XmlSerialName(
    "SigAndRefsTimeStamp",
    namespace = "http://uri.etsi.org/01903/v1.3.2#",
  )
  val sigAndRefsTimeStamp: List<XAdESTimeStampType> = emptyList(),
  @XmlElement(true)
  @XmlSerialName(
    "RefsOnlyTimeStamp",
    namespace = "http://uri.etsi.org/01903/v1.3.2#",
  )
  val refsOnlyTimeStamp: List<XAdESTimeStampType> = emptyList(),
  @XmlElement(true)
  @XmlSerialName(
    "CertificateValues",
    namespace = "http://uri.etsi.org/01903/v1.3.2#",
  )
  val certificateValues: List<CertificateValuesType> = emptyList(),
  @XmlElement(true)
  @XmlSerialName(
    "RevocationValues",
    namespace = "http://uri.etsi.org/01903/v1.3.2#",
  )
  val revocationValues: List<RevocationValuesType> = emptyList(),
  @XmlElement(true)
  @XmlSerialName(
    "AttrAuthoritiesCertValues",
    namespace = "http://uri.etsi.org/01903/v1.3.2#",
  )
  val attrAuthoritiesCertValues: List<CertificateValuesType> = emptyList(),
  @XmlElement(true)
  @XmlSerialName(
    "AttributeRevocationValues",
    namespace = "http://uri.etsi.org/01903/v1.3.2#",
  )
  val attributeRevocationValues: List<RevocationValuesType> = emptyList(),
  @XmlElement(true)
  @XmlSerialName(
    "ArchiveTimeStamp",
    namespace = "http://uri.etsi.org/01903/v1.3.2#",
  )
  val archiveTimeStamp: List<XAdESTimeStampType> = emptyList(),
  @XmlElement(true)
  val unknownContent: String? = null,
)
