// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.etsi01903132

import kotlin.String
import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName

@Serializable
@XmlSerialName(
  "UnsignedProperties",
  namespace = "http://uri.etsi.org/01903/v1.3.2#",
)
data class UnsignedProperties(
  @XmlElement(false)
  @XmlSerialName("Id")
  val id: String? = null,
  @XmlElement(true)
  @XmlSerialName("UnsignedSignatureProperties")
  val unsignedSignatureProperties: UnsignedSignaturePropertiesType? = null,
  @XmlElement(true)
  @XmlSerialName("UnsignedDataObjectProperties")
  val unsignedDataObjectProperties: UnsignedDataObjectPropertiesType? = null,
)
