// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.etsi01903132

import kotlin.String
import kotlin.collections.List
import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName

@Serializable
@XmlSerialName(
  "UnsignedSignatureProperties",
  namespace = "http://uri.etsi.org/01903/v1.3.2#",
)
data class UnsignedSignatureProperties(
  @XmlElement(false)
  @XmlSerialName("Id")
  val id: String? = null,
  @XmlElement(true)
  @XmlSerialName("CounterSignature")
  val counterSignature: List<CounterSignatureType> = emptyList(),
  @XmlElement(true)
  @XmlSerialName("SignatureTimeStamp")
  val signatureTimeStamp: List<XAdESTimeStampType> = emptyList(),
  @XmlElement(true)
  @XmlSerialName("CompleteCertificateRefs")
  val completeCertificateRefs: List<CompleteCertificateRefsType> = emptyList(),
  @XmlElement(true)
  @XmlSerialName("CompleteRevocationRefs")
  val completeRevocationRefs: List<CompleteRevocationRefsType> = emptyList(),
  @XmlElement(true)
  @XmlSerialName("AttributeCertificateRefs")
  val attributeCertificateRefs: List<CompleteCertificateRefsType> = emptyList(),
  @XmlElement(true)
  @XmlSerialName("AttributeRevocationRefs")
  val attributeRevocationRefs: List<CompleteRevocationRefsType> = emptyList(),
  @XmlElement(true)
  @XmlSerialName("SigAndRefsTimeStamp")
  val sigAndRefsTimeStamp: List<XAdESTimeStampType> = emptyList(),
  @XmlElement(true)
  @XmlSerialName("RefsOnlyTimeStamp")
  val refsOnlyTimeStamp: List<XAdESTimeStampType> = emptyList(),
  @XmlElement(true)
  @XmlSerialName("CertificateValues")
  val certificateValues: List<CertificateValuesType> = emptyList(),
  @XmlElement(true)
  @XmlSerialName("RevocationValues")
  val revocationValues: List<RevocationValuesType> = emptyList(),
  @XmlElement(true)
  @XmlSerialName("AttrAuthoritiesCertValues")
  val attrAuthoritiesCertValues: List<CertificateValuesType> = emptyList(),
  @XmlElement(true)
  @XmlSerialName("AttributeRevocationValues")
  val attributeRevocationValues: List<RevocationValuesType> = emptyList(),
  @XmlElement(true)
  @XmlSerialName("ArchiveTimeStamp")
  val archiveTimeStamp: List<XAdESTimeStampType> = emptyList(),
  @XmlElement(true)
  val unknownContent: String? = null,
)
