// Code generated by wsdl2openapi; DO NOT EDIT.
package de.gematik.connector.api.gematik.consumer.certificateservice300

import de.gematik.connector.api.gematik.consumer.certificateservicecommon20.X509DataInfoList
import de.gematik.connector.api.gematik.consumer.consumercommon20.Status
import de.gematik.connector.api.gematik.tel.error20.Error
import kotlin.String
import kotlin.collections.List
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName

@Serializable
@XmlSerialName(
  "ReadCertificate",
  namespace = "http://ws.gematik.de/consumer/CertificateService/v3.0",
)
data class ReadCertificate(
  @XmlElement(true)
  @XmlSerialName(
    "CardHandle",
    namespace = "http://ws.gematik.de/consumer/ConsumerCommon/v2.0",
  )
  val cardHandle: String,
  @XmlElement(true)
  @XmlSerialName("CertRefList")
  val certRefList: ReadCertificateCertRefList,
  @XmlElement(true)
  @XmlSerialName("Crypt")
  val crypt: CryptType? = null,
)

@Serializable
@XmlSerialName(
  "ReadCertificateResponse",
  namespace = "http://ws.gematik.de/consumer/CertificateService/v3.0",
)
data class ReadCertificateResponse(
  @XmlElement(true)
  @XmlSerialName(
    "Status",
    namespace = "http://ws.gematik.de/consumer/ConsumerCommon/v2.0",
  )
  val status: Status,
  @XmlElement(true)
  @XmlSerialName(
    "X509DataInfoList",
    namespace = "http://ws.gematik.de/consumer/CertificateServiceCommon/v2.0",
  )
  val x509DataInfoList: X509DataInfoList,
)

@Serializable
@XmlSerialName(
  "VerifyCertificate",
  namespace = "http://ws.gematik.de/consumer/CertificateService/v3.0",
)
data class VerifyCertificate(
  @XmlElement(true)
  @XmlSerialName(
    "X509Certificate",
    namespace = "http://ws.gematik.de/consumer/CertificateServiceCommon/v2.0",
  )
  val x509Certificate: String,
  @XmlElement(true)
  @XmlSerialName("VerificationTime")
  val verificationTime: String? = null,
)

@Serializable
@XmlSerialName(
  "VerifyCertificateResponse",
  namespace = "http://ws.gematik.de/consumer/CertificateService/v3.0",
)
data class VerifyCertificateResponse(
  @XmlElement(true)
  @XmlSerialName(
    "Status",
    namespace = "http://ws.gematik.de/consumer/ConsumerCommon/v2.0",
  )
  val status: Status,
  @XmlElement(true)
  @XmlSerialName("VerificationStatus")
  val verificationStatus: VerifyCertificateResponseVerificationStatus,
  @XmlElement(true)
  @XmlSerialName("RoleList")
  val roleList: VerifyCertificateResponseRoleList,
)

@Serializable
enum class CryptType {
  @SerialName("RSA")
  Rsa,
  @SerialName("ECC")
  Ecc,
}

@Serializable
enum class VerificationResultType {
  @SerialName("VALID")
  Valid,
  @SerialName("INCONCLUSIVE")
  Inconclusive,
  @SerialName("INVALID")
  Invalid,
}

@Serializable
@XmlSerialName(
  "CertRefList",
  namespace = "http://ws.gematik.de/consumer/CertificateService/v3.0",
)
data class ReadCertificateCertRefList(
  @XmlElement(true)
  @XmlSerialName("CertRef")
  val certRef: List<String> = emptyList(),
)

@Serializable
@XmlSerialName(
  "VerificationStatus",
  namespace = "http://ws.gematik.de/consumer/CertificateService/v3.0",
)
data class VerifyCertificateResponseVerificationStatus(
  @XmlElement(true)
  @XmlSerialName("VerificationResult")
  val verificationResult: VerificationResultType,
  @XmlElement(true)
  @XmlSerialName(
    "Error",
    namespace = "http://ws.gematik.de/tel/error/v2.0",
  )
  val error: Error? = null,
)

@Serializable
@XmlSerialName(
  "RoleList",
  namespace = "http://ws.gematik.de/consumer/CertificateService/v3.0",
)
data class VerifyCertificateResponseRoleList(
  @XmlElement(true)
  @XmlSerialName("Role")
  val role: List<String> = emptyList(),
)
